<%
' CDONTS Constants 

' CDONTS Attachment.Type values 
Const CayriDosya = 1
Const CgomuluMesaj = 4

' CDONTS Message.Importance Values.  Also used in NewMail.Importance
Const Cdusuk = 0
Const Cnormal = 1
Const Cyuksek = 2

' CDONTS Message.MessageFormat and Session.MessageFormat Values 
Const CmesMime = 0
Const CmesText = 1

' CDONTS NewMail.AttachFile and NewMail.AttachURL EncodingMethod Values 
Const CuUencode = 0
Const Cbase64 = 1

' CDONTS NewMail.BodyFormat Values 
Const CmailHtml = 0
Const CmailText = 1

' CDONTS NewMail.MailFormat Values 
Const CmailMime = 0
Const CmailText = 1

' CDONTS Recipient.Type Values 
Const CmailTo = 1
Const CmailCc = 2
Const CmailBcc = 3

' CDONTS Session.GetDefaultFolder Values 
Const CmailDefaultFolderInbox = 1
Const CmailDefaultFolderOutbox = 2
%>