import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'sdal_theme_tokens.dart';
import 'sdal_ux_profile.dart';

enum SdalAppTheme {
  kor,
  atlas,
  vibe,
  zinc,
  ember,
  mist,
  nova,
  prism,
  dusk,
  flux;

  static SdalAppTheme fromString(String? value) {
    return switch (value?.toLowerCase().trim()) {
      'atlas' => atlas,
      'vibe'  => vibe,
      'zinc'  => zinc,
      'ember' => ember,
      'mist'  => mist,
      'nova'  => nova,
      'prism' => prism,
      'dusk'  => dusk,
      'flux'  => flux,
      _       => kor,
    };
  }

  String get id => name;

  String get displayName => switch (this) {
    kor   => 'Kor',
    atlas => 'Atlas',
    vibe  => 'Vibe',
    zinc  => 'Zinc',
    ember => 'Ember',
    mist  => 'Mist',
    nova  => 'Nova',
    prism => 'Prism',
    dusk  => 'Dusk',
    flux  => 'Flux',
  };

  String get tagline => switch (this) {
    kor   => 'Sıcak & samimi',
    atlas => 'Premium & kobalt',
    vibe  => 'Elektrik & canlı',
    zinc  => 'Noir & keskin',
    ember => 'Lüks & altın',
    mist  => 'Zümrüt & taze',
    nova  => 'Uzaysal cam & zerafet',
    prism => 'Modüler bento & netlik',
    dusk  => 'Sinematik karanlık & dramatik',
    flux  => 'Dinamik & uyarlanabilir',
  };

  /// Dark-mode accent for watchOS .tint().
  Color get watchAccent => switch (this) {
    kor   => const Color(0xFF818CF8),
    atlas => const Color(0xFF4D9FFF),
    vibe  => const Color(0xFFB47FFF),
    zinc  => const Color(0xFF22D3EE),
    ember => const Color(0xFFFFB800),
    mist  => const Color(0xFF51CF66),
    nova  => const Color(0xFF60A5FA),
    prism => const Color(0xFFA78BFA),
    dusk  => const Color(0xFFFBBF24),
    flux  => const Color(0xFF2DD4BF),
  };

  /// Three representative swatch colors for the theme picker.
  List<Color> get swatches => switch (this) {
    kor   => const [Color(0xFF818CF8), Color(0xFF3E3FBC), Color(0xFF0C0C1E)],
    atlas => const [Color(0xFF4D9FFF), Color(0xFF1060A0), Color(0xFF0A1428)],
    vibe  => const [Color(0xFFB47FFF), Color(0xFF6200EE), Color(0xFF110820)],
    zinc  => const [Color(0xFF22D3EE), Color(0xFF0891B2), Color(0xFF0A0A0B)],
    ember => const [Color(0xFFFFB800), Color(0xFFD4700A), Color(0xFF1A1000)],
    mist  => const [Color(0xFF51CF66), Color(0xFF087F5B), Color(0xFF081210)],
    nova  => const [Color(0xFF60A5FA), Color(0xFF1D4ED8), Color(0xFF05060F)],
    prism => const [Color(0xFFA78BFA), Color(0xFF7C3AED), Color(0xFF0F0F14)],
    dusk  => const [Color(0xFFFBBF24), Color(0xFFEF4444), Color(0xFF0A0806)],
    flux  => const [Color(0xFF2DD4BF), Color(0xFF0D9488), Color(0xFF0A1512)],
  };

  String get logoAsset => 'assets/logo_$name.png';

  SdalThemeTokens get lightTokens => switch (this) {
    kor   => SdalThemeTokens.light,
    atlas => _atlasLight,
    vibe  => _vibeLight,
    zinc  => _zincLight,
    ember => _emberLight,
    mist  => _mistLight,
    nova  => _novaLight,
    prism => _prismLight,
    dusk  => _duskLight,
    flux  => _fluxLight,
  };

  SdalThemeTokens get darkTokens => switch (this) {
    kor   => SdalThemeTokens.dark,
    atlas => _atlasDark,
    vibe  => _vibeDark,
    zinc  => _zincDark,
    ember => _emberDark,
    mist  => _mistDark,
    nova  => _novaDark,
    prism => _prismDark,
    dusk  => _duskDark,
    flux  => _fluxDark,
  };

  SdalThemeTokens tokensFor(Brightness brightness) =>
      brightness == Brightness.dark ? darkTokens : lightTokens;

  // ---------------------------------------------------------------------------
  // Font integration
  // ---------------------------------------------------------------------------

  /// The ThemeData fontFamily string.
  /// Kor uses the local Manrope asset; others resolve via Google Fonts.
  String get materialFontFamily => switch (this) {
    kor   => 'Manrope',
    atlas => GoogleFonts.ibmPlexSans().fontFamily!,
    vibe  => GoogleFonts.nunito().fontFamily!,
    zinc  => GoogleFonts.dmSans().fontFamily!,
    ember => GoogleFonts.outfit().fontFamily!,
    mist  => GoogleFonts.jost().fontFamily!,
    nova  => GoogleFonts.spaceGrotesk().fontFamily!,
    prism => GoogleFonts.archivo().fontFamily!,
    dusk  => GoogleFonts.spaceGrotesk().fontFamily!,
    flux  => GoogleFonts.plusJakartaSans().fontFamily!,
  };

  /// Apply this theme's typeface to [base]. For Kor the base is returned
  /// unchanged because Manrope is already wired via [materialFontFamily].
  TextTheme applyFont(TextTheme base) => switch (this) {
    kor   => base,
    atlas => GoogleFonts.ibmPlexSansTextTheme(base),
    vibe  => GoogleFonts.nunitoTextTheme(base),
    zinc  => GoogleFonts.dmSansTextTheme(base),
    ember => GoogleFonts.outfitTextTheme(base),
    mist  => GoogleFonts.jostTextTheme(base),
    nova  => GoogleFonts.spaceGroteskTextTheme(base),
    prism => GoogleFonts.archivoTextTheme(base),
    dusk  => GoogleFonts.spaceGroteskTextTheme(base),
    flux  => GoogleFonts.plusJakartaSansTextTheme(base),
  };
}

// ---------------------------------------------------------------------------
// Atlas — deep cobalt, premium precision, clean navy depth
// ---------------------------------------------------------------------------

const _atlasLight = SdalThemeTokens(
  canvas: Color(0xFFF1F5FB),
  canvasSubtle: Color(0xFFE3EDF8),
  panel: Color(0xFFFBFDFF),
  panelRaised: Color(0xFFEBF2FB),
  panelMuted: Color(0xFFDAEAF8),
  panelBorder: Color(0xFFAAC8E8),
  accent: Color(0xFF1060A0),
  accentMuted: Color(0xFFCCE3F8),
  success: Color(0xFF1A6B48),
  successMuted: Color(0xFFD0EDE0),
  warning: Color(0xFF7A5A14),
  warningMuted: Color(0xFFF0E2C0),
  info: Color(0xFF244880),
  infoMuted: Color(0xFFCCD8F4),
  danger: Color(0xFF9E3430),
  dangerMuted: Color(0xFFF2D8D6),
  chatOutgoing: Color(0xFF1A4A70),
  chatIncoming: Color(0xFFFBFDFF),
  storyActive: Color(0xFF1060A0),
  storyInactive: Color(0xFFA4C2DC),
  storyOverlay: Color(0xB30A1628),
  imagePlaceholder: Color(0xFFCADEF2),
  imageError: Color(0xFFBCD0E8),
  foreground: Color(0xFF0A1628),
  foregroundMuted: Color(0xFF486078),
  foregroundOnAccent: Color(0xFFF0F8FF),
  adminExperiment: Color(0xFF4060B0),
  cardRadius: 12,
  buttonRadius: 10,
  inputRadius: 12,
  panelBorderWidth: 0.8,
  logoAsset: 'assets/logo_atlas.png',
);

const _atlasDark = SdalThemeTokens(
  canvas: Color(0xFF0A1428),
  canvasSubtle: Color(0xFF101E38),
  panel: Color(0xFF162040),
  panelRaised: Color(0xFF1C2A4C),
  panelMuted: Color(0xFF243460),
  panelBorder: Color(0xFF385068),
  accent: Color(0xFF4D9FFF),
  accentMuted: Color(0xFF1A3060),
  success: Color(0xFF60BA90),
  successMuted: Color(0xFF143428),
  warning: Color(0xFFCCAA48),
  warningMuted: Color(0xFF3A2C0E),
  info: Color(0xFF70C0E0),
  infoMuted: Color(0xFF143040),
  danger: Color(0xFFE08078),
  dangerMuted: Color(0xFF481E1E),
  chatOutgoing: Color(0xFF1E3C60),
  chatIncoming: Color(0xFF162040),
  storyActive: Color(0xFF4D9FFF),
  storyInactive: Color(0xFF385068),
  storyOverlay: Color(0xD904081E),
  imagePlaceholder: Color(0xFF223460),
  imageError: Color(0xFF2C3E58),
  foreground: Color(0xFFE8F2FF),
  foregroundMuted: Color(0xFF9ABBDC),
  foregroundOnAccent: Color(0xFF0A1428),
  adminExperiment: Color(0xFF80A0E0),
  cardRadius: 12,
  buttonRadius: 10,
  inputRadius: 12,
  panelBorderWidth: 0.8,
  logoAsset: 'assets/logo_atlas.png',
);

// ---------------------------------------------------------------------------
// Vibe — electric violet, vivid energy, bold saturated punch
// ---------------------------------------------------------------------------

const _vibeLight = SdalThemeTokens(
  canvas: Color(0xFFF7F3FF),
  canvasSubtle: Color(0xFFEDE4FF),
  panel: Color(0xFFFEFCFF),
  panelRaised: Color(0xFFF3ECFF),
  panelMuted: Color(0xFFE8DCFF),
  panelBorder: Color(0xFFCCB0F0),
  accent: Color(0xFF6200EE),
  accentMuted: Color(0xFFE8D6FF),
  success: Color(0xFF1E6844),
  successMuted: Color(0xFFD0EDE0),
  warning: Color(0xFF7A5814),
  warningMuted: Color(0xFFF2E2C0),
  info: Color(0xFF2A5080),
  infoMuted: Color(0xFFCCDCF4),
  danger: Color(0xFF9E3030),
  dangerMuted: Color(0xFFF4D4D4),
  chatOutgoing: Color(0xFF3A0A90),
  chatIncoming: Color(0xFFFEFCFF),
  storyActive: Color(0xFF6200EE),
  storyInactive: Color(0xFFBBA8E0),
  storyOverlay: Color(0xB3100820),
  imagePlaceholder: Color(0xFFDDD0FF),
  imageError: Color(0xFFCEC0F0),
  foreground: Color(0xFF14083A),
  foregroundMuted: Color(0xFF584878),
  foregroundOnAccent: Color(0xFFFAF4FF),
  adminExperiment: Color(0xFF9050E0),
  cardRadius: 24,
  buttonRadius: 22,
  inputRadius: 22,
  panelBorderWidth: 0.7,
  logoAsset: 'assets/logo_vibe.png',
);

const _vibeDark = SdalThemeTokens(
  canvas: Color(0xFF110820),
  canvasSubtle: Color(0xFF1A1030),
  panel: Color(0xFF221840),
  panelRaised: Color(0xFF2C2050),
  panelMuted: Color(0xFF382A60),
  panelBorder: Color(0xFF504078),
  accent: Color(0xFFB47FFF),
  accentMuted: Color(0xFF361A60),
  success: Color(0xFF68C090),
  successMuted: Color(0xFF183828),
  warning: Color(0xFFCCAA50),
  warningMuted: Color(0xFF3C2E10),
  info: Color(0xFF72C0E0),
  infoMuted: Color(0xFF163040),
  danger: Color(0xFFE08888),
  dangerMuted: Color(0xFF4A1E1E),
  chatOutgoing: Color(0xFF3A1070),
  chatIncoming: Color(0xFF221840),
  storyActive: Color(0xFFB47FFF),
  storyInactive: Color(0xFF504078),
  storyOverlay: Color(0xD90A0618),
  imagePlaceholder: Color(0xFF362A60),
  imageError: Color(0xFF44346C),
  foreground: Color(0xFFF2EEFF),
  foregroundMuted: Color(0xFFBBAAE0),
  foregroundOnAccent: Color(0xFF0E0420),
  adminExperiment: Color(0xFFCC90FF),
  cardRadius: 24,
  buttonRadius: 22,
  inputRadius: 22,
  panelBorderWidth: 0.7,
  logoAsset: 'assets/logo_vibe.png',
);

// ---------------------------------------------------------------------------
// Zinc — noir editorial, electric teal accent, razor-sharp
// ---------------------------------------------------------------------------

const _zincLight = SdalThemeTokens(
  canvas: Color(0xFFF3F4F6),
  canvasSubtle: Color(0xFFE6E8EC),
  panel: Color(0xFFFAFAFB),
  panelRaised: Color(0xFFEDEEF1),
  panelMuted: Color(0xFFDFE1E6),
  panelBorder: Color(0xFFBCC0C8),
  accent: Color(0xFF0891B2),
  accentMuted: Color(0xFFCCF0F8),
  success: Color(0xFF1E6844),
  successMuted: Color(0xFFD0EDE0),
  warning: Color(0xFF7A5A14),
  warningMuted: Color(0xFFF0E2C0),
  info: Color(0xFF1C4A6E),
  infoMuted: Color(0xFFCCDCF0),
  danger: Color(0xFF9E3430),
  dangerMuted: Color(0xFFF0D8D6),
  chatOutgoing: Color(0xFF1A3A48),
  chatIncoming: Color(0xFFFAFAFB),
  storyActive: Color(0xFF0891B2),
  storyInactive: Color(0xFFA0AABC),
  storyOverlay: Color(0xB30A0C10),
  imagePlaceholder: Color(0xFFD4D8E0),
  imageError: Color(0xFFC8CCD4),
  foreground: Color(0xFF101216),
  foregroundMuted: Color(0xFF545C68),
  foregroundOnAccent: Color(0xFFF0FAFF),
  adminExperiment: Color(0xFF4860A8),
  cardRadius: 6,
  buttonRadius: 4,
  inputRadius: 6,
  panelBorderWidth: 0.8,
  logoAsset: 'assets/logo_zinc.png',
);

const _zincDark = SdalThemeTokens(
  canvas: Color(0xFF0A0A0B),
  canvasSubtle: Color(0xFF101012),
  panel: Color(0xFF141416),
  panelRaised: Color(0xFF1C1C1E),
  panelMuted: Color(0xFF242428),
  panelBorder: Color(0xFF34343A),
  accent: Color(0xFF22D3EE),
  accentMuted: Color(0xFF0E2A2E),
  success: Color(0xFF4ADE80),
  successMuted: Color(0xFF0E2818),
  warning: Color(0xFFFBBF24),
  warningMuted: Color(0xFF2C2008),
  info: Color(0xFF38BDF8),
  infoMuted: Color(0xFF0C2030),
  danger: Color(0xFFF87171),
  dangerMuted: Color(0xFF2C1010),
  chatOutgoing: Color(0xFF1A3038),
  chatIncoming: Color(0xFF141416),
  storyActive: Color(0xFF22D3EE),
  storyInactive: Color(0xFF34343A),
  storyOverlay: Color(0xD9020204),
  imagePlaceholder: Color(0xFF1C1C24),
  imageError: Color(0xFF242430),
  foreground: Color(0xFFF4F4F5),
  foregroundMuted: Color(0xFF848490),
  foregroundOnAccent: Color(0xFF02080A),
  adminExperiment: Color(0xFF7090D8),
  cardRadius: 6,
  buttonRadius: 4,
  inputRadius: 6,
  panelBorderWidth: 0.8,
  logoAsset: 'assets/logo_zinc.png',
);

// ---------------------------------------------------------------------------
// Ember — wildfire amber, rich luxury gold, warm depth
// ---------------------------------------------------------------------------

const _emberLight = SdalThemeTokens(
  canvas: Color(0xFFFDF7EE),
  canvasSubtle: Color(0xFFF5E8D6),
  panel: Color(0xFFFFFEF8),
  panelRaised: Color(0xFFF8EDD8),
  panelMuted: Color(0xFFEEDCC0),
  panelBorder: Color(0xFFD4A860),
  accent: Color(0xFFD4700A),
  accentMuted: Color(0xFFFFF0CC),
  success: Color(0xFF1E6844),
  successMuted: Color(0xFFD0EDE0),
  warning: Color(0xFF8A5A10),
  warningMuted: Color(0xFFF2E0B8),
  info: Color(0xFF2A5478),
  infoMuted: Color(0xFFCCE4F4),
  danger: Color(0xFF9E3428),
  dangerMuted: Color(0xFFF4D4D0),
  chatOutgoing: Color(0xFF6A3800),
  chatIncoming: Color(0xFFFFFEF8),
  storyActive: Color(0xFFD4700A),
  storyInactive: Color(0xFFCCB080),
  storyOverlay: Color(0xB3221200),
  imagePlaceholder: Color(0xFFECDCAC),
  imageError: Color(0xFFE0CC9C),
  foreground: Color(0xFF2A1400),
  foregroundMuted: Color(0xFF6C4C1A),
  foregroundOnAccent: Color(0xFFFFFAF0),
  adminExperiment: Color(0xFF7050A0),
  cardRadius: 16,
  buttonRadius: 14,
  inputRadius: 14,
  panelBorderWidth: 0.8,
  logoAsset: 'assets/logo_ember.png',
);

const _emberDark = SdalThemeTokens(
  canvas: Color(0xFF1A1000),
  canvasSubtle: Color(0xFF221800),
  panel: Color(0xFF2C1C00),
  panelRaised: Color(0xFF382400),
  panelMuted: Color(0xFF443000),
  panelBorder: Color(0xFF664410),
  accent: Color(0xFFFFB800),
  accentMuted: Color(0xFF5C3800),
  success: Color(0xFF78C098),
  successMuted: Color(0xFF1C3C28),
  warning: Color(0xFFD4AA50),
  warningMuted: Color(0xFF3E2800),
  info: Color(0xFF78C0D8),
  infoMuted: Color(0xFF163040),
  danger: Color(0xFFE08878),
  dangerMuted: Color(0xFF4A2018),
  chatOutgoing: Color(0xFF4E3400),
  chatIncoming: Color(0xFF2C1C00),
  storyActive: Color(0xFFFFB800),
  storyInactive: Color(0xFF705030),
  storyOverlay: Color(0xD90A0600),
  imagePlaceholder: Color(0xFF443200),
  imageError: Color(0xFF543E00),
  foreground: Color(0xFFFFF8E6),
  foregroundMuted: Color(0xFFD4A858),
  foregroundOnAccent: Color(0xFF1A0E00),
  adminExperiment: Color(0xFFCC9AFF),
  cardRadius: 16,
  buttonRadius: 14,
  inputRadius: 14,
  panelBorderWidth: 0.8,
  logoAsset: 'assets/logo_ember.png',
);

// ---------------------------------------------------------------------------
// Mist — vibrant emerald, fresh vitality, spring-green dark mode
// ---------------------------------------------------------------------------

const _mistLight = SdalThemeTokens(
  canvas: Color(0xFFF0FAF5),
  canvasSubtle: Color(0xFFDFF3E8),
  panel: Color(0xFFFAFEFC),
  panelRaised: Color(0xFFEBF8F1),
  panelMuted: Color(0xFFD6F0E4),
  panelBorder: Color(0xFF9ACDB5),
  accent: Color(0xFF087F5B),
  accentMuted: Color(0xFFBBEDD8),
  success: Color(0xFF206848),
  successMuted: Color(0xFFCCEEDC),
  warning: Color(0xFF7A5A14),
  warningMuted: Color(0xFFEEE0BE),
  info: Color(0xFF245470),
  infoMuted: Color(0xFFCCE4F0),
  danger: Color(0xFF9E3838),
  dangerMuted: Color(0xFFF2D4D4),
  chatOutgoing: Color(0xFF1C5038),
  chatIncoming: Color(0xFFFAFEFC),
  storyActive: Color(0xFF087F5B),
  storyInactive: Color(0xFF8ABFAA),
  storyOverlay: Color(0xB3081A10),
  imagePlaceholder: Color(0xFFBEE8D4),
  imageError: Color(0xFFAEDCC8),
  foreground: Color(0xFF081E14),
  foregroundMuted: Color(0xFF3E6050),
  foregroundOnAccent: Color(0xFFF0FBF6),
  adminExperiment: Color(0xFF5850A8),
  cardRadius: 22,
  buttonRadius: 18,
  inputRadius: 18,
  panelBorderWidth: 0.7,
  logoAsset: 'assets/logo_mist.png',
);

const _mistDark = SdalThemeTokens(
  canvas: Color(0xFF081210),
  canvasSubtle: Color(0xFF0E1C18),
  panel: Color(0xFF142018),
  panelRaised: Color(0xFF1A2C20),
  panelMuted: Color(0xFF203828),
  panelBorder: Color(0xFF2C4C38),
  accent: Color(0xFF51CF66),
  accentMuted: Color(0xFF0E3C20),
  success: Color(0xFF6CD098),
  successMuted: Color(0xFF143828),
  warning: Color(0xFFCCAA50),
  warningMuted: Color(0xFF3C2E10),
  info: Color(0xFF70C0D8),
  infoMuted: Color(0xFF143040),
  danger: Color(0xFFE08888),
  dangerMuted: Color(0xFF481E1E),
  chatOutgoing: Color(0xFF163C28),
  chatIncoming: Color(0xFF142018),
  storyActive: Color(0xFF51CF66),
  storyInactive: Color(0xFF2C4C38),
  storyOverlay: Color(0xD9040E08),
  imagePlaceholder: Color(0xFF1A3028),
  imageError: Color(0xFF223C30),
  foreground: Color(0xFFD8F5E6),
  foregroundMuted: Color(0xFF72A888),
  foregroundOnAccent: Color(0xFF041008),
  adminExperiment: Color(0xFF9898E8),
  cardRadius: 22,
  buttonRadius: 18,
  inputRadius: 18,
  panelBorderWidth: 0.7,
  logoAsset: 'assets/logo_mist.png',
);

// ---------------------------------------------------------------------------
// Nova — spatial glass, intelligence-first, deep space
// ---------------------------------------------------------------------------

const _novaLight = SdalThemeTokens(
  canvas: Color(0xFFF0F4FF),
  canvasSubtle: Color(0xFFE2EBFF),
  panel: Color(0xFFFFFFFF),
  panelRaised: Color(0xFFECF2FF),
  panelMuted: Color(0xFFDAE5FF),
  panelBorder: Color(0xFFB0C4F8),
  accent: Color(0xFF1D4ED8),
  accentMuted: Color(0xFFDBE8FF),
  success: Color(0xFF1A6B48),
  successMuted: Color(0xFFD0EDE0),
  warning: Color(0xFF7A5A14),
  warningMuted: Color(0xFFF0E2C0),
  info: Color(0xFF1D4ED8),
  infoMuted: Color(0xFFDBE8FF),
  danger: Color(0xFF9E3430),
  dangerMuted: Color(0xFFF2D8D6),
  chatOutgoing: Color(0xFF1E40AF),
  chatIncoming: Color(0xFFF8FAFF),
  storyActive: Color(0xFF1D4ED8),
  storyInactive: Color(0xFFB0C4F8),
  storyOverlay: Color(0xB3050614),
  imagePlaceholder: Color(0xFFD0DCFF),
  imageError: Color(0xFFC2D0F8),
  foreground: Color(0xFF0B0F2A),
  foregroundMuted: Color(0xFF4A5480),
  foregroundOnAccent: Color(0xFFF8FAFF),
  adminExperiment: Color(0xFF6060C8),
  cardRadius: 24,
  buttonRadius: 20,
  inputRadius: 24,
  panelBorderWidth: 0.5,
  logoAsset: 'assets/logo_nova.png',
  navStyle: SdalNavStyle.floatingPill,
  navLabelMode: SdalNavLabelMode.never,
  navIndicator: SdalNavIndicator.accentIcon,
  navBarBackground: SdalNavBarBackground.frosted,
  headerStyle: SdalHeaderStyle.minimal,
  headerBackground: SdalHeaderBackground.frosted,
  logoPosition: SdalLogoPosition.leading,
  avatarPosition: SdalAvatarPosition.trailing,
  titleAlignment: SdalTitleAlignment.center,
  cardStyle: SdalCardStyle.glass,
  surfaceDepth: SdalSurfaceDepth.glass,
  borderStyle: SdalBorderStyle.hairline,
  backgroundPattern: SdalBackgroundPattern.radialGlow,
  feedLayout: SdalFeedLayout.singleColumn,
  listItemStyle: SdalListItemStyle.card,
  separatorStyle: SdalSeparatorStyle.spacer,
  scrollPhysics: SdalScrollPhysics.bouncing,
  tapFeedback: SdalTapFeedback.lift,
  transitionStyle: SdalTransitionStyle.blurFade,
  animationSpeed: SdalAnimationSpeed.slow,
  scrollBehavior: SdalScrollBehavior.smooth,
  avatarShape: SdalAvatarShape.roundedSquare,
  avatarBorder: SdalAvatarBorder.glowRing,
  onlineIndicator: SdalOnlineIndicator.pulse,
  memberBadgeStyle: SdalMemberBadgeStyle.none,
  metaPlacement: SdalMetaPlacement.below,
  actionsStyle: SdalActionsStyle.floating,
  statsDisplay: SdalStatsDisplay.chips,
  timestampStyle: SdalTimestampStyle.compact,
  menuStyle: SdalMenuStyle.fullscreen,
  modalBackdrop: SdalModalBackdrop.frosted,
  sheetStyle: SdalSheetStyle.none,
  loadingStyle: SdalLoadingStyle.pulse,
  emptyStateStyle: SdalEmptyStateStyle.minimal,
  imageShape: SdalImageShape.roundedLarge,
  imageOverlay: SdalImageOverlay.gradientBottom,
  placeholderStyle: SdalPlaceholderStyle.crossFade,
  headingWeight: SdalHeadingWeight.light,
  bodyLineHeight: SdalBodyLineHeight.loose,
  letterSpacing: SdalLetterSpacing.tight,
  typographyHierarchy: SdalTypographyHierarchy.display,
  spacingScale: SdalSpacingScale.airy,
  contentInset: SdalContentInset.wide,
  badgeStyle: SdalBadgeStyle.dot,
  unreadIndicator: SdalUnreadIndicator.coloredDot,
  toastPosition: SdalToastPosition.center,
  toastStyle: SdalToastStyle.pill,
  blurSigma: 20.0,
  glassOpacity: 0.10,
  glassSheetOpacity: 0.88,
  navBarHeight: 64.0,
  floatingPillBottomPad: 20.0,
  appBarHeight: 44.0,
  heroHeaderHeight: 0.0,
  contentPaddingH: 20.0,
  cardSpacing: 16.0,
  animationDurationMs: 380,
  feedImageAspect: 1.50,
);

const _novaDark = SdalThemeTokens(
  canvas: Color(0xFF05060F),
  canvasSubtle: Color(0xFF0A0C1E),
  panel: Color(0xFF0E1020),
  panelRaised: Color(0xFF14182E),
  panelMuted: Color(0xFF1A2040),
  panelBorder: Color(0xFF2A3460),
  accent: Color(0xFF60A5FA),
  accentMuted: Color(0xFF1A2A5A),
  success: Color(0xFF68C090),
  successMuted: Color(0xFF143828),
  warning: Color(0xFFCCAA50),
  warningMuted: Color(0xFF3C2E10),
  info: Color(0xFF60A5FA),
  infoMuted: Color(0xFF1A2A5A),
  danger: Color(0xFFE08080),
  dangerMuted: Color(0xFF4A1E1E),
  chatOutgoing: Color(0xFF1E3068),
  chatIncoming: Color(0xFF0E1020),
  storyActive: Color(0xFF60A5FA),
  storyInactive: Color(0xFF2A3460),
  storyOverlay: Color(0xD9030408),
  imagePlaceholder: Color(0xFF18204A),
  imageError: Color(0xFF1E2C58),
  foreground: Color(0xFFEFF4FF),
  foregroundMuted: Color(0xFF7088C8),
  foregroundOnAccent: Color(0xFF05060F),
  adminExperiment: Color(0xFF9898E8),
  cardRadius: 24,
  buttonRadius: 20,
  inputRadius: 24,
  panelBorderWidth: 0.5,
  logoAsset: 'assets/logo_nova.png',
  navStyle: SdalNavStyle.floatingPill,
  navLabelMode: SdalNavLabelMode.never,
  navIndicator: SdalNavIndicator.accentIcon,
  navBarBackground: SdalNavBarBackground.frosted,
  headerStyle: SdalHeaderStyle.minimal,
  headerBackground: SdalHeaderBackground.frosted,
  logoPosition: SdalLogoPosition.leading,
  avatarPosition: SdalAvatarPosition.trailing,
  titleAlignment: SdalTitleAlignment.center,
  cardStyle: SdalCardStyle.glass,
  surfaceDepth: SdalSurfaceDepth.glass,
  borderStyle: SdalBorderStyle.hairline,
  backgroundPattern: SdalBackgroundPattern.radialGlow,
  feedLayout: SdalFeedLayout.singleColumn,
  listItemStyle: SdalListItemStyle.card,
  separatorStyle: SdalSeparatorStyle.spacer,
  scrollPhysics: SdalScrollPhysics.bouncing,
  tapFeedback: SdalTapFeedback.lift,
  transitionStyle: SdalTransitionStyle.blurFade,
  animationSpeed: SdalAnimationSpeed.slow,
  scrollBehavior: SdalScrollBehavior.smooth,
  avatarShape: SdalAvatarShape.roundedSquare,
  avatarBorder: SdalAvatarBorder.glowRing,
  onlineIndicator: SdalOnlineIndicator.pulse,
  memberBadgeStyle: SdalMemberBadgeStyle.none,
  metaPlacement: SdalMetaPlacement.below,
  actionsStyle: SdalActionsStyle.floating,
  statsDisplay: SdalStatsDisplay.chips,
  timestampStyle: SdalTimestampStyle.compact,
  menuStyle: SdalMenuStyle.fullscreen,
  modalBackdrop: SdalModalBackdrop.frosted,
  sheetStyle: SdalSheetStyle.none,
  loadingStyle: SdalLoadingStyle.pulse,
  emptyStateStyle: SdalEmptyStateStyle.minimal,
  imageShape: SdalImageShape.roundedLarge,
  imageOverlay: SdalImageOverlay.gradientBottom,
  placeholderStyle: SdalPlaceholderStyle.crossFade,
  headingWeight: SdalHeadingWeight.light,
  bodyLineHeight: SdalBodyLineHeight.loose,
  letterSpacing: SdalLetterSpacing.tight,
  typographyHierarchy: SdalTypographyHierarchy.display,
  spacingScale: SdalSpacingScale.airy,
  contentInset: SdalContentInset.wide,
  badgeStyle: SdalBadgeStyle.dot,
  unreadIndicator: SdalUnreadIndicator.coloredDot,
  toastPosition: SdalToastPosition.center,
  toastStyle: SdalToastStyle.pill,
  blurSigma: 20.0,
  glassOpacity: 0.08,
  glassSheetOpacity: 0.88,
  navBarHeight: 64.0,
  floatingPillBottomPad: 20.0,
  appBarHeight: 44.0,
  heroHeaderHeight: 0.0,
  contentPaddingH: 20.0,
  cardSpacing: 16.0,
  animationDurationMs: 380,
  feedImageAspect: 1.50,
);

// ---------------------------------------------------------------------------
// Prism — bento grid, modular information architecture
// ---------------------------------------------------------------------------

const _prismLight = SdalThemeTokens(
  canvas: Color(0xFFF7F7F9),
  canvasSubtle: Color(0xFFEEEEF4),
  panel: Color(0xFFFFFFFF),
  panelRaised: Color(0xFFF3F2FA),
  panelMuted: Color(0xFFE8E7F5),
  panelBorder: Color(0xFFD0CEEC),
  accent: Color(0xFF7C3AED),
  accentMuted: Color(0xFFEDE9FE),
  success: Color(0xFF1E6B48),
  successMuted: Color(0xFFD0EDE0),
  warning: Color(0xFF7A5A14),
  warningMuted: Color(0xFFF0E2C0),
  info: Color(0xFF2A5080),
  infoMuted: Color(0xFFCCDCF4),
  danger: Color(0xFF9E3030),
  dangerMuted: Color(0xFFF4D4D4),
  chatOutgoing: Color(0xFF4A1A9A),
  chatIncoming: Color(0xFFFFFFFF),
  storyActive: Color(0xFF7C3AED),
  storyInactive: Color(0xFFBBAAE0),
  storyOverlay: Color(0xB30E0820),
  imagePlaceholder: Color(0xFFE0DAFF),
  imageError: Color(0xFFD4CEF8),
  foreground: Color(0xFF0F0F14),
  foregroundMuted: Color(0xFF6B6B85),
  foregroundOnAccent: Color(0xFFFAF8FF),
  adminExperiment: Color(0xFF8050D0),
  cardRadius: 20,
  buttonRadius: 14,
  inputRadius: 16,
  panelBorderWidth: 1.0,
  logoAsset: 'assets/logo_prism.png',
  navStyle: SdalNavStyle.sideDrawer,
  navLabelMode: SdalNavLabelMode.always,
  navIndicator: SdalNavIndicator.filledPill,
  navBarBackground: SdalNavBarBackground.solid,
  headerStyle: SdalHeaderStyle.heroAvatar,
  headerBackground: SdalHeaderBackground.solid,
  logoPosition: SdalLogoPosition.hidden,
  avatarPosition: SdalAvatarPosition.headerHero,
  titleAlignment: SdalTitleAlignment.start,
  cardStyle: SdalCardStyle.flat,
  surfaceDepth: SdalSurfaceDepth.flat,
  borderStyle: SdalBorderStyle.thin,
  backgroundPattern: SdalBackgroundPattern.solid,
  feedLayout: SdalFeedLayout.twoColumnGrid,
  listItemStyle: SdalListItemStyle.inlineCard,
  separatorStyle: SdalSeparatorStyle.cardGap,
  scrollPhysics: SdalScrollPhysics.bouncing,
  tapFeedback: SdalTapFeedback.scalePress,
  transitionStyle: SdalTransitionStyle.fade,
  animationSpeed: SdalAnimationSpeed.fast,
  scrollBehavior: SdalScrollBehavior.standard,
  avatarShape: SdalAvatarShape.hexagon,
  avatarBorder: SdalAvatarBorder.gradient,
  onlineIndicator: SdalOnlineIndicator.ring,
  memberBadgeStyle: SdalMemberBadgeStyle.subtleLabel,
  metaPlacement: SdalMetaPlacement.trailing,
  actionsStyle: SdalActionsStyle.iconRow,
  statsDisplay: SdalStatsDisplay.metricCards,
  timestampStyle: SdalTimestampStyle.compact,
  menuStyle: SdalMenuStyle.drawer,
  modalBackdrop: SdalModalBackdrop.dim,
  sheetStyle: SdalSheetStyle.lineHandle,
  loadingStyle: SdalLoadingStyle.skeleton,
  emptyStateStyle: SdalEmptyStateStyle.card,
  imageShape: SdalImageShape.roundedLarge,
  imageOverlay: SdalImageOverlay.none,
  placeholderStyle: SdalPlaceholderStyle.shimmer,
  headingWeight: SdalHeadingWeight.bold,
  bodyLineHeight: SdalBodyLineHeight.normal,
  letterSpacing: SdalLetterSpacing.tight,
  typographyHierarchy: SdalTypographyHierarchy.editorial,
  spacingScale: SdalSpacingScale.normal,
  contentInset: SdalContentInset.standard,
  badgeStyle: SdalBadgeStyle.count,
  unreadIndicator: SdalUnreadIndicator.badgeCount,
  toastPosition: SdalToastPosition.bottom,
  toastStyle: SdalToastStyle.snackbar,
  blurSigma: 0.0,
  glassOpacity: 0.0,
  glassSheetOpacity: 0.50,
  navBarHeight: 0.0,
  floatingPillBottomPad: 0.0,
  appBarHeight: 88.0,
  heroHeaderHeight: 160.0,
  contentPaddingH: 16.0,
  cardSpacing: 12.0,
  animationDurationMs: 180,
  feedImageAspect: 1.0,
);

const _prismDark = SdalThemeTokens(
  canvas: Color(0xFF0D0D12),
  canvasSubtle: Color(0xFF141420),
  panel: Color(0xFF1A1A28),
  panelRaised: Color(0xFF222238),
  panelMuted: Color(0xFF2A2A48),
  panelBorder: Color(0xFF3A3A60),
  accent: Color(0xFFA78BFA),
  accentMuted: Color(0xFF2A1C60),
  success: Color(0xFF68C090),
  successMuted: Color(0xFF183828),
  warning: Color(0xFFCCAA50),
  warningMuted: Color(0xFF3C2E10),
  info: Color(0xFF72C0E0),
  infoMuted: Color(0xFF163040),
  danger: Color(0xFFE08888),
  dangerMuted: Color(0xFF4A1E1E),
  chatOutgoing: Color(0xFF38207A),
  chatIncoming: Color(0xFF1A1A28),
  storyActive: Color(0xFFA78BFA),
  storyInactive: Color(0xFF3A3A60),
  storyOverlay: Color(0xD908061A),
  imagePlaceholder: Color(0xFF28284C),
  imageError: Color(0xFF323258),
  foreground: Color(0xFFF2F0FF),
  foregroundMuted: Color(0xFFBBAAE0),
  foregroundOnAccent: Color(0xFF0D0D12),
  adminExperiment: Color(0xFFCC90FF),
  cardRadius: 20,
  buttonRadius: 14,
  inputRadius: 16,
  panelBorderWidth: 1.0,
  logoAsset: 'assets/logo_prism.png',
  navStyle: SdalNavStyle.sideDrawer,
  navLabelMode: SdalNavLabelMode.always,
  navIndicator: SdalNavIndicator.filledPill,
  navBarBackground: SdalNavBarBackground.solid,
  headerStyle: SdalHeaderStyle.heroAvatar,
  headerBackground: SdalHeaderBackground.solid,
  logoPosition: SdalLogoPosition.hidden,
  avatarPosition: SdalAvatarPosition.headerHero,
  titleAlignment: SdalTitleAlignment.start,
  cardStyle: SdalCardStyle.flat,
  surfaceDepth: SdalSurfaceDepth.flat,
  borderStyle: SdalBorderStyle.thin,
  backgroundPattern: SdalBackgroundPattern.solid,
  feedLayout: SdalFeedLayout.twoColumnGrid,
  listItemStyle: SdalListItemStyle.inlineCard,
  separatorStyle: SdalSeparatorStyle.cardGap,
  scrollPhysics: SdalScrollPhysics.bouncing,
  tapFeedback: SdalTapFeedback.scalePress,
  transitionStyle: SdalTransitionStyle.fade,
  animationSpeed: SdalAnimationSpeed.fast,
  scrollBehavior: SdalScrollBehavior.standard,
  avatarShape: SdalAvatarShape.hexagon,
  avatarBorder: SdalAvatarBorder.gradient,
  onlineIndicator: SdalOnlineIndicator.ring,
  memberBadgeStyle: SdalMemberBadgeStyle.subtleLabel,
  metaPlacement: SdalMetaPlacement.trailing,
  actionsStyle: SdalActionsStyle.iconRow,
  statsDisplay: SdalStatsDisplay.metricCards,
  timestampStyle: SdalTimestampStyle.compact,
  menuStyle: SdalMenuStyle.drawer,
  modalBackdrop: SdalModalBackdrop.dim,
  sheetStyle: SdalSheetStyle.lineHandle,
  loadingStyle: SdalLoadingStyle.skeleton,
  emptyStateStyle: SdalEmptyStateStyle.card,
  imageShape: SdalImageShape.roundedLarge,
  imageOverlay: SdalImageOverlay.none,
  placeholderStyle: SdalPlaceholderStyle.shimmer,
  headingWeight: SdalHeadingWeight.bold,
  bodyLineHeight: SdalBodyLineHeight.normal,
  letterSpacing: SdalLetterSpacing.tight,
  typographyHierarchy: SdalTypographyHierarchy.editorial,
  spacingScale: SdalSpacingScale.normal,
  contentInset: SdalContentInset.standard,
  badgeStyle: SdalBadgeStyle.count,
  unreadIndicator: SdalUnreadIndicator.badgeCount,
  toastPosition: SdalToastPosition.bottom,
  toastStyle: SdalToastStyle.snackbar,
  blurSigma: 0.0,
  glassOpacity: 0.0,
  glassSheetOpacity: 0.50,
  navBarHeight: 0.0,
  floatingPillBottomPad: 0.0,
  appBarHeight: 88.0,
  heroHeaderHeight: 160.0,
  contentPaddingH: 16.0,
  cardSpacing: 12.0,
  animationDurationMs: 180,
  feedImageAspect: 1.0,
);

// ---------------------------------------------------------------------------
// Dusk — dark cinematic, dramatic editorial
// ---------------------------------------------------------------------------

const _duskLight = SdalThemeTokens(
  canvas: Color(0xFFFAF7F2),
  canvasSubtle: Color(0xFFF0EAE0),
  panel: Color(0xFFFFFFFF),
  panelRaised: Color(0xFFF8F3EC),
  panelMuted: Color(0xFFEDE4D8),
  panelBorder: Color(0xFFD4B880),
  accent: Color(0xFFD97706),
  accentMuted: Color(0xFFFEF3C7),
  success: Color(0xFF1E6B48),
  successMuted: Color(0xFFD0EDE0),
  warning: Color(0xFF92400E),
  warningMuted: Color(0xFFFEF3C7),
  info: Color(0xFF1E40AF),
  infoMuted: Color(0xFFDBEAFE),
  danger: Color(0xFF991B1B),
  dangerMuted: Color(0xFFFEE2E2),
  chatOutgoing: Color(0xFF78350F),
  chatIncoming: Color(0xFFFFFFFF),
  storyActive: Color(0xFFD97706),
  storyInactive: Color(0xFFD4B880),
  storyOverlay: Color(0xB3180C00),
  imagePlaceholder: Color(0xFFECDCAC),
  imageError: Color(0xFFE8D0A0),
  foreground: Color(0xFF1C1208),
  foregroundMuted: Color(0xFF6C4C1A),
  foregroundOnAccent: Color(0xFFFFFBF0),
  adminExperiment: Color(0xFF7050A0),
  cardRadius: 8,
  buttonRadius: 6,
  inputRadius: 8,
  panelBorderWidth: 0.0,
  logoAsset: 'assets/logo_dusk.png',
  navStyle: SdalNavStyle.transparentBar,
  navLabelMode: SdalNavLabelMode.never,
  navIndicator: SdalNavIndicator.underline,
  navBarBackground: SdalNavBarBackground.transparentBlur,
  headerStyle: SdalHeaderStyle.transparent,
  headerBackground: SdalHeaderBackground.gradientScrim,
  logoPosition: SdalLogoPosition.leading,
  avatarPosition: SdalAvatarPosition.leading,
  titleAlignment: SdalTitleAlignment.center,
  cardStyle: SdalCardStyle.fullBleed,
  surfaceDepth: SdalSurfaceDepth.flat,
  borderStyle: SdalBorderStyle.none,
  backgroundPattern: SdalBackgroundPattern.solid,
  feedLayout: SdalFeedLayout.cinematic,
  listItemStyle: SdalListItemStyle.fullBleedCard,
  separatorStyle: SdalSeparatorStyle.none,
  scrollPhysics: SdalScrollPhysics.snapping,
  tapFeedback: SdalTapFeedback.highlight,
  transitionStyle: SdalTransitionStyle.fade,
  animationSpeed: SdalAnimationSpeed.dramatic,
  scrollBehavior: SdalScrollBehavior.smooth,
  avatarShape: SdalAvatarShape.circle,
  avatarBorder: SdalAvatarBorder.glowRing,
  onlineIndicator: SdalOnlineIndicator.ring,
  memberBadgeStyle: SdalMemberBadgeStyle.none,
  metaPlacement: SdalMetaPlacement.overlay,
  actionsStyle: SdalActionsStyle.floating,
  statsDisplay: SdalStatsDisplay.hidden,
  timestampStyle: SdalTimestampStyle.hidden,
  menuStyle: SdalMenuStyle.centerModal,
  modalBackdrop: SdalModalBackdrop.tinted,
  sheetStyle: SdalSheetStyle.pillHandle,
  loadingStyle: SdalLoadingStyle.shimmer,
  emptyStateStyle: SdalEmptyStateStyle.minimal,
  imageShape: SdalImageShape.rectangle,
  imageOverlay: SdalImageOverlay.gradientBottom,
  placeholderStyle: SdalPlaceholderStyle.solidColor,
  headingWeight: SdalHeadingWeight.black,
  bodyLineHeight: SdalBodyLineHeight.normal,
  letterSpacing: SdalLetterSpacing.ultraWide,
  typographyHierarchy: SdalTypographyHierarchy.display,
  spacingScale: SdalSpacingScale.relaxed,
  contentInset: SdalContentInset.none,
  badgeStyle: SdalBadgeStyle.dot,
  unreadIndicator: SdalUnreadIndicator.coloredDot,
  toastPosition: SdalToastPosition.bottom,
  toastStyle: SdalToastStyle.card,
  blurSigma: 28.0,
  glassOpacity: 0.0,
  glassSheetOpacity: 0.82,
  navBarHeight: 72.0,
  floatingPillBottomPad: 0.0,
  appBarHeight: 56.0,
  heroHeaderHeight: 0.0,
  contentPaddingH: 0.0,
  cardSpacing: 4.0,
  animationDurationMs: 500,
  feedImageAspect: 0.65,
);

const _duskDark = SdalThemeTokens(
  canvas: Color(0xFF0A0806),
  canvasSubtle: Color(0xFF120E08),
  panel: Color(0xFF161210),
  panelRaised: Color(0xFF201A14),
  panelMuted: Color(0xFF2A221A),
  panelBorder: Color(0xFF3C2E1A),
  accent: Color(0xFFFBBF24),
  accentMuted: Color(0xFF442800),
  success: Color(0xFF78C098),
  successMuted: Color(0xFF1C3C28),
  warning: Color(0xFFF59E0B),
  warningMuted: Color(0xFF3A2000),
  info: Color(0xFF60A5FA),
  infoMuted: Color(0xFF1A2A5A),
  danger: Color(0xFFF87171),
  dangerMuted: Color(0xFF4A1010),
  chatOutgoing: Color(0xFF4E3400),
  chatIncoming: Color(0xFF161210),
  storyActive: Color(0xFFFBBF24),
  storyInactive: Color(0xFF705030),
  storyOverlay: Color(0xD9060400),
  imagePlaceholder: Color(0xFF3A2A14),
  imageError: Color(0xFF4A3418),
  foreground: Color(0xFFFFF8F0),
  foregroundMuted: Color(0xFFD4A858),
  foregroundOnAccent: Color(0xFF0A0600),
  adminExperiment: Color(0xFFCC9AFF),
  cardRadius: 8,
  buttonRadius: 6,
  inputRadius: 8,
  panelBorderWidth: 0.0,
  logoAsset: 'assets/logo_dusk.png',
  navStyle: SdalNavStyle.transparentBar,
  navLabelMode: SdalNavLabelMode.never,
  navIndicator: SdalNavIndicator.underline,
  navBarBackground: SdalNavBarBackground.transparentBlur,
  headerStyle: SdalHeaderStyle.transparent,
  headerBackground: SdalHeaderBackground.gradientScrim,
  logoPosition: SdalLogoPosition.leading,
  avatarPosition: SdalAvatarPosition.leading,
  titleAlignment: SdalTitleAlignment.center,
  cardStyle: SdalCardStyle.fullBleed,
  surfaceDepth: SdalSurfaceDepth.flat,
  borderStyle: SdalBorderStyle.none,
  backgroundPattern: SdalBackgroundPattern.solid,
  feedLayout: SdalFeedLayout.cinematic,
  listItemStyle: SdalListItemStyle.fullBleedCard,
  separatorStyle: SdalSeparatorStyle.none,
  scrollPhysics: SdalScrollPhysics.snapping,
  tapFeedback: SdalTapFeedback.highlight,
  transitionStyle: SdalTransitionStyle.fade,
  animationSpeed: SdalAnimationSpeed.dramatic,
  scrollBehavior: SdalScrollBehavior.smooth,
  avatarShape: SdalAvatarShape.circle,
  avatarBorder: SdalAvatarBorder.glowRing,
  onlineIndicator: SdalOnlineIndicator.ring,
  memberBadgeStyle: SdalMemberBadgeStyle.none,
  metaPlacement: SdalMetaPlacement.overlay,
  actionsStyle: SdalActionsStyle.floating,
  statsDisplay: SdalStatsDisplay.hidden,
  timestampStyle: SdalTimestampStyle.hidden,
  menuStyle: SdalMenuStyle.centerModal,
  modalBackdrop: SdalModalBackdrop.tinted,
  sheetStyle: SdalSheetStyle.pillHandle,
  loadingStyle: SdalLoadingStyle.shimmer,
  emptyStateStyle: SdalEmptyStateStyle.minimal,
  imageShape: SdalImageShape.rectangle,
  imageOverlay: SdalImageOverlay.gradientBottom,
  placeholderStyle: SdalPlaceholderStyle.solidColor,
  headingWeight: SdalHeadingWeight.black,
  bodyLineHeight: SdalBodyLineHeight.normal,
  letterSpacing: SdalLetterSpacing.ultraWide,
  typographyHierarchy: SdalTypographyHierarchy.display,
  spacingScale: SdalSpacingScale.relaxed,
  contentInset: SdalContentInset.none,
  badgeStyle: SdalBadgeStyle.dot,
  unreadIndicator: SdalUnreadIndicator.coloredDot,
  toastPosition: SdalToastPosition.bottom,
  toastStyle: SdalToastStyle.card,
  blurSigma: 28.0,
  glassOpacity: 0.0,
  glassSheetOpacity: 0.82,
  navBarHeight: 72.0,
  floatingPillBottomPad: 0.0,
  appBarHeight: 56.0,
  heroHeaderHeight: 0.0,
  contentPaddingH: 0.0,
  cardSpacing: 4.0,
  animationDurationMs: 500,
  feedImageAspect: 0.65,
);

// ---------------------------------------------------------------------------
// Flux — Material You 3, dynamic & adaptive teal
// ---------------------------------------------------------------------------

const _fluxLight = SdalThemeTokens(
  canvas: Color(0xFFF8FFFE),
  canvasSubtle: Color(0xFFEEFBF8),
  panel: Color(0xFFFFFFFF),
  panelRaised: Color(0xFFEAF9F5),
  panelMuted: Color(0xFFD5F4EC),
  panelBorder: Color(0xFF99DACA),
  accent: Color(0xFF0D9488),
  accentMuted: Color(0xFFCCFBF1),
  success: Color(0xFF1E6B48),
  successMuted: Color(0xFFD0EDE0),
  warning: Color(0xFF7A5A14),
  warningMuted: Color(0xFFF0E2C0),
  info: Color(0xFF0D6E94),
  infoMuted: Color(0xFFCCE8F4),
  danger: Color(0xFF9E3430),
  dangerMuted: Color(0xFFF2D8D6),
  chatOutgoing: Color(0xFF0C5E54),
  chatIncoming: Color(0xFFFFFFFF),
  storyActive: Color(0xFF0D9488),
  storyInactive: Color(0xFF99DACA),
  storyOverlay: Color(0xB3040E0C),
  imagePlaceholder: Color(0xFFBBEDD8),
  imageError: Color(0xFFAAE0CC),
  foreground: Color(0xFF0A1512),
  foregroundMuted: Color(0xFF3D6B60),
  foregroundOnAccent: Color(0xFFF0FFFD),
  adminExperiment: Color(0xFF5850A8),
  cardRadius: 12,
  buttonRadius: 20,
  inputRadius: 12,
  panelBorderWidth: 0.0,
  logoAsset: 'assets/logo_flux.png',
  navStyle: SdalNavStyle.materialFab,
  navLabelMode: SdalNavLabelMode.selectedOnly,
  navIndicator: SdalNavIndicator.filledPill,
  navBarBackground: SdalNavBarBackground.solid,
  headerStyle: SdalHeaderStyle.collapsible,
  headerBackground: SdalHeaderBackground.solid,
  logoPosition: SdalLogoPosition.leading,
  avatarPosition: SdalAvatarPosition.trailing,
  titleAlignment: SdalTitleAlignment.start,
  cardStyle: SdalCardStyle.tonal,
  surfaceDepth: SdalSurfaceDepth.flat,
  borderStyle: SdalBorderStyle.none,
  backgroundPattern: SdalBackgroundPattern.solid,
  feedLayout: SdalFeedLayout.compact,
  listItemStyle: SdalListItemStyle.compact,
  separatorStyle: SdalSeparatorStyle.hairline,
  scrollPhysics: SdalScrollPhysics.clamped,
  tapFeedback: SdalTapFeedback.ripple,
  transitionStyle: SdalTransitionStyle.scale,
  animationSpeed: SdalAnimationSpeed.fast,
  scrollBehavior: SdalScrollBehavior.standard,
  avatarShape: SdalAvatarShape.circle,
  avatarBorder: SdalAvatarBorder.roleColor,
  onlineIndicator: SdalOnlineIndicator.dot,
  memberBadgeStyle: SdalMemberBadgeStyle.colorRing,
  metaPlacement: SdalMetaPlacement.inline,
  actionsStyle: SdalActionsStyle.pillButtons,
  statsDisplay: SdalStatsDisplay.inlineText,
  timestampStyle: SdalTimestampStyle.relative,
  menuStyle: SdalMenuStyle.expandedTab,
  modalBackdrop: SdalModalBackdrop.blur,
  sheetStyle: SdalSheetStyle.lineHandle,
  loadingStyle: SdalLoadingStyle.skeleton,
  emptyStateStyle: SdalEmptyStateStyle.inline,
  imageShape: SdalImageShape.roundedSmall,
  imageOverlay: SdalImageOverlay.none,
  placeholderStyle: SdalPlaceholderStyle.shimmer,
  headingWeight: SdalHeadingWeight.medium,
  bodyLineHeight: SdalBodyLineHeight.tight,
  letterSpacing: SdalLetterSpacing.normal,
  typographyHierarchy: SdalTypographyHierarchy.functional,
  spacingScale: SdalSpacingScale.compact,
  contentInset: SdalContentInset.standard,
  badgeStyle: SdalBadgeStyle.count,
  unreadIndicator: SdalUnreadIndicator.accentBar,
  toastPosition: SdalToastPosition.top,
  toastStyle: SdalToastStyle.pill,
  blurSigma: 8.0,
  glassOpacity: 0.0,
  glassSheetOpacity: 0.60,
  navBarHeight: 80.0,
  floatingPillBottomPad: 16.0,
  appBarHeight: 64.0,
  heroHeaderHeight: 80.0,
  contentPaddingH: 16.0,
  cardSpacing: 8.0,
  animationDurationMs: 160,
  feedImageAspect: 1.78,
);

const _fluxDark = SdalThemeTokens(
  canvas: Color(0xFF081210),
  canvasSubtle: Color(0xFF0E1C1A),
  panel: Color(0xFF142820),
  panelRaised: Color(0xFF1A342A),
  panelMuted: Color(0xFF204030),
  panelBorder: Color(0xFF2C5040),
  accent: Color(0xFF2DD4BF),
  accentMuted: Color(0xFF0A3C34),
  success: Color(0xFF6CD098),
  successMuted: Color(0xFF143828),
  warning: Color(0xFFCCAA50),
  warningMuted: Color(0xFF3C2E10),
  info: Color(0xFF60C0D8),
  infoMuted: Color(0xFF103040),
  danger: Color(0xFFE08888),
  dangerMuted: Color(0xFF481E1E),
  chatOutgoing: Color(0xFF143C30),
  chatIncoming: Color(0xFF142820),
  storyActive: Color(0xFF2DD4BF),
  storyInactive: Color(0xFF2C5040),
  storyOverlay: Color(0xD9020A08),
  imagePlaceholder: Color(0xFF183028),
  imageError: Color(0xFF1E3C30),
  foreground: Color(0xFFD4F5EE),
  foregroundMuted: Color(0xFF68A898),
  foregroundOnAccent: Color(0xFF040E0C),
  adminExperiment: Color(0xFF9898E8),
  cardRadius: 12,
  buttonRadius: 20,
  inputRadius: 12,
  panelBorderWidth: 0.0,
  logoAsset: 'assets/logo_flux.png',
  navStyle: SdalNavStyle.materialFab,
  navLabelMode: SdalNavLabelMode.selectedOnly,
  navIndicator: SdalNavIndicator.filledPill,
  navBarBackground: SdalNavBarBackground.solid,
  headerStyle: SdalHeaderStyle.collapsible,
  headerBackground: SdalHeaderBackground.solid,
  logoPosition: SdalLogoPosition.leading,
  avatarPosition: SdalAvatarPosition.trailing,
  titleAlignment: SdalTitleAlignment.start,
  cardStyle: SdalCardStyle.tonal,
  surfaceDepth: SdalSurfaceDepth.flat,
  borderStyle: SdalBorderStyle.none,
  backgroundPattern: SdalBackgroundPattern.solid,
  feedLayout: SdalFeedLayout.compact,
  listItemStyle: SdalListItemStyle.compact,
  separatorStyle: SdalSeparatorStyle.hairline,
  scrollPhysics: SdalScrollPhysics.clamped,
  tapFeedback: SdalTapFeedback.ripple,
  transitionStyle: SdalTransitionStyle.scale,
  animationSpeed: SdalAnimationSpeed.fast,
  scrollBehavior: SdalScrollBehavior.standard,
  avatarShape: SdalAvatarShape.circle,
  avatarBorder: SdalAvatarBorder.roleColor,
  onlineIndicator: SdalOnlineIndicator.dot,
  memberBadgeStyle: SdalMemberBadgeStyle.colorRing,
  metaPlacement: SdalMetaPlacement.inline,
  actionsStyle: SdalActionsStyle.pillButtons,
  statsDisplay: SdalStatsDisplay.inlineText,
  timestampStyle: SdalTimestampStyle.relative,
  menuStyle: SdalMenuStyle.expandedTab,
  modalBackdrop: SdalModalBackdrop.blur,
  sheetStyle: SdalSheetStyle.lineHandle,
  loadingStyle: SdalLoadingStyle.skeleton,
  emptyStateStyle: SdalEmptyStateStyle.inline,
  imageShape: SdalImageShape.roundedSmall,
  imageOverlay: SdalImageOverlay.none,
  placeholderStyle: SdalPlaceholderStyle.shimmer,
  headingWeight: SdalHeadingWeight.medium,
  bodyLineHeight: SdalBodyLineHeight.tight,
  letterSpacing: SdalLetterSpacing.normal,
  typographyHierarchy: SdalTypographyHierarchy.functional,
  spacingScale: SdalSpacingScale.compact,
  contentInset: SdalContentInset.standard,
  badgeStyle: SdalBadgeStyle.count,
  unreadIndicator: SdalUnreadIndicator.accentBar,
  toastPosition: SdalToastPosition.top,
  toastStyle: SdalToastStyle.pill,
  blurSigma: 8.0,
  glassOpacity: 0.0,
  glassSheetOpacity: 0.60,
  navBarHeight: 80.0,
  floatingPillBottomPad: 16.0,
  appBarHeight: 64.0,
  heroHeaderHeight: 80.0,
  contentPaddingH: 16.0,
  cardSpacing: 8.0,
  animationDurationMs: 160,
  feedImageAspect: 1.78,
);
