import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'sdal_theme_experience.dart';
import 'sdal_theme_tokens.dart';
import 'sdal_ux_profile.dart';

enum SdalAppTheme {
  kor,
  atlas,
  vibe,
  zinc,
  ember,
  mist,
  nova,
  prism,
  dusk,
  flux;

  static SdalAppTheme fromString(String? value) {
    return switch (value?.toLowerCase().trim()) {
      'atlas' => atlas,
      'vibe' => vibe,
      'zinc' => zinc,
      'ember' => ember,
      'mist' => mist,
      'nova' => nova,
      'prism' => prism,
      'dusk' => dusk,
      'flux' => flux,
      _ => kor,
    };
  }

  String get id => name;

  String get displayName => switch (this) {
    kor => 'Kor',
    atlas => 'Atlas',
    vibe => 'Vibe',
    zinc => 'Zinc',
    ember => 'Ember',
    mist => 'Mist',
    nova => 'Nova',
    prism => 'Prism',
    dusk => 'Dusk',
    flux => 'Flux',
  };

  String get tagline => switch (this) {
    kor => 'Ocak ağı & sıcak akış',
    atlas => 'Harita & yapı',
    vibe => 'Sosyal nabız',
    zinc => 'Ink & hızlı tarama',
    ember => 'Arşiv & etkinlik salonu',
    mist => 'Bahçe & sakin okuma',
    nova => 'Uzaysal cam & zerafet',
    prism => 'Modüler bento & netlik',
    dusk => 'Sinematik karanlık & dramatik',
    flux => 'Dinamik & uyarlanabilir',
  };

  /// Dark-mode accent for watchOS .tint().
  Color get watchAccent => switch (this) {
    kor => const Color(0xFFD88B68),
    atlas => const Color(0xFF79A7D8),
    vibe => const Color(0xFFA58BCB),
    zinc => const Color(0xFF8AB8C4),
    ember => const Color(0xFFD7A24E),
    mist => const Color(0xFF86B892),
    nova => const Color(0xFF86AEE0),
    prism => const Color(0xFF9B8FD8),
    dusk => const Color(0xFFD4A456),
    flux => const Color(0xFF78BDB1),
  };

  /// Three representative swatch colors for the theme picker.
  List<Color> get swatches => switch (this) {
    kor => const [Color(0xFFD88B68), Color(0xFF5F78A5), Color(0xFF130C0A)],
    atlas => const [Color(0xFF79A7D8), Color(0xFFA8B86A), Color(0xFF0A1428)],
    vibe => const [Color(0xFFA58BCB), Color(0xFF7DB5C4), Color(0xFF110820)],
    zinc => const [Color(0xFF8AB8C4), Color(0xFFE2E3E6), Color(0xFF0A0A0B)],
    ember => const [Color(0xFFD7A24E), Color(0xFF98614D), Color(0xFF1A1000)],
    mist => const [Color(0xFF86B892), Color(0xFFD3907E), Color(0xFF081210)],
    nova => const [Color(0xFF86AEE0), Color(0xFF6179C8), Color(0xFF05060F)],
    prism => const [Color(0xFF9B8FD8), Color(0xFF7068B8), Color(0xFF0F0F14)],
    dusk => const [Color(0xFFD4A456), Color(0xFFC77A6C), Color(0xFF0A0806)],
    flux => const [Color(0xFF78BDB1), Color(0xFF5C9F96), Color(0xFF0A1512)],
  };

  String get logoAsset => 'assets/logo_$name.png';

  SdalThemeTokens get lightTokens => switch (this) {
    kor => SdalThemeTokens.light,
    atlas => _atlasLight,
    vibe => _vibeLight,
    zinc => _zincLight,
    ember => _emberLight,
    mist => _mistLight,
    nova => _novaLight,
    prism => _prismLight,
    dusk => _duskLight,
    flux => _fluxLight,
  };

  SdalThemeTokens get darkTokens => switch (this) {
    kor => SdalThemeTokens.dark,
    atlas => _atlasDark,
    vibe => _vibeDark,
    zinc => _zincDark,
    ember => _emberDark,
    mist => _mistDark,
    nova => _novaDark,
    prism => _prismDark,
    dusk => _duskDark,
    flux => _fluxDark,
  };

  SdalThemeTokens tokensFor(Brightness brightness) =>
      brightness == Brightness.dark ? darkTokens : lightTokens;

  SdalThemeExperience experienceFor(Brightness brightness) =>
      _experienceForTheme(this, tokensFor(brightness), brightness);

  // ---------------------------------------------------------------------------
  // Font integration
  // ---------------------------------------------------------------------------

  /// The ThemeData fontFamily string.
  /// Kor uses the local Manrope asset; others resolve via Google Fonts.
  String get materialFontFamily => switch (this) {
    kor => 'Manrope',
    atlas => GoogleFonts.ibmPlexSans().fontFamily!,
    vibe => GoogleFonts.nunito().fontFamily!,
    zinc => GoogleFonts.dmSans().fontFamily!,
    ember => GoogleFonts.outfit().fontFamily!,
    mist => GoogleFonts.jost().fontFamily!,
    nova => GoogleFonts.spaceGrotesk().fontFamily!,
    prism => GoogleFonts.archivo().fontFamily!,
    dusk => GoogleFonts.spaceGrotesk().fontFamily!,
    flux => GoogleFonts.plusJakartaSans().fontFamily!,
  };

  /// Apply this theme's typeface to [base]. For Kor the base is returned
  /// unchanged because Manrope is already wired via [materialFontFamily].
  TextTheme applyFont(TextTheme base) => switch (this) {
    kor => base,
    atlas => GoogleFonts.ibmPlexSansTextTheme(base),
    vibe => GoogleFonts.nunitoTextTheme(base),
    zinc => GoogleFonts.dmSansTextTheme(base),
    ember => GoogleFonts.outfitTextTheme(base),
    mist => GoogleFonts.jostTextTheme(base),
    nova => GoogleFonts.spaceGroteskTextTheme(base),
    prism => GoogleFonts.archivoTextTheme(base),
    dusk => GoogleFonts.spaceGroteskTextTheme(base),
    flux => GoogleFonts.plusJakartaSansTextTheme(base),
  };
}

SdalThemeExperience _experienceForTheme(
  SdalAppTheme theme,
  SdalThemeTokens tokens,
  Brightness brightness,
) {
  final isDark = brightness == Brightness.dark;
  SdalLogoProfile logo({
    required Color frame,
    required Color background,
    required Color border,
    required Color shadow,
    double padding = 4,
    double? radius,
  }) {
    return SdalLogoProfile(
      asset: tokens.logoAsset,
      frame: frame,
      background: background,
      border: border,
      shadow: shadow,
      padding: padding,
      radius: radius ?? tokens.cardRadius.clamp(10.0, 24.0),
    );
  }

  return switch (theme) {
    SdalAppTheme.kor => SdalThemeExperience(
      identity: const SdalThemeIdentity(
        id: 'kor',
        scene:
            'A member checks SDAL between campus, commute, and a cafe in normal daylight.',
        promise: 'Warm community flow with strong default clarity.',
        colorStrategy: 'Committed warm neutrals with indigo and green anchors',
        mode: SdalMicroAppMode.hearth,
      ),
      logo: logo(
        frame: isDark ? const Color(0xFF221713) : const Color(0xFFFFF4EC),
        background: isDark ? const Color(0xFF2D1E18) : const Color(0xFFFFE3D3),
        border: tokens.panelBorder,
        shadow: tokens.accent.withValues(alpha: isDark ? 0.28 : 0.18),
        padding: 5,
        radius: 16,
      ),
      shell: const SdalShellProfile(
        primaryActionPlacement: SdalPrimaryActionPlacement.pageFab,
        overlayHitTestMode: SdalOverlayHitTestMode.opaque,
        minimumTapTarget: 46,
      ),
      composition: const SdalCompositionProfile(
        feedLeadTreatment: SdalFeedLeadTreatment.composerCard,
        listRhythm: 1.05,
        controlDensity: 0.95,
        contentBreathingRoom: 1.08,
      ),
      components: const SdalComponentProfile(
        surfaceMaterial: SdalSurfaceMaterial.paper,
        emptyStateTone: SdalEmptyStateTone.guided,
      ),
      motion: const SdalMotionProfile(
        pressScale: 0.98,
        routeDurationMs: 230,
        reducedMotionDurationMs: 90,
        hapticIntensity: 0.25,
      ),
      media: SdalMediaProfile(
        feedImageAspect: tokens.feedImageAspect,
        avatarFrameWidth: 1.4,
        storyRingWidth: 2.4,
      ),
    ),
    SdalAppTheme.atlas => SdalThemeExperience(
      identity: const SdalThemeIdentity(
        id: 'atlas',
        scene:
            'A member maps people, opportunities, and events while scanning structured lists.',
        promise: 'A precise workspace for orientation and discovery.',
        colorStrategy: 'Restrained cobalt system with chartreuse signal',
        mode: SdalMicroAppMode.atlas,
      ),
      logo: logo(
        frame: isDark ? const Color(0xFF0A172D) : const Color(0xFFEAF4FF),
        background: isDark ? const Color(0xFF13264A) : const Color(0xFFD8ECFF),
        border: tokens.panelBorder,
        shadow: tokens.info.withValues(alpha: isDark ? 0.30 : 0.16),
        radius: 12,
      ),
      shell: const SdalShellProfile(
        primaryActionPlacement: SdalPrimaryActionPlacement.pageFab,
        overlayHitTestMode: SdalOverlayHitTestMode.opaque,
        minimumTapTarget: 44,
      ),
      composition: const SdalCompositionProfile(
        feedLeadTreatment: SdalFeedLeadTreatment.structuredControls,
        listRhythm: 0.92,
        controlDensity: 0.86,
        contentBreathingRoom: 0.94,
      ),
      components: const SdalComponentProfile(
        surfaceMaterial: SdalSurfaceMaterial.precision,
        emptyStateTone: SdalEmptyStateTone.structured,
      ),
      motion: const SdalMotionProfile(
        pressScale: 0.985,
        routeDurationMs: 170,
        reducedMotionDurationMs: 70,
        hapticIntensity: 0.18,
      ),
      media: SdalMediaProfile(
        feedImageAspect: tokens.feedImageAspect,
        avatarFrameWidth: 1.0,
      ),
    ),
    SdalAppTheme.vibe => SdalThemeExperience(
      identity: const SdalThemeIdentity(
        id: 'vibe',
        scene:
            'A social-first member jumps between stories, messages, and feed updates on the move.',
        promise: 'Visible social energy without hiding common actions.',
        colorStrategy: 'Full palette rose, violet, cyan, and grape',
        mode: SdalMicroAppMode.pulse,
      ),
      logo: logo(
        frame: isDark ? const Color(0xFF211138) : const Color(0xFFF7E9FF),
        background: isDark ? const Color(0xFF321A54) : const Color(0xFFEFD6FF),
        border: tokens.panelBorder,
        shadow: tokens.accent.withValues(alpha: isDark ? 0.34 : 0.20),
        radius: 20,
      ),
      shell: const SdalShellProfile(
        primaryActionPlacement: SdalPrimaryActionPlacement.pageFab,
        overlayHitTestMode: SdalOverlayHitTestMode.opaque,
        prominentActionOnTabs: true,
        minimumTapTarget: 48,
      ),
      composition: const SdalCompositionProfile(
        feedLeadTreatment: SdalFeedLeadTreatment.socialPulse,
        listRhythm: 1.1,
        controlDensity: 1.0,
        contentBreathingRoom: 1.0,
      ),
      components: const SdalComponentProfile(
        surfaceMaterial: SdalSurfaceMaterial.social,
        emptyStateTone: SdalEmptyStateTone.social,
      ),
      motion: const SdalMotionProfile(
        pressScale: 0.965,
        routeDurationMs: 210,
        reducedMotionDurationMs: 80,
        hapticIntensity: 0.36,
      ),
      media: SdalMediaProfile(
        feedImageAspect: tokens.feedImageAspect,
        avatarFrameWidth: 2.0,
        storyRingWidth: 3.0,
      ),
    ),
    SdalAppTheme.zinc => SdalThemeExperience(
      identity: const SdalThemeIdentity(
        id: 'zinc',
        scene:
            'A power user reads SDAL at night and wants speed, contrast, and no ceremony.',
        promise: 'Fast command-like scanning with editorial contrast.',
        colorStrategy: 'Restrained ink neutrals with cyan signal',
        mode: SdalMicroAppMode.ink,
      ),
      logo: logo(
        frame: isDark ? const Color(0xFF101114) : const Color(0xFFE9ECEF),
        background: isDark ? const Color(0xFF1A1D21) : const Color(0xFFF7F8F9),
        border: tokens.panelBorder,
        shadow: tokens.accent.withValues(alpha: isDark ? 0.22 : 0.10),
        padding: 3,
        radius: 8,
      ),
      shell: const SdalShellProfile(
        primaryActionPlacement: SdalPrimaryActionPlacement.pageFab,
        overlayHitTestMode: SdalOverlayHitTestMode.opaque,
        minimumTapTarget: 44,
      ),
      composition: const SdalCompositionProfile(
        feedLeadTreatment: SdalFeedLeadTreatment.compactScan,
        listRhythm: 0.78,
        controlDensity: 0.78,
        contentBreathingRoom: 0.82,
      ),
      components: const SdalComponentProfile(
        surfaceMaterial: SdalSurfaceMaterial.ink,
        emptyStateTone: SdalEmptyStateTone.compact,
      ),
      motion: const SdalMotionProfile(
        pressScale: 0.99,
        routeDurationMs: 130,
        reducedMotionDurationMs: 50,
      ),
      media: SdalMediaProfile(
        feedImageAspect: tokens.feedImageAspect,
        avatarFrameWidth: 0.8,
        storyRingWidth: 1.4,
      ),
    ),
    SdalAppTheme.ember => SdalThemeExperience(
      identity: const SdalThemeIdentity(
        id: 'ember',
        scene:
            'A member browses events, albums, and announcements like a warm community archive.',
        promise: 'Premium archive surfaces for memory and participation.',
        colorStrategy: 'Committed amber clay with oxblood and teal support',
        mode: SdalMicroAppMode.archive,
      ),
      logo: logo(
        frame: isDark ? const Color(0xFF241503) : const Color(0xFFFFF4D7),
        background: isDark ? const Color(0xFF382406) : const Color(0xFFFFE4A8),
        border: tokens.panelBorder,
        shadow: tokens.warning.withValues(alpha: isDark ? 0.35 : 0.18),
        radius: 14,
      ),
      shell: const SdalShellProfile(
        primaryActionPlacement: SdalPrimaryActionPlacement.pageFab,
        overlayHitTestMode: SdalOverlayHitTestMode.opaque,
        minimumTapTarget: 46,
      ),
      composition: const SdalCompositionProfile(
        feedLeadTreatment: SdalFeedLeadTreatment.archiveFeature,
        listRhythm: 1.0,
        controlDensity: 0.96,
        contentBreathingRoom: 1.02,
      ),
      components: const SdalComponentProfile(
        surfaceMaterial: SdalSurfaceMaterial.archive,
        emptyStateTone: SdalEmptyStateTone.archive,
      ),
      motion: const SdalMotionProfile(
        pressScale: 0.975,
        routeDurationMs: 260,
        reducedMotionDurationMs: 90,
        hapticIntensity: 0.20,
      ),
      media: SdalMediaProfile(
        feedImageAspect: tokens.feedImageAspect,
        avatarFrameWidth: 1.3,
        preferImageOverlays: true,
      ),
    ),
    SdalAppTheme.mist => SdalThemeExperience(
      identity: const SdalThemeIdentity(
        id: 'mist',
        scene:
            'A member settles into longer reading, profile updates, and calm community browsing.',
        promise: 'A quieter garden-like SDAL for low-pressure sessions.',
        colorStrategy: 'Restrained botanical palette with coral warmth',
        mode: SdalMicroAppMode.garden,
      ),
      logo: logo(
        frame: isDark ? const Color(0xFF071A14) : const Color(0xFFEAF8F0),
        background: isDark ? const Color(0xFF10271E) : const Color(0xFFD8F2E4),
        border: tokens.panelBorder,
        shadow: tokens.success.withValues(alpha: isDark ? 0.28 : 0.14),
        radius: 22,
      ),
      shell: const SdalShellProfile(
        primaryActionPlacement: SdalPrimaryActionPlacement.pageFab,
        overlayHitTestMode: SdalOverlayHitTestMode.opaque,
        minimumTapTarget: 48,
      ),
      composition: const SdalCompositionProfile(
        feedLeadTreatment: SdalFeedLeadTreatment.calmGuide,
        listRhythm: 1.18,
        controlDensity: 1.05,
        contentBreathingRoom: 1.22,
      ),
      components: const SdalComponentProfile(
        surfaceMaterial: SdalSurfaceMaterial.organic,
        emptyStateTone: SdalEmptyStateTone.calm,
      ),
      motion: const SdalMotionProfile(
        pressScale: 0.98,
        routeDurationMs: 300,
        reducedMotionDurationMs: 100,
      ),
      media: SdalMediaProfile(
        feedImageAspect: tokens.feedImageAspect,
        avatarFrameWidth: 1.6,
        storyRingWidth: 2.2,
      ),
    ),
    SdalAppTheme.nova => SdalThemeExperience(
      identity: const SdalThemeIdentity(
        id: 'nova',
        scene: 'A member uses SDAL as a spatial, calm intelligence layer.',
        promise: 'Floating focus with glass used only for chrome.',
        colorStrategy: 'Restrained space blue with luminous focus',
        mode: SdalMicroAppMode.spatial,
      ),
      logo: logo(
        frame: isDark ? const Color(0xFF080B18) : const Color(0xFFEAF1FF),
        background: isDark ? const Color(0xFF101936) : const Color(0xFFDCE8FF),
        border: tokens.panelBorder,
        shadow: tokens.accent.withValues(alpha: isDark ? 0.34 : 0.18),
        radius: 20,
      ),
      shell: const SdalShellProfile(
        primaryActionPlacement: SdalPrimaryActionPlacement.pageFab,
        overlayHitTestMode: SdalOverlayHitTestMode.opaque,
        minimumTapTarget: 48,
      ),
      composition: const SdalCompositionProfile(
        feedLeadTreatment: SdalFeedLeadTreatment.spatialFloat,
        listRhythm: 1.08,
        controlDensity: 1.0,
        contentBreathingRoom: 1.12,
      ),
      components: const SdalComponentProfile(
        surfaceMaterial: SdalSurfaceMaterial.glass,
        emptyStateTone: SdalEmptyStateTone.minimal,
        allowDecorativeBlur: true,
      ),
      motion: const SdalMotionProfile(
        pressScale: 1.02,
        routeDurationMs: 380,
        reducedMotionDurationMs: 100,
      ),
      media: SdalMediaProfile(
        feedImageAspect: tokens.feedImageAspect,
        avatarFrameWidth: 1.2,
        preferImageOverlays: true,
      ),
    ),
    SdalAppTheme.prism => SdalThemeExperience(
      identity: const SdalThemeIdentity(
        id: 'prism',
        scene:
            'A member treats SDAL as a modular workspace of community tiles.',
        promise: 'Bento structure for dense community modules.',
        colorStrategy: 'Full palette violet with neutral workspace layers',
        mode: SdalMicroAppMode.bento,
      ),
      logo: logo(
        frame: isDark ? const Color(0xFF12111B) : const Color(0xFFF0ECFF),
        background: isDark ? const Color(0xFF211A3A) : const Color(0xFFE6DDFF),
        border: tokens.panelBorder,
        shadow: tokens.accent.withValues(alpha: isDark ? 0.30 : 0.16),
        radius: 16,
      ),
      shell: const SdalShellProfile(
        primaryActionPlacement: SdalPrimaryActionPlacement.pageFab,
        overlayHitTestMode: SdalOverlayHitTestMode.opaque,
        minimumTapTarget: 44,
      ),
      composition: const SdalCompositionProfile(
        feedLeadTreatment: SdalFeedLeadTreatment.bentoGrid,
        listRhythm: 0.96,
        controlDensity: 0.9,
        contentBreathingRoom: 0.95,
      ),
      components: const SdalComponentProfile(
        surfaceMaterial: SdalSurfaceMaterial.bento,
        emptyStateTone: SdalEmptyStateTone.modular,
      ),
      motion: const SdalMotionProfile(
        pressScale: 0.97,
        routeDurationMs: 180,
        reducedMotionDurationMs: 70,
      ),
      media: SdalMediaProfile(
        feedImageAspect: tokens.feedImageAspect,
        avatarFrameWidth: 1.4,
      ),
    ),
    SdalAppTheme.dusk => SdalThemeExperience(
      identity: const SdalThemeIdentity(
        id: 'dusk',
        scene:
            'A member browses SDAL at night with media-rich cinematic focus.',
        promise: 'Floating cinema chrome without blocking content controls.',
        colorStrategy: 'Drenched dark amber with ember red support',
        mode: SdalMicroAppMode.cinema,
      ),
      logo: logo(
        frame: isDark ? const Color(0xFF100A04) : const Color(0xFFFFF1D6),
        background: isDark ? const Color(0xFF251407) : const Color(0xFFFFDDA5),
        border: tokens.panelBorder,
        shadow: tokens.accent.withValues(alpha: isDark ? 0.42 : 0.20),
        radius: 10,
      ),
      shell: const SdalShellProfile(
        primaryActionPlacement: SdalPrimaryActionPlacement.pageFab,
        overlayHitTestMode: SdalOverlayHitTestMode.controlsOnly,
        passThroughTransparentChrome: true,
        minimumTapTarget: 48,
      ),
      composition: const SdalCompositionProfile(
        feedLeadTreatment: SdalFeedLeadTreatment.cinematic,
        listRhythm: 1.22,
        controlDensity: 1.0,
        contentBreathingRoom: 1.1,
      ),
      components: const SdalComponentProfile(
        surfaceMaterial: SdalSurfaceMaterial.cinema,
        emptyStateTone: SdalEmptyStateTone.cinematic,
      ),
      motion: const SdalMotionProfile(
        pressScale: 0.985,
        routeDurationMs: 500,
        reducedMotionDurationMs: 110,
      ),
      media: SdalMediaProfile(
        feedImageAspect: tokens.feedImageAspect,
        avatarFrameWidth: 1.5,
        preferImageOverlays: true,
        storyRingWidth: 2.6,
      ),
    ),
    SdalAppTheme.flux => SdalThemeExperience(
      identity: const SdalThemeIdentity(
        id: 'flux',
        scene:
            'A member moves quickly and expects SDAL to expose the next action.',
        promise: 'Adaptive Material action routing by current screen.',
        colorStrategy: 'Restrained adaptive teal with tonal surfaces',
        mode: SdalMicroAppMode.adaptive,
      ),
      logo: logo(
        frame: isDark ? const Color(0xFF061714) : const Color(0xFFE7FBF7),
        background: isDark ? const Color(0xFF0B2C25) : const Color(0xFFCFF6EC),
        border: tokens.panelBorder,
        shadow: tokens.accent.withValues(alpha: isDark ? 0.30 : 0.16),
        radius: 14,
      ),
      shell: const SdalShellProfile(
        primaryActionPlacement: SdalPrimaryActionPlacement.shellFab,
        overlayHitTestMode: SdalOverlayHitTestMode.opaque,
        prominentActionOnTabs: true,
        minimumTapTarget: 44,
      ),
      composition: const SdalCompositionProfile(
        feedLeadTreatment: SdalFeedLeadTreatment.adaptiveCompact,
        listRhythm: 0.86,
        controlDensity: 0.82,
        contentBreathingRoom: 0.88,
      ),
      components: const SdalComponentProfile(
        surfaceMaterial: SdalSurfaceMaterial.tonal,
        emptyStateTone: SdalEmptyStateTone.inline,
      ),
      motion: const SdalMotionProfile(
        pressScale: 0.97,
        routeDurationMs: 160,
        reducedMotionDurationMs: 60,
        hapticIntensity: 0.22,
      ),
      media: SdalMediaProfile(
        feedImageAspect: tokens.feedImageAspect,
        avatarFrameWidth: 1.0,
      ),
    ),
  };
}

// ---------------------------------------------------------------------------
// Atlas — deep cobalt, premium precision, clean navy depth
// ---------------------------------------------------------------------------

const _atlasLight = SdalThemeTokens(
  canvas: Color(0xFFF1F5FB),
  canvasSubtle: Color(0xFFE3EDF8),
  panel: Color(0xFFFBFDFF),
  panelRaised: Color(0xFFEBF2FB),
  panelMuted: Color(0xFFDAEAF8),
  panelBorder: Color(0xFFAAC8E8),
  accent: Color(0xFF1060A0),
  accentMuted: Color(0xFFCCE3F8),
  success: Color(0xFF1A6B48),
  successMuted: Color(0xFFD0EDE0),
  warning: Color(0xFF7A5A14),
  warningMuted: Color(0xFFF0E2C0),
  info: Color(0xFF244880),
  infoMuted: Color(0xFFCCD8F4),
  danger: Color(0xFF9E3430),
  dangerMuted: Color(0xFFF2D8D6),
  chatOutgoing: Color(0xFF1A4A70),
  chatIncoming: Color(0xFFFBFDFF),
  storyActive: Color(0xFF1060A0),
  storyInactive: Color(0xFFA4C2DC),
  storyOverlay: Color(0xB30A1628),
  imagePlaceholder: Color(0xFFCADEF2),
  imageError: Color(0xFFBCD0E8),
  foreground: Color(0xFF0A1628),
  foregroundMuted: Color(0xFF486078),
  foregroundOnAccent: Color(0xFFF0F8FF),
  adminExperiment: Color(0xFF4060B0),
  cardRadius: 12,
  buttonRadius: 10,
  inputRadius: 12,
  panelBorderWidth: 0.8,
  logoAsset: 'assets/logo_atlas.png',
  navStyle: SdalNavStyle.bottomBar,
  navLabelMode: SdalNavLabelMode.selectedOnly,
  navIndicator: SdalNavIndicator.underline,
  navBarBackground: SdalNavBarBackground.solid,
  headerStyle: SdalHeaderStyle.collapsible,
  headerBackground: SdalHeaderBackground.solid,
  logoPosition: SdalLogoPosition.leading,
  avatarPosition: SdalAvatarPosition.trailing,
  titleAlignment: SdalTitleAlignment.start,
  cardStyle: SdalCardStyle.outlined,
  surfaceDepth: SdalSurfaceDepth.flat,
  borderStyle: SdalBorderStyle.thin,
  backgroundPattern: SdalBackgroundPattern.subtleGradient,
  feedLayout: SdalFeedLayout.compact,
  listItemStyle: SdalListItemStyle.inlineCard,
  separatorStyle: SdalSeparatorStyle.hairline,
  scrollPhysics: SdalScrollPhysics.clamped,
  tapFeedback: SdalTapFeedback.ripple,
  transitionStyle: SdalTransitionStyle.scale,
  animationSpeed: SdalAnimationSpeed.fast,
  avatarShape: SdalAvatarShape.roundedSquare,
  avatarBorder: SdalAvatarBorder.accentRing,
  onlineIndicator: SdalOnlineIndicator.ring,
  memberBadgeStyle: SdalMemberBadgeStyle.subtleLabel,
  metaPlacement: SdalMetaPlacement.trailing,
  actionsStyle: SdalActionsStyle.contextMenu,
  statsDisplay: SdalStatsDisplay.inlineText,
  timestampStyle: SdalTimestampStyle.compact,
  menuStyle: SdalMenuStyle.bottomSheet,
  sheetStyle: SdalSheetStyle.lineHandle,
  loadingStyle: SdalLoadingStyle.skeleton,
  emptyStateStyle: SdalEmptyStateStyle.inline,
  imageShape: SdalImageShape.roundedSmall,
  headingWeight: SdalHeadingWeight.bold,
  typographyHierarchy: SdalTypographyHierarchy.functional,
  spacingScale: SdalSpacingScale.compact,
  contentInset: SdalContentInset.standard,
  badgeStyle: SdalBadgeStyle.count,
  unreadIndicator: SdalUnreadIndicator.accentBar,
  navBarHeight: 76.0,
  appBarHeight: 64.0,
  heroHeaderHeight: 84.0,
  contentPaddingH: 16.0,
  cardSpacing: 8.0,
  animationDurationMs: 170,
  feedImageAspect: 1.70,
);

const _atlasDark = SdalThemeTokens(
  canvas: Color(0xFF0B1424),
  canvasSubtle: Color(0xFF121E34),
  panel: Color(0xFF17223A),
  panelRaised: Color(0xFF1F2B46),
  panelMuted: Color(0xFF293752),
  panelBorder: Color(0xFF45586E),
  accent: Color(0xFF79A7D8),
  accentMuted: Color(0xFF233A59),
  success: Color(0xFF88BE9B),
  successMuted: Color(0xFF1B382C),
  warning: Color(0xFFD1B069),
  warningMuted: Color(0xFF3A3018),
  info: Color(0xFF8BBFD0),
  infoMuted: Color(0xFF183443),
  danger: Color(0xFFE19A92),
  dangerMuted: Color(0xFF462522),
  chatOutgoing: Color(0xFF26405B),
  chatIncoming: Color(0xFF17223A),
  storyActive: Color(0xFF79A7D8),
  storyInactive: Color(0xFF45586E),
  storyOverlay: Color(0xD904081E),
  imagePlaceholder: Color(0xFF283B55),
  imageError: Color(0xFF31445C),
  foreground: Color(0xFFE8F2FF),
  foregroundMuted: Color(0xFFA6BDD2),
  foregroundOnAccent: Color(0xFF0A1428),
  adminExperiment: Color(0xFF98ABD8),
  cardRadius: 12,
  buttonRadius: 10,
  inputRadius: 12,
  panelBorderWidth: 0.8,
  logoAsset: 'assets/logo_atlas.png',
  navStyle: SdalNavStyle.bottomBar,
  navLabelMode: SdalNavLabelMode.selectedOnly,
  navIndicator: SdalNavIndicator.underline,
  navBarBackground: SdalNavBarBackground.solid,
  headerStyle: SdalHeaderStyle.collapsible,
  headerBackground: SdalHeaderBackground.solid,
  logoPosition: SdalLogoPosition.leading,
  avatarPosition: SdalAvatarPosition.trailing,
  titleAlignment: SdalTitleAlignment.start,
  cardStyle: SdalCardStyle.outlined,
  surfaceDepth: SdalSurfaceDepth.flat,
  borderStyle: SdalBorderStyle.thin,
  backgroundPattern: SdalBackgroundPattern.subtleGradient,
  feedLayout: SdalFeedLayout.compact,
  listItemStyle: SdalListItemStyle.inlineCard,
  separatorStyle: SdalSeparatorStyle.hairline,
  scrollPhysics: SdalScrollPhysics.clamped,
  tapFeedback: SdalTapFeedback.ripple,
  transitionStyle: SdalTransitionStyle.scale,
  animationSpeed: SdalAnimationSpeed.fast,
  avatarShape: SdalAvatarShape.roundedSquare,
  avatarBorder: SdalAvatarBorder.accentRing,
  onlineIndicator: SdalOnlineIndicator.ring,
  memberBadgeStyle: SdalMemberBadgeStyle.subtleLabel,
  metaPlacement: SdalMetaPlacement.trailing,
  actionsStyle: SdalActionsStyle.contextMenu,
  statsDisplay: SdalStatsDisplay.inlineText,
  timestampStyle: SdalTimestampStyle.compact,
  menuStyle: SdalMenuStyle.bottomSheet,
  sheetStyle: SdalSheetStyle.lineHandle,
  loadingStyle: SdalLoadingStyle.skeleton,
  emptyStateStyle: SdalEmptyStateStyle.inline,
  imageShape: SdalImageShape.roundedSmall,
  headingWeight: SdalHeadingWeight.bold,
  typographyHierarchy: SdalTypographyHierarchy.functional,
  spacingScale: SdalSpacingScale.compact,
  contentInset: SdalContentInset.standard,
  badgeStyle: SdalBadgeStyle.count,
  unreadIndicator: SdalUnreadIndicator.accentBar,
  navBarHeight: 76.0,
  appBarHeight: 64.0,
  heroHeaderHeight: 84.0,
  contentPaddingH: 16.0,
  cardSpacing: 8.0,
  animationDurationMs: 170,
  feedImageAspect: 1.70,
);

// ---------------------------------------------------------------------------
// Vibe — electric violet, vivid energy, bold saturated punch
// ---------------------------------------------------------------------------

const _vibeLight = SdalThemeTokens(
  canvas: Color(0xFFF7F3FF),
  canvasSubtle: Color(0xFFEDE4FF),
  panel: Color(0xFFFEFCFF),
  panelRaised: Color(0xFFF3ECFF),
  panelMuted: Color(0xFFE8DCFF),
  panelBorder: Color(0xFFCCB0F0),
  accent: Color(0xFF6200EE),
  accentMuted: Color(0xFFE8D6FF),
  success: Color(0xFF1E6844),
  successMuted: Color(0xFFD0EDE0),
  warning: Color(0xFF7A5814),
  warningMuted: Color(0xFFF2E2C0),
  info: Color(0xFF2A5080),
  infoMuted: Color(0xFFCCDCF4),
  danger: Color(0xFF9E3030),
  dangerMuted: Color(0xFFF4D4D4),
  chatOutgoing: Color(0xFF3A0A90),
  chatIncoming: Color(0xFFFEFCFF),
  storyActive: Color(0xFF6200EE),
  storyInactive: Color(0xFFBBA8E0),
  storyOverlay: Color(0xB3100820),
  imagePlaceholder: Color(0xFFDDD0FF),
  imageError: Color(0xFFCEC0F0),
  foreground: Color(0xFF14083A),
  foregroundMuted: Color(0xFF584878),
  foregroundOnAccent: Color(0xFFFAF4FF),
  adminExperiment: Color(0xFF9050E0),
  cardRadius: 24,
  buttonRadius: 22,
  inputRadius: 22,
  panelBorderWidth: 0.7,
  logoAsset: 'assets/logo_vibe.png',
  navStyle: SdalNavStyle.floatingPill,
  navLabelMode: SdalNavLabelMode.never,
  navIndicator: SdalNavIndicator.dot,
  navBarBackground: SdalNavBarBackground.frosted,
  headerStyle: SdalHeaderStyle.minimal,
  headerBackground: SdalHeaderBackground.solid,
  logoPosition: SdalLogoPosition.center,
  avatarPosition: SdalAvatarPosition.trailing,
  titleAlignment: SdalTitleAlignment.center,
  cardStyle: SdalCardStyle.tonal,
  surfaceDepth: SdalSurfaceDepth.floating,
  borderStyle: SdalBorderStyle.hairline,
  backgroundPattern: SdalBackgroundPattern.mesh,
  feedLayout: SdalFeedLayout.singleColumn,
  listItemStyle: SdalListItemStyle.card,
  separatorStyle: SdalSeparatorStyle.cardGap,
  scrollPhysics: SdalScrollPhysics.bouncing,
  tapFeedback: SdalTapFeedback.scalePress,
  transitionStyle: SdalTransitionStyle.blurFade,
  animationSpeed: SdalAnimationSpeed.normal,
  scrollBehavior: SdalScrollBehavior.bouncy,
  avatarShape: SdalAvatarShape.squircle,
  avatarBorder: SdalAvatarBorder.gradient,
  onlineIndicator: SdalOnlineIndicator.pulse,
  memberBadgeStyle: SdalMemberBadgeStyle.iconTag,
  actionsStyle: SdalActionsStyle.pillButtons,
  statsDisplay: SdalStatsDisplay.chips,
  timestampStyle: SdalTimestampStyle.relative,
  menuStyle: SdalMenuStyle.bottomSheet,
  modalBackdrop: SdalModalBackdrop.blur,
  sheetStyle: SdalSheetStyle.pillHandle,
  loadingStyle: SdalLoadingStyle.pulse,
  emptyStateStyle: SdalEmptyStateStyle.card,
  imageShape: SdalImageShape.roundedLarge,
  imageOverlay: SdalImageOverlay.gradientBottom,
  placeholderStyle: SdalPlaceholderStyle.shimmer,
  headingWeight: SdalHeadingWeight.bold,
  typographyHierarchy: SdalTypographyHierarchy.display,
  spacingScale: SdalSpacingScale.airy,
  contentInset: SdalContentInset.wide,
  badgeStyle: SdalBadgeStyle.dot,
  unreadIndicator: SdalUnreadIndicator.badgeCount,
  toastPosition: SdalToastPosition.center,
  toastStyle: SdalToastStyle.pill,
  blurSigma: 14.0,
  glassOpacity: 0.08,
  navBarHeight: 66.0,
  floatingPillBottomPad: 18.0,
  appBarHeight: 46.0,
  contentPaddingH: 20.0,
  cardSpacing: 16.0,
  animationDurationMs: 230,
  feedImageAspect: 1.25,
);

const _vibeDark = SdalThemeTokens(
  canvas: Color(0xFF120C1E),
  canvasSubtle: Color(0xFF1B142B),
  panel: Color(0xFF241B38),
  panelRaised: Color(0xFF2D2346),
  panelMuted: Color(0xFF3A2E56),
  panelBorder: Color(0xFF574B70),
  accent: Color(0xFFA58BCB),
  accentMuted: Color(0xFF392850),
  success: Color(0xFF89C19D),
  successMuted: Color(0xFF1E382A),
  warning: Color(0xFFD0AF68),
  warningMuted: Color(0xFF3B3018),
  info: Color(0xFF8ABAC8),
  infoMuted: Color(0xFF1B3440),
  danger: Color(0xFFE19A9A),
  dangerMuted: Color(0xFF472424),
  chatOutgoing: Color(0xFF3D2A5C),
  chatIncoming: Color(0xFF241B38),
  storyActive: Color(0xFFA58BCB),
  storyInactive: Color(0xFF574B70),
  storyOverlay: Color(0xD90A0618),
  imagePlaceholder: Color(0xFF382E52),
  imageError: Color(0xFF45385E),
  foreground: Color(0xFFF2EEFF),
  foregroundMuted: Color(0xFFC1B5D8),
  foregroundOnAccent: Color(0xFF08000F),
  adminExperiment: Color(0xFFBDA0D8),
  cardRadius: 24,
  buttonRadius: 22,
  inputRadius: 22,
  panelBorderWidth: 0.7,
  logoAsset: 'assets/logo_vibe.png',
  navStyle: SdalNavStyle.floatingPill,
  navLabelMode: SdalNavLabelMode.never,
  navIndicator: SdalNavIndicator.dot,
  navBarBackground: SdalNavBarBackground.frosted,
  headerStyle: SdalHeaderStyle.minimal,
  headerBackground: SdalHeaderBackground.solid,
  logoPosition: SdalLogoPosition.center,
  avatarPosition: SdalAvatarPosition.trailing,
  titleAlignment: SdalTitleAlignment.center,
  cardStyle: SdalCardStyle.tonal,
  surfaceDepth: SdalSurfaceDepth.floating,
  borderStyle: SdalBorderStyle.hairline,
  backgroundPattern: SdalBackgroundPattern.mesh,
  feedLayout: SdalFeedLayout.singleColumn,
  listItemStyle: SdalListItemStyle.card,
  separatorStyle: SdalSeparatorStyle.cardGap,
  scrollPhysics: SdalScrollPhysics.bouncing,
  tapFeedback: SdalTapFeedback.scalePress,
  transitionStyle: SdalTransitionStyle.blurFade,
  animationSpeed: SdalAnimationSpeed.normal,
  scrollBehavior: SdalScrollBehavior.bouncy,
  avatarShape: SdalAvatarShape.squircle,
  avatarBorder: SdalAvatarBorder.gradient,
  onlineIndicator: SdalOnlineIndicator.pulse,
  memberBadgeStyle: SdalMemberBadgeStyle.iconTag,
  actionsStyle: SdalActionsStyle.pillButtons,
  statsDisplay: SdalStatsDisplay.chips,
  timestampStyle: SdalTimestampStyle.relative,
  menuStyle: SdalMenuStyle.bottomSheet,
  modalBackdrop: SdalModalBackdrop.blur,
  sheetStyle: SdalSheetStyle.pillHandle,
  loadingStyle: SdalLoadingStyle.pulse,
  emptyStateStyle: SdalEmptyStateStyle.card,
  imageShape: SdalImageShape.roundedLarge,
  imageOverlay: SdalImageOverlay.gradientBottom,
  placeholderStyle: SdalPlaceholderStyle.shimmer,
  headingWeight: SdalHeadingWeight.bold,
  typographyHierarchy: SdalTypographyHierarchy.display,
  spacingScale: SdalSpacingScale.airy,
  contentInset: SdalContentInset.wide,
  badgeStyle: SdalBadgeStyle.dot,
  unreadIndicator: SdalUnreadIndicator.badgeCount,
  toastPosition: SdalToastPosition.center,
  toastStyle: SdalToastStyle.pill,
  blurSigma: 14.0,
  glassOpacity: 0.08,
  navBarHeight: 66.0,
  floatingPillBottomPad: 18.0,
  appBarHeight: 46.0,
  contentPaddingH: 20.0,
  cardSpacing: 16.0,
  animationDurationMs: 230,
  feedImageAspect: 1.25,
);

// ---------------------------------------------------------------------------
// Zinc — noir editorial, electric teal accent, razor-sharp
// ---------------------------------------------------------------------------

const _zincLight = SdalThemeTokens(
  canvas: Color(0xFFF3F4F6),
  canvasSubtle: Color(0xFFE6E8EC),
  panel: Color(0xFFFAFAFB),
  panelRaised: Color(0xFFEDEEF1),
  panelMuted: Color(0xFFDFE1E6),
  panelBorder: Color(0xFFBCC0C8),
  accent: Color(0xFF0891B2),
  accentMuted: Color(0xFFCCF0F8),
  success: Color(0xFF1E6844),
  successMuted: Color(0xFFD0EDE0),
  warning: Color(0xFF7A5A14),
  warningMuted: Color(0xFFF0E2C0),
  info: Color(0xFF1C4A6E),
  infoMuted: Color(0xFFCCDCF0),
  danger: Color(0xFF9E3430),
  dangerMuted: Color(0xFFF0D8D6),
  chatOutgoing: Color(0xFF1A3A48),
  chatIncoming: Color(0xFFFAFAFB),
  storyActive: Color(0xFF0891B2),
  storyInactive: Color(0xFFA0AABC),
  storyOverlay: Color(0xB30A0C10),
  imagePlaceholder: Color(0xFFD4D8E0),
  imageError: Color(0xFFC8CCD4),
  foreground: Color(0xFF101216),
  foregroundMuted: Color(0xFF545C68),
  foregroundOnAccent: Color(0xFFF0FAFF),
  adminExperiment: Color(0xFF4860A8),
  cardRadius: 6,
  buttonRadius: 4,
  inputRadius: 6,
  panelBorderWidth: 0.8,
  logoAsset: 'assets/logo_zinc.png',
  navStyle: SdalNavStyle.bottomBar,
  navLabelMode: SdalNavLabelMode.never,
  navIndicator: SdalNavIndicator.accentIcon,
  navBarBackground: SdalNavBarBackground.solid,
  headerStyle: SdalHeaderStyle.minimal,
  headerBackground: SdalHeaderBackground.solid,
  logoPosition: SdalLogoPosition.leading,
  avatarPosition: SdalAvatarPosition.trailing,
  titleAlignment: SdalTitleAlignment.start,
  cardStyle: SdalCardStyle.flat,
  surfaceDepth: SdalSurfaceDepth.flat,
  borderStyle: SdalBorderStyle.hairline,
  backgroundPattern: SdalBackgroundPattern.solid,
  feedLayout: SdalFeedLayout.compact,
  listItemStyle: SdalListItemStyle.tile,
  separatorStyle: SdalSeparatorStyle.hairline,
  scrollPhysics: SdalScrollPhysics.clamped,
  tapFeedback: SdalTapFeedback.highlight,
  transitionStyle: SdalTransitionStyle.fade,
  animationSpeed: SdalAnimationSpeed.fast,
  avatarShape: SdalAvatarShape.roundedSquare,
  avatarBorder: SdalAvatarBorder.none,
  onlineIndicator: SdalOnlineIndicator.dot,
  memberBadgeStyle: SdalMemberBadgeStyle.subtleLabel,
  metaPlacement: SdalMetaPlacement.inline,
  actionsStyle: SdalActionsStyle.contextMenu,
  statsDisplay: SdalStatsDisplay.inlineText,
  timestampStyle: SdalTimestampStyle.compact,
  menuStyle: SdalMenuStyle.bottomSheet,
  sheetStyle: SdalSheetStyle.lineHandle,
  loadingStyle: SdalLoadingStyle.skeleton,
  emptyStateStyle: SdalEmptyStateStyle.inline,
  imageShape: SdalImageShape.roundedSmall,
  headingWeight: SdalHeadingWeight.black,
  bodyLineHeight: SdalBodyLineHeight.tight,
  typographyHierarchy: SdalTypographyHierarchy.functional,
  spacingScale: SdalSpacingScale.compact,
  contentInset: SdalContentInset.tight,
  badgeStyle: SdalBadgeStyle.dot,
  unreadIndicator: SdalUnreadIndicator.accentBar,
  navBarHeight: 68.0,
  appBarHeight: 44.0,
  contentPaddingH: 12.0,
  cardSpacing: 6.0,
  animationDurationMs: 130,
  feedImageAspect: 1.90,
);

const _zincDark = SdalThemeTokens(
  canvas: Color(0xFF0D0D0F),
  canvasSubtle: Color(0xFF141417),
  panel: Color(0xFF1A1B1E),
  panelRaised: Color(0xFF222429),
  panelMuted: Color(0xFF2B2E34),
  panelBorder: Color(0xFF464B54),
  accent: Color(0xFF8AB8C4),
  accentMuted: Color(0xFF20363C),
  success: Color(0xFF8BC7A0),
  successMuted: Color(0xFF1A3424),
  warning: Color(0xFFD1AE62),
  warningMuted: Color(0xFF372B12),
  info: Color(0xFF8EBBD0),
  infoMuted: Color(0xFF1B3442),
  danger: Color(0xFFE39A9A),
  dangerMuted: Color(0xFF3A2020),
  chatOutgoing: Color(0xFF233A42),
  chatIncoming: Color(0xFF1A1B1E),
  storyActive: Color(0xFF8AB8C4),
  storyInactive: Color(0xFF464B54),
  storyOverlay: Color(0xD9020204),
  imagePlaceholder: Color(0xFF24262D),
  imageError: Color(0xFF2D3038),
  foreground: Color(0xFFF0F1F3),
  foregroundMuted: Color(0xFFA5AAB3),
  foregroundOnAccent: Color(0xFF02080A),
  adminExperiment: Color(0xFF9AAAD0),
  cardRadius: 6,
  buttonRadius: 4,
  inputRadius: 6,
  panelBorderWidth: 0.8,
  logoAsset: 'assets/logo_zinc.png',
  navStyle: SdalNavStyle.bottomBar,
  navLabelMode: SdalNavLabelMode.never,
  navIndicator: SdalNavIndicator.accentIcon,
  navBarBackground: SdalNavBarBackground.solid,
  headerStyle: SdalHeaderStyle.minimal,
  headerBackground: SdalHeaderBackground.solid,
  logoPosition: SdalLogoPosition.leading,
  avatarPosition: SdalAvatarPosition.trailing,
  titleAlignment: SdalTitleAlignment.start,
  cardStyle: SdalCardStyle.flat,
  surfaceDepth: SdalSurfaceDepth.flat,
  borderStyle: SdalBorderStyle.hairline,
  backgroundPattern: SdalBackgroundPattern.solid,
  feedLayout: SdalFeedLayout.compact,
  listItemStyle: SdalListItemStyle.tile,
  separatorStyle: SdalSeparatorStyle.hairline,
  scrollPhysics: SdalScrollPhysics.clamped,
  tapFeedback: SdalTapFeedback.highlight,
  transitionStyle: SdalTransitionStyle.fade,
  animationSpeed: SdalAnimationSpeed.fast,
  avatarShape: SdalAvatarShape.roundedSquare,
  avatarBorder: SdalAvatarBorder.none,
  onlineIndicator: SdalOnlineIndicator.dot,
  memberBadgeStyle: SdalMemberBadgeStyle.subtleLabel,
  metaPlacement: SdalMetaPlacement.inline,
  actionsStyle: SdalActionsStyle.contextMenu,
  statsDisplay: SdalStatsDisplay.inlineText,
  timestampStyle: SdalTimestampStyle.compact,
  menuStyle: SdalMenuStyle.bottomSheet,
  sheetStyle: SdalSheetStyle.lineHandle,
  loadingStyle: SdalLoadingStyle.skeleton,
  emptyStateStyle: SdalEmptyStateStyle.inline,
  imageShape: SdalImageShape.roundedSmall,
  headingWeight: SdalHeadingWeight.black,
  bodyLineHeight: SdalBodyLineHeight.tight,
  typographyHierarchy: SdalTypographyHierarchy.functional,
  spacingScale: SdalSpacingScale.compact,
  contentInset: SdalContentInset.tight,
  badgeStyle: SdalBadgeStyle.dot,
  unreadIndicator: SdalUnreadIndicator.accentBar,
  navBarHeight: 68.0,
  appBarHeight: 44.0,
  contentPaddingH: 12.0,
  cardSpacing: 6.0,
  animationDurationMs: 130,
  feedImageAspect: 1.90,
);

// ---------------------------------------------------------------------------
// Ember — wildfire amber, rich luxury gold, warm depth
// ---------------------------------------------------------------------------

const _emberLight = SdalThemeTokens(
  canvas: Color(0xFFFDF7EE),
  canvasSubtle: Color(0xFFF5E8D6),
  panel: Color(0xFFFFFEF8),
  panelRaised: Color(0xFFF8EDD8),
  panelMuted: Color(0xFFEEDCC0),
  panelBorder: Color(0xFFD4A860),
  accent: Color(0xFFD4700A),
  accentMuted: Color(0xFFFFF0CC),
  success: Color(0xFF1E6844),
  successMuted: Color(0xFFD0EDE0),
  warning: Color(0xFF8A5A10),
  warningMuted: Color(0xFFF2E0B8),
  info: Color(0xFF2A5478),
  infoMuted: Color(0xFFCCE4F4),
  danger: Color(0xFF9E3428),
  dangerMuted: Color(0xFFF4D4D0),
  chatOutgoing: Color(0xFF6A3800),
  chatIncoming: Color(0xFFFFFEF8),
  storyActive: Color(0xFFD4700A),
  storyInactive: Color(0xFFCCB080),
  storyOverlay: Color(0xB3221200),
  imagePlaceholder: Color(0xFFECDCAC),
  imageError: Color(0xFFE0CC9C),
  foreground: Color(0xFF2A1400),
  foregroundMuted: Color(0xFF6C4C1A),
  foregroundOnAccent: Color(0xFFFFFAF0),
  adminExperiment: Color(0xFF7050A0),
  cardRadius: 16,
  buttonRadius: 14,
  inputRadius: 14,
  panelBorderWidth: 0.8,
  logoAsset: 'assets/logo_ember.png',
  navStyle: SdalNavStyle.bottomBar,
  navLabelMode: SdalNavLabelMode.always,
  navIndicator: SdalNavIndicator.dot,
  navBarBackground: SdalNavBarBackground.elevated,
  headerStyle: SdalHeaderStyle.standard,
  headerBackground: SdalHeaderBackground.solid,
  logoPosition: SdalLogoPosition.center,
  avatarPosition: SdalAvatarPosition.leading,
  titleAlignment: SdalTitleAlignment.center,
  cardStyle: SdalCardStyle.elevated,
  surfaceDepth: SdalSurfaceDepth.raised,
  borderStyle: SdalBorderStyle.none,
  backgroundPattern: SdalBackgroundPattern.noise,
  feedLayout: SdalFeedLayout.magazine,
  listItemStyle: SdalListItemStyle.card,
  separatorStyle: SdalSeparatorStyle.cardGap,
  scrollPhysics: SdalScrollPhysics.bouncing,
  tapFeedback: SdalTapFeedback.lift,
  transitionStyle: SdalTransitionStyle.fade,
  animationSpeed: SdalAnimationSpeed.slow,
  avatarShape: SdalAvatarShape.circle,
  avatarBorder: SdalAvatarBorder.photoRim,
  onlineIndicator: SdalOnlineIndicator.ring,
  memberBadgeStyle: SdalMemberBadgeStyle.pill,
  metaPlacement: SdalMetaPlacement.below,
  actionsStyle: SdalActionsStyle.textButtons,
  statsDisplay: SdalStatsDisplay.metricCards,
  timestampStyle: SdalTimestampStyle.relative,
  menuStyle: SdalMenuStyle.bottomSheet,
  modalBackdrop: SdalModalBackdrop.tinted,
  sheetStyle: SdalSheetStyle.pillHandle,
  loadingStyle: SdalLoadingStyle.shimmer,
  emptyStateStyle: SdalEmptyStateStyle.card,
  imageShape: SdalImageShape.roundedLarge,
  imageOverlay: SdalImageOverlay.gradientBottom,
  placeholderStyle: SdalPlaceholderStyle.solidColor,
  headingWeight: SdalHeadingWeight.bold,
  bodyLineHeight: SdalBodyLineHeight.loose,
  typographyHierarchy: SdalTypographyHierarchy.editorial,
  spacingScale: SdalSpacingScale.normal,
  contentInset: SdalContentInset.wide,
  badgeStyle: SdalBadgeStyle.count,
  unreadIndicator: SdalUnreadIndicator.badgeCount,
  toastPosition: SdalToastPosition.bottom,
  toastStyle: SdalToastStyle.card,
  navBarHeight: 84.0,
  appBarHeight: 60.0,
  contentPaddingH: 18.0,
  cardSpacing: 14.0,
  animationDurationMs: 260,
  feedImageAspect: 1.20,
);

const _emberDark = SdalThemeTokens(
  canvas: Color(0xFF181107),
  canvasSubtle: Color(0xFF22190B),
  panel: Color(0xFF2A1E0E),
  panelRaised: Color(0xFF342713),
  panelMuted: Color(0xFF423218),
  panelBorder: Color(0xFF6B5530),
  accent: Color(0xFFD7A24E),
  accentMuted: Color(0xFF4C3514),
  success: Color(0xFF8BC19E),
  successMuted: Color(0xFF223A2A),
  warning: Color(0xFFD4B16B),
  warningMuted: Color(0xFF3E2F12),
  info: Color(0xFF8CBAC8),
  infoMuted: Color(0xFF1D3440),
  danger: Color(0xFFE09B91),
  dangerMuted: Color(0xFF482720),
  chatOutgoing: Color(0xFF493315),
  chatIncoming: Color(0xFF2A1E0E),
  storyActive: Color(0xFFD7A24E),
  storyInactive: Color(0xFF6B5530),
  storyOverlay: Color(0xD90A0600),
  imagePlaceholder: Color(0xFF423116),
  imageError: Color(0xFF503C1D),
  foreground: Color(0xFFFFF3DF),
  foregroundMuted: Color(0xFFD3B882),
  foregroundOnAccent: Color(0xFF1A0E00),
  adminExperiment: Color(0xFFBEA0D0),
  cardRadius: 16,
  buttonRadius: 14,
  inputRadius: 14,
  panelBorderWidth: 0.8,
  logoAsset: 'assets/logo_ember.png',
  navStyle: SdalNavStyle.bottomBar,
  navLabelMode: SdalNavLabelMode.always,
  navIndicator: SdalNavIndicator.dot,
  navBarBackground: SdalNavBarBackground.elevated,
  headerStyle: SdalHeaderStyle.standard,
  headerBackground: SdalHeaderBackground.solid,
  logoPosition: SdalLogoPosition.center,
  avatarPosition: SdalAvatarPosition.leading,
  titleAlignment: SdalTitleAlignment.center,
  cardStyle: SdalCardStyle.elevated,
  surfaceDepth: SdalSurfaceDepth.raised,
  borderStyle: SdalBorderStyle.none,
  backgroundPattern: SdalBackgroundPattern.noise,
  feedLayout: SdalFeedLayout.magazine,
  listItemStyle: SdalListItemStyle.card,
  separatorStyle: SdalSeparatorStyle.cardGap,
  scrollPhysics: SdalScrollPhysics.bouncing,
  tapFeedback: SdalTapFeedback.lift,
  transitionStyle: SdalTransitionStyle.fade,
  animationSpeed: SdalAnimationSpeed.slow,
  avatarShape: SdalAvatarShape.circle,
  avatarBorder: SdalAvatarBorder.photoRim,
  onlineIndicator: SdalOnlineIndicator.ring,
  memberBadgeStyle: SdalMemberBadgeStyle.pill,
  metaPlacement: SdalMetaPlacement.below,
  actionsStyle: SdalActionsStyle.textButtons,
  statsDisplay: SdalStatsDisplay.metricCards,
  timestampStyle: SdalTimestampStyle.relative,
  menuStyle: SdalMenuStyle.bottomSheet,
  modalBackdrop: SdalModalBackdrop.tinted,
  sheetStyle: SdalSheetStyle.pillHandle,
  loadingStyle: SdalLoadingStyle.shimmer,
  emptyStateStyle: SdalEmptyStateStyle.card,
  imageShape: SdalImageShape.roundedLarge,
  imageOverlay: SdalImageOverlay.gradientBottom,
  placeholderStyle: SdalPlaceholderStyle.solidColor,
  headingWeight: SdalHeadingWeight.bold,
  bodyLineHeight: SdalBodyLineHeight.loose,
  typographyHierarchy: SdalTypographyHierarchy.editorial,
  spacingScale: SdalSpacingScale.normal,
  contentInset: SdalContentInset.wide,
  badgeStyle: SdalBadgeStyle.count,
  unreadIndicator: SdalUnreadIndicator.badgeCount,
  toastPosition: SdalToastPosition.bottom,
  toastStyle: SdalToastStyle.card,
  navBarHeight: 84.0,
  appBarHeight: 60.0,
  contentPaddingH: 18.0,
  cardSpacing: 14.0,
  animationDurationMs: 260,
  feedImageAspect: 1.20,
);

// ---------------------------------------------------------------------------
// Mist — vibrant emerald, fresh vitality, spring-green dark mode
// ---------------------------------------------------------------------------

const _mistLight = SdalThemeTokens(
  canvas: Color(0xFFF0FAF5),
  canvasSubtle: Color(0xFFDFF3E8),
  panel: Color(0xFFFAFEFC),
  panelRaised: Color(0xFFEBF8F1),
  panelMuted: Color(0xFFD6F0E4),
  panelBorder: Color(0xFF9ACDB5),
  accent: Color(0xFF087F5B),
  accentMuted: Color(0xFFBBEDD8),
  success: Color(0xFF206848),
  successMuted: Color(0xFFCCEEDC),
  warning: Color(0xFF7A5A14),
  warningMuted: Color(0xFFEEE0BE),
  info: Color(0xFF245470),
  infoMuted: Color(0xFFCCE4F0),
  danger: Color(0xFF9E3838),
  dangerMuted: Color(0xFFF2D4D4),
  chatOutgoing: Color(0xFF1C5038),
  chatIncoming: Color(0xFFFAFEFC),
  storyActive: Color(0xFF087F5B),
  storyInactive: Color(0xFF8ABFAA),
  storyOverlay: Color(0xB3081A10),
  imagePlaceholder: Color(0xFFBEE8D4),
  imageError: Color(0xFFAEDCC8),
  foreground: Color(0xFF081E14),
  foregroundMuted: Color(0xFF3E6050),
  foregroundOnAccent: Color(0xFFF0FBF6),
  adminExperiment: Color(0xFF5850A8),
  cardRadius: 22,
  buttonRadius: 18,
  inputRadius: 18,
  panelBorderWidth: 0.7,
  logoAsset: 'assets/logo_mist.png',
  navStyle: SdalNavStyle.bottomBar,
  navLabelMode: SdalNavLabelMode.always,
  navIndicator: SdalNavIndicator.filledPill,
  navBarBackground: SdalNavBarBackground.frosted,
  headerStyle: SdalHeaderStyle.standard,
  headerBackground: SdalHeaderBackground.solid,
  logoPosition: SdalLogoPosition.center,
  avatarPosition: SdalAvatarPosition.trailing,
  titleAlignment: SdalTitleAlignment.center,
  cardStyle: SdalCardStyle.tonal,
  surfaceDepth: SdalSurfaceDepth.subtle,
  borderStyle: SdalBorderStyle.hairline,
  backgroundPattern: SdalBackgroundPattern.subtleGradient,
  feedLayout: SdalFeedLayout.singleColumn,
  listItemStyle: SdalListItemStyle.card,
  separatorStyle: SdalSeparatorStyle.spacer,
  scrollPhysics: SdalScrollPhysics.bouncing,
  tapFeedback: SdalTapFeedback.lift,
  transitionStyle: SdalTransitionStyle.fade,
  animationSpeed: SdalAnimationSpeed.slow,
  scrollBehavior: SdalScrollBehavior.smooth,
  avatarShape: SdalAvatarShape.squircle,
  avatarBorder: SdalAvatarBorder.photoRim,
  onlineIndicator: SdalOnlineIndicator.dot,
  memberBadgeStyle: SdalMemberBadgeStyle.pill,
  metaPlacement: SdalMetaPlacement.below,
  actionsStyle: SdalActionsStyle.iconRow,
  statsDisplay: SdalStatsDisplay.chips,
  timestampStyle: SdalTimestampStyle.relative,
  menuStyle: SdalMenuStyle.bottomSheet,
  modalBackdrop: SdalModalBackdrop.dim,
  sheetStyle: SdalSheetStyle.pillHandle,
  loadingStyle: SdalLoadingStyle.pulse,
  emptyStateStyle: SdalEmptyStateStyle.centered,
  imageShape: SdalImageShape.roundedLarge,
  imageOverlay: SdalImageOverlay.none,
  placeholderStyle: SdalPlaceholderStyle.crossFade,
  headingWeight: SdalHeadingWeight.semibold,
  bodyLineHeight: SdalBodyLineHeight.loose,
  typographyHierarchy: SdalTypographyHierarchy.standard,
  spacingScale: SdalSpacingScale.airy,
  contentInset: SdalContentInset.wide,
  badgeStyle: SdalBadgeStyle.count,
  unreadIndicator: SdalUnreadIndicator.coloredDot,
  toastPosition: SdalToastPosition.bottom,
  toastStyle: SdalToastStyle.pill,
  blurSigma: 8.0,
  glassOpacity: 0.04,
  navBarHeight: 84.0,
  appBarHeight: 58.0,
  contentPaddingH: 22.0,
  cardSpacing: 18.0,
  animationDurationMs: 300,
  feedImageAspect: 1.60,
);

const _mistDark = SdalThemeTokens(
  canvas: Color(0xFF0A1210),
  canvasSubtle: Color(0xFF111C18),
  panel: Color(0xFF17231D),
  panelRaised: Color(0xFF1F2E25),
  panelMuted: Color(0xFF283A2F),
  panelBorder: Color(0xFF3D5A48),
  accent: Color(0xFF86B892),
  accentMuted: Color(0xFF253B2A),
  success: Color(0xFF8AC49D),
  successMuted: Color(0xFF1E3929),
  warning: Color(0xFFD0AD66),
  warningMuted: Color(0xFF3A3018),
  info: Color(0xFF8EBAC8),
  infoMuted: Color(0xFF1B3440),
  danger: Color(0xFFE19A9A),
  dangerMuted: Color(0xFF462424),
  chatOutgoing: Color(0xFF253C2D),
  chatIncoming: Color(0xFF17231D),
  storyActive: Color(0xFF86B892),
  storyInactive: Color(0xFF3D5A48),
  storyOverlay: Color(0xD9040E08),
  imagePlaceholder: Color(0xFF24362D),
  imageError: Color(0xFF2D4336),
  foreground: Color(0xFFE4F3EA),
  foregroundMuted: Color(0xFFA7C4B2),
  foregroundOnAccent: Color(0xFF041008),
  adminExperiment: Color(0xFFA8ABD8),
  cardRadius: 22,
  buttonRadius: 18,
  inputRadius: 18,
  panelBorderWidth: 0.7,
  logoAsset: 'assets/logo_mist.png',
  navStyle: SdalNavStyle.bottomBar,
  navLabelMode: SdalNavLabelMode.always,
  navIndicator: SdalNavIndicator.filledPill,
  navBarBackground: SdalNavBarBackground.frosted,
  headerStyle: SdalHeaderStyle.standard,
  headerBackground: SdalHeaderBackground.solid,
  logoPosition: SdalLogoPosition.center,
  avatarPosition: SdalAvatarPosition.trailing,
  titleAlignment: SdalTitleAlignment.center,
  cardStyle: SdalCardStyle.tonal,
  surfaceDepth: SdalSurfaceDepth.subtle,
  borderStyle: SdalBorderStyle.hairline,
  backgroundPattern: SdalBackgroundPattern.subtleGradient,
  feedLayout: SdalFeedLayout.singleColumn,
  listItemStyle: SdalListItemStyle.card,
  separatorStyle: SdalSeparatorStyle.spacer,
  scrollPhysics: SdalScrollPhysics.bouncing,
  tapFeedback: SdalTapFeedback.lift,
  transitionStyle: SdalTransitionStyle.fade,
  animationSpeed: SdalAnimationSpeed.slow,
  scrollBehavior: SdalScrollBehavior.smooth,
  avatarShape: SdalAvatarShape.squircle,
  avatarBorder: SdalAvatarBorder.photoRim,
  onlineIndicator: SdalOnlineIndicator.dot,
  memberBadgeStyle: SdalMemberBadgeStyle.pill,
  metaPlacement: SdalMetaPlacement.below,
  actionsStyle: SdalActionsStyle.iconRow,
  statsDisplay: SdalStatsDisplay.chips,
  timestampStyle: SdalTimestampStyle.relative,
  menuStyle: SdalMenuStyle.bottomSheet,
  modalBackdrop: SdalModalBackdrop.dim,
  sheetStyle: SdalSheetStyle.pillHandle,
  loadingStyle: SdalLoadingStyle.pulse,
  emptyStateStyle: SdalEmptyStateStyle.centered,
  imageShape: SdalImageShape.roundedLarge,
  imageOverlay: SdalImageOverlay.none,
  placeholderStyle: SdalPlaceholderStyle.crossFade,
  headingWeight: SdalHeadingWeight.semibold,
  bodyLineHeight: SdalBodyLineHeight.loose,
  typographyHierarchy: SdalTypographyHierarchy.standard,
  spacingScale: SdalSpacingScale.airy,
  contentInset: SdalContentInset.wide,
  badgeStyle: SdalBadgeStyle.count,
  unreadIndicator: SdalUnreadIndicator.coloredDot,
  toastPosition: SdalToastPosition.bottom,
  toastStyle: SdalToastStyle.pill,
  blurSigma: 8.0,
  glassOpacity: 0.04,
  navBarHeight: 84.0,
  appBarHeight: 58.0,
  contentPaddingH: 22.0,
  cardSpacing: 18.0,
  animationDurationMs: 300,
  feedImageAspect: 1.60,
);

// ---------------------------------------------------------------------------
// Nova — spatial glass, intelligence-first, deep space
// ---------------------------------------------------------------------------

const _novaLight = SdalThemeTokens(
  canvas: Color(0xFFF0F4FF),
  canvasSubtle: Color(0xFFE2EBFF),
  panel: Color(0xFFFFFFFF),
  panelRaised: Color(0xFFECF2FF),
  panelMuted: Color(0xFFDAE5FF),
  panelBorder: Color(0xFFB0C4F8),
  accent: Color(0xFF1D4ED8),
  accentMuted: Color(0xFFDBE8FF),
  success: Color(0xFF1A6B48),
  successMuted: Color(0xFFD0EDE0),
  warning: Color(0xFF7A5A14),
  warningMuted: Color(0xFFF0E2C0),
  info: Color(0xFF1D4ED8),
  infoMuted: Color(0xFFDBE8FF),
  danger: Color(0xFF9E3430),
  dangerMuted: Color(0xFFF2D8D6),
  chatOutgoing: Color(0xFF1E40AF),
  chatIncoming: Color(0xFFF8FAFF),
  storyActive: Color(0xFF1D4ED8),
  storyInactive: Color(0xFFB0C4F8),
  storyOverlay: Color(0xB3050614),
  imagePlaceholder: Color(0xFFD0DCFF),
  imageError: Color(0xFFC2D0F8),
  foreground: Color(0xFF0B0F2A),
  foregroundMuted: Color(0xFF4A5480),
  foregroundOnAccent: Color(0xFFF8FAFF),
  adminExperiment: Color(0xFF6060C8),
  cardRadius: 24,
  buttonRadius: 20,
  inputRadius: 24,
  panelBorderWidth: 0.5,
  logoAsset: 'assets/logo_nova.png',
  navStyle: SdalNavStyle.floatingPill,
  navLabelMode: SdalNavLabelMode.never,
  navIndicator: SdalNavIndicator.accentIcon,
  navBarBackground: SdalNavBarBackground.frosted,
  headerStyle: SdalHeaderStyle.minimal,
  headerBackground: SdalHeaderBackground.frosted,
  logoPosition: SdalLogoPosition.leading,
  avatarPosition: SdalAvatarPosition.trailing,
  titleAlignment: SdalTitleAlignment.center,
  cardStyle: SdalCardStyle.glass,
  surfaceDepth: SdalSurfaceDepth.glass,
  borderStyle: SdalBorderStyle.hairline,
  backgroundPattern: SdalBackgroundPattern.radialGlow,
  feedLayout: SdalFeedLayout.singleColumn,
  listItemStyle: SdalListItemStyle.card,
  separatorStyle: SdalSeparatorStyle.spacer,
  scrollPhysics: SdalScrollPhysics.bouncing,
  tapFeedback: SdalTapFeedback.lift,
  transitionStyle: SdalTransitionStyle.blurFade,
  animationSpeed: SdalAnimationSpeed.slow,
  scrollBehavior: SdalScrollBehavior.smooth,
  avatarShape: SdalAvatarShape.roundedSquare,
  avatarBorder: SdalAvatarBorder.glowRing,
  onlineIndicator: SdalOnlineIndicator.pulse,
  memberBadgeStyle: SdalMemberBadgeStyle.none,
  metaPlacement: SdalMetaPlacement.below,
  actionsStyle: SdalActionsStyle.floating,
  statsDisplay: SdalStatsDisplay.chips,
  timestampStyle: SdalTimestampStyle.compact,
  menuStyle: SdalMenuStyle.fullscreen,
  modalBackdrop: SdalModalBackdrop.frosted,
  sheetStyle: SdalSheetStyle.none,
  loadingStyle: SdalLoadingStyle.pulse,
  emptyStateStyle: SdalEmptyStateStyle.minimal,
  imageShape: SdalImageShape.roundedLarge,
  imageOverlay: SdalImageOverlay.gradientBottom,
  placeholderStyle: SdalPlaceholderStyle.crossFade,
  headingWeight: SdalHeadingWeight.light,
  bodyLineHeight: SdalBodyLineHeight.loose,
  letterSpacing: SdalLetterSpacing.tight,
  typographyHierarchy: SdalTypographyHierarchy.display,
  spacingScale: SdalSpacingScale.airy,
  contentInset: SdalContentInset.wide,
  badgeStyle: SdalBadgeStyle.dot,
  unreadIndicator: SdalUnreadIndicator.coloredDot,
  toastPosition: SdalToastPosition.center,
  toastStyle: SdalToastStyle.pill,
  blurSigma: 20.0,
  glassOpacity: 0.10,
  glassSheetOpacity: 0.88,
  navBarHeight: 64.0,
  floatingPillBottomPad: 20.0,
  appBarHeight: 44.0,
  heroHeaderHeight: 0.0,
  contentPaddingH: 20.0,
  cardSpacing: 16.0,
  animationDurationMs: 380,
  feedImageAspect: 1.50,
);

const _novaDark = SdalThemeTokens(
  canvas: Color(0xFF070912),
  canvasSubtle: Color(0xFF0E1220),
  panel: Color(0xFF141827),
  panelRaised: Color(0xFF1B2133),
  panelMuted: Color(0xFF242C42),
  panelBorder: Color(0xFF3A4665),
  accent: Color(0xFF86AEE0),
  accentMuted: Color(0xFF25375C),
  success: Color(0xFF89C19D),
  successMuted: Color(0xFF1E382A),
  warning: Color(0xFFD0AE67),
  warningMuted: Color(0xFF3B3018),
  info: Color(0xFF86AEE0),
  infoMuted: Color(0xFF25375C),
  danger: Color(0xFFE19A9A),
  dangerMuted: Color(0xFF472424),
  chatOutgoing: Color(0xFF263A61),
  chatIncoming: Color(0xFF141827),
  storyActive: Color(0xFF86AEE0),
  storyInactive: Color(0xFF3A4665),
  storyOverlay: Color(0xD9030408),
  imagePlaceholder: Color(0xFF242E4C),
  imageError: Color(0xFF2D3856),
  foreground: Color(0xFFEFF4FF),
  foregroundMuted: Color(0xFFA8B7D4),
  foregroundOnAccent: Color(0xFF05060F),
  adminExperiment: Color(0xFFA8ACD8),
  cardRadius: 24,
  buttonRadius: 20,
  inputRadius: 24,
  panelBorderWidth: 0.5,
  logoAsset: 'assets/logo_nova.png',
  navStyle: SdalNavStyle.floatingPill,
  navLabelMode: SdalNavLabelMode.never,
  navIndicator: SdalNavIndicator.accentIcon,
  navBarBackground: SdalNavBarBackground.frosted,
  headerStyle: SdalHeaderStyle.minimal,
  headerBackground: SdalHeaderBackground.frosted,
  logoPosition: SdalLogoPosition.leading,
  avatarPosition: SdalAvatarPosition.trailing,
  titleAlignment: SdalTitleAlignment.center,
  cardStyle: SdalCardStyle.glass,
  surfaceDepth: SdalSurfaceDepth.glass,
  borderStyle: SdalBorderStyle.hairline,
  backgroundPattern: SdalBackgroundPattern.radialGlow,
  feedLayout: SdalFeedLayout.singleColumn,
  listItemStyle: SdalListItemStyle.card,
  separatorStyle: SdalSeparatorStyle.spacer,
  scrollPhysics: SdalScrollPhysics.bouncing,
  tapFeedback: SdalTapFeedback.lift,
  transitionStyle: SdalTransitionStyle.blurFade,
  animationSpeed: SdalAnimationSpeed.slow,
  scrollBehavior: SdalScrollBehavior.smooth,
  avatarShape: SdalAvatarShape.roundedSquare,
  avatarBorder: SdalAvatarBorder.glowRing,
  onlineIndicator: SdalOnlineIndicator.pulse,
  memberBadgeStyle: SdalMemberBadgeStyle.none,
  metaPlacement: SdalMetaPlacement.below,
  actionsStyle: SdalActionsStyle.floating,
  statsDisplay: SdalStatsDisplay.chips,
  timestampStyle: SdalTimestampStyle.compact,
  menuStyle: SdalMenuStyle.fullscreen,
  modalBackdrop: SdalModalBackdrop.frosted,
  sheetStyle: SdalSheetStyle.none,
  loadingStyle: SdalLoadingStyle.pulse,
  emptyStateStyle: SdalEmptyStateStyle.minimal,
  imageShape: SdalImageShape.roundedLarge,
  imageOverlay: SdalImageOverlay.gradientBottom,
  placeholderStyle: SdalPlaceholderStyle.crossFade,
  headingWeight: SdalHeadingWeight.light,
  bodyLineHeight: SdalBodyLineHeight.loose,
  letterSpacing: SdalLetterSpacing.tight,
  typographyHierarchy: SdalTypographyHierarchy.display,
  spacingScale: SdalSpacingScale.airy,
  contentInset: SdalContentInset.wide,
  badgeStyle: SdalBadgeStyle.dot,
  unreadIndicator: SdalUnreadIndicator.coloredDot,
  toastPosition: SdalToastPosition.center,
  toastStyle: SdalToastStyle.pill,
  blurSigma: 20.0,
  glassOpacity: 0.08,
  glassSheetOpacity: 0.88,
  navBarHeight: 64.0,
  floatingPillBottomPad: 20.0,
  appBarHeight: 44.0,
  heroHeaderHeight: 0.0,
  contentPaddingH: 20.0,
  cardSpacing: 16.0,
  animationDurationMs: 380,
  feedImageAspect: 1.50,
);

// ---------------------------------------------------------------------------
// Prism — bento grid, modular information architecture
// ---------------------------------------------------------------------------

const _prismLight = SdalThemeTokens(
  canvas: Color(0xFFF7F7F9),
  canvasSubtle: Color(0xFFEEEEF4),
  panel: Color(0xFFFFFFFF),
  panelRaised: Color(0xFFF3F2FA),
  panelMuted: Color(0xFFE8E7F5),
  panelBorder: Color(0xFFD0CEEC),
  accent: Color(0xFF7C3AED),
  accentMuted: Color(0xFFEDE9FE),
  success: Color(0xFF1E6B48),
  successMuted: Color(0xFFD0EDE0),
  warning: Color(0xFF7A5A14),
  warningMuted: Color(0xFFF0E2C0),
  info: Color(0xFF2A5080),
  infoMuted: Color(0xFFCCDCF4),
  danger: Color(0xFF9E3030),
  dangerMuted: Color(0xFFF4D4D4),
  chatOutgoing: Color(0xFF4A1A9A),
  chatIncoming: Color(0xFFFFFFFF),
  storyActive: Color(0xFF7C3AED),
  storyInactive: Color(0xFFBBAAE0),
  storyOverlay: Color(0xB30E0820),
  imagePlaceholder: Color(0xFFE0DAFF),
  imageError: Color(0xFFD4CEF8),
  foreground: Color(0xFF0F0F14),
  foregroundMuted: Color(0xFF6B6B85),
  foregroundOnAccent: Color(0xFFFAF8FF),
  adminExperiment: Color(0xFF8050D0),
  cardRadius: 20,
  buttonRadius: 14,
  inputRadius: 16,
  panelBorderWidth: 1.0,
  logoAsset: 'assets/logo_prism.png',
  navStyle: SdalNavStyle.sideDrawer,
  navLabelMode: SdalNavLabelMode.always,
  navIndicator: SdalNavIndicator.filledPill,
  navBarBackground: SdalNavBarBackground.solid,
  headerStyle: SdalHeaderStyle.heroAvatar,
  headerBackground: SdalHeaderBackground.solid,
  logoPosition: SdalLogoPosition.hidden,
  avatarPosition: SdalAvatarPosition.headerHero,
  titleAlignment: SdalTitleAlignment.start,
  cardStyle: SdalCardStyle.flat,
  surfaceDepth: SdalSurfaceDepth.flat,
  borderStyle: SdalBorderStyle.thin,
  backgroundPattern: SdalBackgroundPattern.solid,
  feedLayout: SdalFeedLayout.twoColumnGrid,
  listItemStyle: SdalListItemStyle.inlineCard,
  separatorStyle: SdalSeparatorStyle.cardGap,
  scrollPhysics: SdalScrollPhysics.bouncing,
  tapFeedback: SdalTapFeedback.scalePress,
  transitionStyle: SdalTransitionStyle.fade,
  animationSpeed: SdalAnimationSpeed.fast,
  scrollBehavior: SdalScrollBehavior.standard,
  avatarShape: SdalAvatarShape.hexagon,
  avatarBorder: SdalAvatarBorder.gradient,
  onlineIndicator: SdalOnlineIndicator.ring,
  memberBadgeStyle: SdalMemberBadgeStyle.subtleLabel,
  metaPlacement: SdalMetaPlacement.trailing,
  actionsStyle: SdalActionsStyle.iconRow,
  statsDisplay: SdalStatsDisplay.metricCards,
  timestampStyle: SdalTimestampStyle.compact,
  menuStyle: SdalMenuStyle.drawer,
  modalBackdrop: SdalModalBackdrop.dim,
  sheetStyle: SdalSheetStyle.lineHandle,
  loadingStyle: SdalLoadingStyle.skeleton,
  emptyStateStyle: SdalEmptyStateStyle.card,
  imageShape: SdalImageShape.roundedLarge,
  imageOverlay: SdalImageOverlay.none,
  placeholderStyle: SdalPlaceholderStyle.shimmer,
  headingWeight: SdalHeadingWeight.bold,
  bodyLineHeight: SdalBodyLineHeight.normal,
  letterSpacing: SdalLetterSpacing.tight,
  typographyHierarchy: SdalTypographyHierarchy.editorial,
  spacingScale: SdalSpacingScale.normal,
  contentInset: SdalContentInset.standard,
  badgeStyle: SdalBadgeStyle.count,
  unreadIndicator: SdalUnreadIndicator.badgeCount,
  toastPosition: SdalToastPosition.bottom,
  toastStyle: SdalToastStyle.snackbar,
  blurSigma: 0.0,
  glassOpacity: 0.0,
  glassSheetOpacity: 0.50,
  navBarHeight: 0.0,
  floatingPillBottomPad: 0.0,
  appBarHeight: 88.0,
  heroHeaderHeight: 160.0,
  contentPaddingH: 16.0,
  cardSpacing: 12.0,
  animationDurationMs: 180,
  feedImageAspect: 1.0,
);

const _prismDark = SdalThemeTokens(
  canvas: Color(0xFF0F0F14),
  canvasSubtle: Color(0xFF171722),
  panel: Color(0xFF1E1E2C),
  panelRaised: Color(0xFF27273A),
  panelMuted: Color(0xFF30304A),
  panelBorder: Color(0xFF4B4B6A),
  accent: Color(0xFF9B8FD8),
  accentMuted: Color(0xFF342B58),
  success: Color(0xFF89C19D),
  successMuted: Color(0xFF1F382A),
  warning: Color(0xFFD0AF68),
  warningMuted: Color(0xFF3B3018),
  info: Color(0xFF8BBAC8),
  infoMuted: Color(0xFF1B3440),
  danger: Color(0xFFE19A9A),
  dangerMuted: Color(0xFF472424),
  chatOutgoing: Color(0xFF3C3266),
  chatIncoming: Color(0xFF1E1E2C),
  storyActive: Color(0xFF9B8FD8),
  storyInactive: Color(0xFF4B4B6A),
  storyOverlay: Color(0xD908061A),
  imagePlaceholder: Color(0xFF30304A),
  imageError: Color(0xFF3A3A55),
  foreground: Color(0xFFF2F0FF),
  foregroundMuted: Color(0xFFC0B7D8),
  foregroundOnAccent: Color(0xFF07070B),
  adminExperiment: Color(0xFFBCA4D8),
  cardRadius: 20,
  buttonRadius: 14,
  inputRadius: 16,
  panelBorderWidth: 1.0,
  logoAsset: 'assets/logo_prism.png',
  navStyle: SdalNavStyle.sideDrawer,
  navLabelMode: SdalNavLabelMode.always,
  navIndicator: SdalNavIndicator.filledPill,
  navBarBackground: SdalNavBarBackground.solid,
  headerStyle: SdalHeaderStyle.heroAvatar,
  headerBackground: SdalHeaderBackground.solid,
  logoPosition: SdalLogoPosition.hidden,
  avatarPosition: SdalAvatarPosition.headerHero,
  titleAlignment: SdalTitleAlignment.start,
  cardStyle: SdalCardStyle.flat,
  surfaceDepth: SdalSurfaceDepth.flat,
  borderStyle: SdalBorderStyle.thin,
  backgroundPattern: SdalBackgroundPattern.solid,
  feedLayout: SdalFeedLayout.twoColumnGrid,
  listItemStyle: SdalListItemStyle.inlineCard,
  separatorStyle: SdalSeparatorStyle.cardGap,
  scrollPhysics: SdalScrollPhysics.bouncing,
  tapFeedback: SdalTapFeedback.scalePress,
  transitionStyle: SdalTransitionStyle.fade,
  animationSpeed: SdalAnimationSpeed.fast,
  scrollBehavior: SdalScrollBehavior.standard,
  avatarShape: SdalAvatarShape.hexagon,
  avatarBorder: SdalAvatarBorder.gradient,
  onlineIndicator: SdalOnlineIndicator.ring,
  memberBadgeStyle: SdalMemberBadgeStyle.subtleLabel,
  metaPlacement: SdalMetaPlacement.trailing,
  actionsStyle: SdalActionsStyle.iconRow,
  statsDisplay: SdalStatsDisplay.metricCards,
  timestampStyle: SdalTimestampStyle.compact,
  menuStyle: SdalMenuStyle.drawer,
  modalBackdrop: SdalModalBackdrop.dim,
  sheetStyle: SdalSheetStyle.lineHandle,
  loadingStyle: SdalLoadingStyle.skeleton,
  emptyStateStyle: SdalEmptyStateStyle.card,
  imageShape: SdalImageShape.roundedLarge,
  imageOverlay: SdalImageOverlay.none,
  placeholderStyle: SdalPlaceholderStyle.shimmer,
  headingWeight: SdalHeadingWeight.bold,
  bodyLineHeight: SdalBodyLineHeight.normal,
  letterSpacing: SdalLetterSpacing.tight,
  typographyHierarchy: SdalTypographyHierarchy.editorial,
  spacingScale: SdalSpacingScale.normal,
  contentInset: SdalContentInset.standard,
  badgeStyle: SdalBadgeStyle.count,
  unreadIndicator: SdalUnreadIndicator.badgeCount,
  toastPosition: SdalToastPosition.bottom,
  toastStyle: SdalToastStyle.snackbar,
  blurSigma: 0.0,
  glassOpacity: 0.0,
  glassSheetOpacity: 0.50,
  navBarHeight: 0.0,
  floatingPillBottomPad: 0.0,
  appBarHeight: 88.0,
  heroHeaderHeight: 160.0,
  contentPaddingH: 16.0,
  cardSpacing: 12.0,
  animationDurationMs: 180,
  feedImageAspect: 1.0,
);

// ---------------------------------------------------------------------------
// Dusk — dark cinematic, dramatic editorial
// ---------------------------------------------------------------------------

const _duskLight = SdalThemeTokens(
  canvas: Color(0xFFFAF7F2),
  canvasSubtle: Color(0xFFF0EAE0),
  panel: Color(0xFFFFFFFF),
  panelRaised: Color(0xFFF8F3EC),
  panelMuted: Color(0xFFEDE4D8),
  panelBorder: Color(0xFFD4B880),
  accent: Color(0xFFD97706),
  accentMuted: Color(0xFFFEF3C7),
  success: Color(0xFF1E6B48),
  successMuted: Color(0xFFD0EDE0),
  warning: Color(0xFF92400E),
  warningMuted: Color(0xFFFEF3C7),
  info: Color(0xFF1E40AF),
  infoMuted: Color(0xFFDBEAFE),
  danger: Color(0xFF991B1B),
  dangerMuted: Color(0xFFFEE2E2),
  chatOutgoing: Color(0xFF78350F),
  chatIncoming: Color(0xFFFFFFFF),
  storyActive: Color(0xFFD97706),
  storyInactive: Color(0xFFD4B880),
  storyOverlay: Color(0xB3180C00),
  imagePlaceholder: Color(0xFFECDCAC),
  imageError: Color(0xFFE8D0A0),
  foreground: Color(0xFF1C1208),
  foregroundMuted: Color(0xFF6C4C1A),
  foregroundOnAccent: Color(0xFFFFFBF0),
  adminExperiment: Color(0xFF7050A0),
  cardRadius: 8,
  buttonRadius: 6,
  inputRadius: 8,
  panelBorderWidth: 0.0,
  logoAsset: 'assets/logo_dusk.png',
  navStyle: SdalNavStyle.transparentBar,
  navLabelMode: SdalNavLabelMode.never,
  navIndicator: SdalNavIndicator.underline,
  navBarBackground: SdalNavBarBackground.transparentBlur,
  headerStyle: SdalHeaderStyle.transparent,
  headerBackground: SdalHeaderBackground.gradientScrim,
  logoPosition: SdalLogoPosition.leading,
  avatarPosition: SdalAvatarPosition.leading,
  titleAlignment: SdalTitleAlignment.center,
  cardStyle: SdalCardStyle.fullBleed,
  surfaceDepth: SdalSurfaceDepth.flat,
  borderStyle: SdalBorderStyle.none,
  backgroundPattern: SdalBackgroundPattern.solid,
  feedLayout: SdalFeedLayout.cinematic,
  listItemStyle: SdalListItemStyle.fullBleedCard,
  separatorStyle: SdalSeparatorStyle.none,
  scrollPhysics: SdalScrollPhysics.snapping,
  tapFeedback: SdalTapFeedback.highlight,
  transitionStyle: SdalTransitionStyle.fade,
  animationSpeed: SdalAnimationSpeed.dramatic,
  scrollBehavior: SdalScrollBehavior.smooth,
  avatarShape: SdalAvatarShape.circle,
  avatarBorder: SdalAvatarBorder.glowRing,
  onlineIndicator: SdalOnlineIndicator.ring,
  memberBadgeStyle: SdalMemberBadgeStyle.none,
  metaPlacement: SdalMetaPlacement.overlay,
  actionsStyle: SdalActionsStyle.floating,
  statsDisplay: SdalStatsDisplay.hidden,
  timestampStyle: SdalTimestampStyle.hidden,
  menuStyle: SdalMenuStyle.centerModal,
  modalBackdrop: SdalModalBackdrop.tinted,
  sheetStyle: SdalSheetStyle.pillHandle,
  loadingStyle: SdalLoadingStyle.shimmer,
  emptyStateStyle: SdalEmptyStateStyle.minimal,
  imageShape: SdalImageShape.rectangle,
  imageOverlay: SdalImageOverlay.gradientBottom,
  placeholderStyle: SdalPlaceholderStyle.solidColor,
  headingWeight: SdalHeadingWeight.black,
  bodyLineHeight: SdalBodyLineHeight.normal,
  letterSpacing: SdalLetterSpacing.ultraWide,
  typographyHierarchy: SdalTypographyHierarchy.display,
  spacingScale: SdalSpacingScale.relaxed,
  contentInset: SdalContentInset.none,
  badgeStyle: SdalBadgeStyle.dot,
  unreadIndicator: SdalUnreadIndicator.coloredDot,
  toastPosition: SdalToastPosition.bottom,
  toastStyle: SdalToastStyle.card,
  blurSigma: 28.0,
  glassOpacity: 0.0,
  glassSheetOpacity: 0.82,
  navBarHeight: 72.0,
  floatingPillBottomPad: 0.0,
  appBarHeight: 56.0,
  heroHeaderHeight: 0.0,
  contentPaddingH: 0.0,
  cardSpacing: 4.0,
  animationDurationMs: 500,
  feedImageAspect: 0.65,
);

const _duskDark = SdalThemeTokens(
  canvas: Color(0xFF0B0907),
  canvasSubtle: Color(0xFF14110D),
  panel: Color(0xFF1A1713),
  panelRaised: Color(0xFF242018),
  panelMuted: Color(0xFF30291F),
  panelBorder: Color(0xFF4E402C),
  accent: Color(0xFFD4A456),
  accentMuted: Color(0xFF463216),
  success: Color(0xFF8AC19E),
  successMuted: Color(0xFF223A2A),
  warning: Color(0xFFD2A45B),
  warningMuted: Color(0xFF3A2A12),
  info: Color(0xFF86AEE0),
  infoMuted: Color(0xFF24365A),
  danger: Color(0xFFC77A6C),
  dangerMuted: Color(0xFF45231E),
  chatOutgoing: Color(0xFF4A351A),
  chatIncoming: Color(0xFF1A1713),
  storyActive: Color(0xFFD4A456),
  storyInactive: Color(0xFF665640),
  storyOverlay: Color(0xD9060400),
  imagePlaceholder: Color(0xFF382D20),
  imageError: Color(0xFF463728),
  foreground: Color(0xFFF7EFE6),
  foregroundMuted: Color(0xFFCBB48C),
  foregroundOnAccent: Color(0xFF0A0600),
  adminExperiment: Color(0xFFBCA0D0),
  cardRadius: 8,
  buttonRadius: 6,
  inputRadius: 8,
  panelBorderWidth: 0.0,
  logoAsset: 'assets/logo_dusk.png',
  navStyle: SdalNavStyle.transparentBar,
  navLabelMode: SdalNavLabelMode.never,
  navIndicator: SdalNavIndicator.underline,
  navBarBackground: SdalNavBarBackground.transparentBlur,
  headerStyle: SdalHeaderStyle.transparent,
  headerBackground: SdalHeaderBackground.gradientScrim,
  logoPosition: SdalLogoPosition.leading,
  avatarPosition: SdalAvatarPosition.leading,
  titleAlignment: SdalTitleAlignment.center,
  cardStyle: SdalCardStyle.fullBleed,
  surfaceDepth: SdalSurfaceDepth.flat,
  borderStyle: SdalBorderStyle.none,
  backgroundPattern: SdalBackgroundPattern.solid,
  feedLayout: SdalFeedLayout.cinematic,
  listItemStyle: SdalListItemStyle.fullBleedCard,
  separatorStyle: SdalSeparatorStyle.none,
  scrollPhysics: SdalScrollPhysics.snapping,
  tapFeedback: SdalTapFeedback.highlight,
  transitionStyle: SdalTransitionStyle.fade,
  animationSpeed: SdalAnimationSpeed.dramatic,
  scrollBehavior: SdalScrollBehavior.smooth,
  avatarShape: SdalAvatarShape.circle,
  avatarBorder: SdalAvatarBorder.glowRing,
  onlineIndicator: SdalOnlineIndicator.ring,
  memberBadgeStyle: SdalMemberBadgeStyle.none,
  metaPlacement: SdalMetaPlacement.overlay,
  actionsStyle: SdalActionsStyle.floating,
  statsDisplay: SdalStatsDisplay.hidden,
  timestampStyle: SdalTimestampStyle.hidden,
  menuStyle: SdalMenuStyle.centerModal,
  modalBackdrop: SdalModalBackdrop.tinted,
  sheetStyle: SdalSheetStyle.pillHandle,
  loadingStyle: SdalLoadingStyle.shimmer,
  emptyStateStyle: SdalEmptyStateStyle.minimal,
  imageShape: SdalImageShape.rectangle,
  imageOverlay: SdalImageOverlay.gradientBottom,
  placeholderStyle: SdalPlaceholderStyle.solidColor,
  headingWeight: SdalHeadingWeight.black,
  bodyLineHeight: SdalBodyLineHeight.normal,
  letterSpacing: SdalLetterSpacing.ultraWide,
  typographyHierarchy: SdalTypographyHierarchy.display,
  spacingScale: SdalSpacingScale.relaxed,
  contentInset: SdalContentInset.none,
  badgeStyle: SdalBadgeStyle.dot,
  unreadIndicator: SdalUnreadIndicator.coloredDot,
  toastPosition: SdalToastPosition.bottom,
  toastStyle: SdalToastStyle.card,
  blurSigma: 28.0,
  glassOpacity: 0.0,
  glassSheetOpacity: 0.82,
  navBarHeight: 72.0,
  floatingPillBottomPad: 0.0,
  appBarHeight: 56.0,
  heroHeaderHeight: 0.0,
  contentPaddingH: 0.0,
  cardSpacing: 4.0,
  animationDurationMs: 500,
  feedImageAspect: 0.65,
);

// ---------------------------------------------------------------------------
// Flux — Material You 3, dynamic & adaptive teal
// ---------------------------------------------------------------------------

const _fluxLight = SdalThemeTokens(
  canvas: Color(0xFFF8FFFE),
  canvasSubtle: Color(0xFFEEFBF8),
  panel: Color(0xFFFFFFFF),
  panelRaised: Color(0xFFEAF9F5),
  panelMuted: Color(0xFFD5F4EC),
  panelBorder: Color(0xFF99DACA),
  accent: Color(0xFF0D9488),
  accentMuted: Color(0xFFCCFBF1),
  success: Color(0xFF1E6B48),
  successMuted: Color(0xFFD0EDE0),
  warning: Color(0xFF7A5A14),
  warningMuted: Color(0xFFF0E2C0),
  info: Color(0xFF0D6E94),
  infoMuted: Color(0xFFCCE8F4),
  danger: Color(0xFF9E3430),
  dangerMuted: Color(0xFFF2D8D6),
  chatOutgoing: Color(0xFF0C5E54),
  chatIncoming: Color(0xFFFFFFFF),
  storyActive: Color(0xFF0D9488),
  storyInactive: Color(0xFF99DACA),
  storyOverlay: Color(0xB3040E0C),
  imagePlaceholder: Color(0xFFBBEDD8),
  imageError: Color(0xFFAAE0CC),
  foreground: Color(0xFF0A1512),
  foregroundMuted: Color(0xFF3D6B60),
  foregroundOnAccent: Color(0xFFF0FFFD),
  adminExperiment: Color(0xFF5850A8),
  cardRadius: 12,
  buttonRadius: 20,
  inputRadius: 12,
  panelBorderWidth: 0.0,
  logoAsset: 'assets/logo_flux.png',
  navStyle: SdalNavStyle.materialFab,
  navLabelMode: SdalNavLabelMode.selectedOnly,
  navIndicator: SdalNavIndicator.filledPill,
  navBarBackground: SdalNavBarBackground.solid,
  headerStyle: SdalHeaderStyle.collapsible,
  headerBackground: SdalHeaderBackground.solid,
  logoPosition: SdalLogoPosition.leading,
  avatarPosition: SdalAvatarPosition.trailing,
  titleAlignment: SdalTitleAlignment.start,
  cardStyle: SdalCardStyle.tonal,
  surfaceDepth: SdalSurfaceDepth.flat,
  borderStyle: SdalBorderStyle.none,
  backgroundPattern: SdalBackgroundPattern.solid,
  feedLayout: SdalFeedLayout.compact,
  listItemStyle: SdalListItemStyle.compact,
  separatorStyle: SdalSeparatorStyle.hairline,
  scrollPhysics: SdalScrollPhysics.clamped,
  tapFeedback: SdalTapFeedback.ripple,
  transitionStyle: SdalTransitionStyle.scale,
  animationSpeed: SdalAnimationSpeed.fast,
  scrollBehavior: SdalScrollBehavior.standard,
  avatarShape: SdalAvatarShape.circle,
  avatarBorder: SdalAvatarBorder.roleColor,
  onlineIndicator: SdalOnlineIndicator.dot,
  memberBadgeStyle: SdalMemberBadgeStyle.colorRing,
  metaPlacement: SdalMetaPlacement.inline,
  actionsStyle: SdalActionsStyle.pillButtons,
  statsDisplay: SdalStatsDisplay.inlineText,
  timestampStyle: SdalTimestampStyle.relative,
  menuStyle: SdalMenuStyle.expandedTab,
  modalBackdrop: SdalModalBackdrop.blur,
  sheetStyle: SdalSheetStyle.lineHandle,
  loadingStyle: SdalLoadingStyle.skeleton,
  emptyStateStyle: SdalEmptyStateStyle.inline,
  imageShape: SdalImageShape.roundedSmall,
  imageOverlay: SdalImageOverlay.none,
  placeholderStyle: SdalPlaceholderStyle.shimmer,
  headingWeight: SdalHeadingWeight.medium,
  bodyLineHeight: SdalBodyLineHeight.tight,
  letterSpacing: SdalLetterSpacing.normal,
  typographyHierarchy: SdalTypographyHierarchy.functional,
  spacingScale: SdalSpacingScale.compact,
  contentInset: SdalContentInset.standard,
  badgeStyle: SdalBadgeStyle.count,
  unreadIndicator: SdalUnreadIndicator.accentBar,
  toastPosition: SdalToastPosition.top,
  toastStyle: SdalToastStyle.pill,
  blurSigma: 8.0,
  glassOpacity: 0.0,
  glassSheetOpacity: 0.60,
  navBarHeight: 80.0,
  floatingPillBottomPad: 16.0,
  appBarHeight: 64.0,
  heroHeaderHeight: 80.0,
  contentPaddingH: 16.0,
  cardSpacing: 8.0,
  animationDurationMs: 160,
  feedImageAspect: 1.78,
);

const _fluxDark = SdalThemeTokens(
  canvas: Color(0xFF0A1311),
  canvasSubtle: Color(0xFF101D1A),
  panel: Color(0xFF182722),
  panelRaised: Color(0xFF20332C),
  panelMuted: Color(0xFF293F36),
  panelBorder: Color(0xFF426257),
  accent: Color(0xFF78BDB1),
  accentMuted: Color(0xFF223C36),
  success: Color(0xFF8AC49D),
  successMuted: Color(0xFF1E3929),
  warning: Color(0xFFD0AD66),
  warningMuted: Color(0xFF3A3018),
  info: Color(0xFF8BBAC8),
  infoMuted: Color(0xFF1B3440),
  danger: Color(0xFFE19A9A),
  dangerMuted: Color(0xFF462424),
  chatOutgoing: Color(0xFF233D35),
  chatIncoming: Color(0xFF182722),
  storyActive: Color(0xFF78BDB1),
  storyInactive: Color(0xFF426257),
  storyOverlay: Color(0xD9020A08),
  imagePlaceholder: Color(0xFF263832),
  imageError: Color(0xFF30453D),
  foreground: Color(0xFFE1F2EF),
  foregroundMuted: Color(0xFFA4C7BF),
  foregroundOnAccent: Color(0xFF040E0C),
  adminExperiment: Color(0xFFA6ACD8),
  cardRadius: 12,
  buttonRadius: 20,
  inputRadius: 12,
  panelBorderWidth: 0.0,
  logoAsset: 'assets/logo_flux.png',
  navStyle: SdalNavStyle.materialFab,
  navLabelMode: SdalNavLabelMode.selectedOnly,
  navIndicator: SdalNavIndicator.filledPill,
  navBarBackground: SdalNavBarBackground.solid,
  headerStyle: SdalHeaderStyle.collapsible,
  headerBackground: SdalHeaderBackground.solid,
  logoPosition: SdalLogoPosition.leading,
  avatarPosition: SdalAvatarPosition.trailing,
  titleAlignment: SdalTitleAlignment.start,
  cardStyle: SdalCardStyle.tonal,
  surfaceDepth: SdalSurfaceDepth.flat,
  borderStyle: SdalBorderStyle.none,
  backgroundPattern: SdalBackgroundPattern.solid,
  feedLayout: SdalFeedLayout.compact,
  listItemStyle: SdalListItemStyle.compact,
  separatorStyle: SdalSeparatorStyle.hairline,
  scrollPhysics: SdalScrollPhysics.clamped,
  tapFeedback: SdalTapFeedback.ripple,
  transitionStyle: SdalTransitionStyle.scale,
  animationSpeed: SdalAnimationSpeed.fast,
  scrollBehavior: SdalScrollBehavior.standard,
  avatarShape: SdalAvatarShape.circle,
  avatarBorder: SdalAvatarBorder.roleColor,
  onlineIndicator: SdalOnlineIndicator.dot,
  memberBadgeStyle: SdalMemberBadgeStyle.colorRing,
  metaPlacement: SdalMetaPlacement.inline,
  actionsStyle: SdalActionsStyle.pillButtons,
  statsDisplay: SdalStatsDisplay.inlineText,
  timestampStyle: SdalTimestampStyle.relative,
  menuStyle: SdalMenuStyle.expandedTab,
  modalBackdrop: SdalModalBackdrop.blur,
  sheetStyle: SdalSheetStyle.lineHandle,
  loadingStyle: SdalLoadingStyle.skeleton,
  emptyStateStyle: SdalEmptyStateStyle.inline,
  imageShape: SdalImageShape.roundedSmall,
  imageOverlay: SdalImageOverlay.none,
  placeholderStyle: SdalPlaceholderStyle.shimmer,
  headingWeight: SdalHeadingWeight.medium,
  bodyLineHeight: SdalBodyLineHeight.tight,
  letterSpacing: SdalLetterSpacing.normal,
  typographyHierarchy: SdalTypographyHierarchy.functional,
  spacingScale: SdalSpacingScale.compact,
  contentInset: SdalContentInset.standard,
  badgeStyle: SdalBadgeStyle.count,
  unreadIndicator: SdalUnreadIndicator.accentBar,
  toastPosition: SdalToastPosition.top,
  toastStyle: SdalToastStyle.pill,
  blurSigma: 8.0,
  glassOpacity: 0.0,
  glassSheetOpacity: 0.60,
  navBarHeight: 80.0,
  floatingPillBottomPad: 16.0,
  appBarHeight: 64.0,
  heroHeaderHeight: 80.0,
  contentPaddingH: 16.0,
  cardSpacing: 8.0,
  animationDurationMs: 160,
  feedImageAspect: 1.78,
);
