import crypto from 'node:crypto';
import fs from 'node:fs';

const FCM_SCOPE = 'https://www.googleapis.com/auth/firebase.messaging';
const FCM_TOKEN_URL = 'https://oauth2.googleapis.com/token';
const DEFAULT_PUSH_TITLE = 'SDAL Bildirim';
const PUSH_DELIVERY_STATUS_SET = new Set(['sent', 'skipped', 'failed']);
const PUSH_PLATFORM_SET = new Set(['android', 'ios']);

function toDbBooleanParam(dbDriver, value) {
  return dbDriver === 'postgres' ? !!value : (value ? 1 : 0);
}

function isDbBooleanTrue(value) {
  return value === true || Number(value || 0) === 1;
}

function sanitizeText(value, fallback = '') {
  const text = String(value || '').trim();
  return text || fallback;
}

function safeJsonParse(value, fallback = null) {
  try {
    return JSON.parse(String(value || ''));
  } catch {
    return fallback;
  }
}

function base64UrlEncode(value) {
  return Buffer.from(value).toString('base64url');
}

export function createNotificationPushRuntime({
  dbDriver,
  sqlRun,
  sqlGet,
  sqlGetAsync,
  sqlAllAsync,
  sqlRunAsync,
  getNotificationCategory,
  buildNotificationTarget,
  writeAppLog,
  sanitizePlainUserText
}) {
  let cachedFirebaseToken = {
    token: '',
    expiresAt: 0,
    pendingPromise: null
  };

  function ensureNotificationPushSettingsTable() {
    sqlRun(`
      CREATE TABLE IF NOT EXISTS notification_push_settings (
        id INTEGER PRIMARY KEY,
        push_enabled ${dbDriver === 'postgres' ? 'BOOLEAN' : 'INTEGER'} NOT NULL DEFAULT ${dbDriver === 'postgres' ? 'FALSE' : '0'},
        updated_at TEXT NOT NULL
      )
    `);
    const now = new Date().toISOString();
    if (dbDriver === 'postgres') {
      sqlRun(
        `INSERT INTO notification_push_settings (id, push_enabled, updated_at)
         VALUES (1, FALSE, ?)
         ON CONFLICT (id) DO NOTHING`,
        [now]
      );
    } else {
      sqlRun(
        `INSERT INTO notification_push_settings (id, push_enabled, updated_at)
         VALUES (1, 0, ?)
         ON CONFLICT(id) DO NOTHING`,
        [now]
      );
    }
  }

  function ensureNotificationPushDevicesTable() {
    sqlRun(`
      CREATE TABLE IF NOT EXISTS notification_push_devices (
        id ${dbDriver === 'postgres' ? 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' : 'INTEGER PRIMARY KEY AUTOINCREMENT'},
        user_id INTEGER NOT NULL,
        installation_id TEXT NOT NULL,
        platform TEXT NOT NULL,
        push_token TEXT NOT NULL,
        locale TEXT,
        app_version TEXT,
        enabled ${dbDriver === 'postgres' ? 'BOOLEAN' : 'INTEGER'} NOT NULL DEFAULT ${dbDriver === 'postgres' ? 'TRUE' : '1'},
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        last_seen_at TEXT NOT NULL
      )
    `);
    sqlRun('CREATE UNIQUE INDEX IF NOT EXISTS idx_notification_push_devices_installation ON notification_push_devices (installation_id)');
    sqlRun('CREATE UNIQUE INDEX IF NOT EXISTS idx_notification_push_devices_token ON notification_push_devices (push_token)');
    sqlRun('CREATE INDEX IF NOT EXISTS idx_notification_push_devices_user_enabled ON notification_push_devices (user_id, enabled, updated_at DESC)');
  }

  function ensureNotificationPushDeliveryAuditTable() {
    sqlRun(`
      CREATE TABLE IF NOT EXISTS notification_push_delivery_audit (
        id ${dbDriver === 'postgres' ? 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' : 'INTEGER PRIMARY KEY AUTOINCREMENT'},
        notification_id INTEGER,
        user_id INTEGER,
        device_id INTEGER,
        platform TEXT,
        notification_type TEXT,
        delivery_status TEXT NOT NULL,
        skip_reason TEXT,
        error_message TEXT,
        created_at TEXT NOT NULL
      )
    `);
    sqlRun('CREATE INDEX IF NOT EXISTS idx_notification_push_delivery_created ON notification_push_delivery_audit (created_at DESC)');
    sqlRun('CREATE INDEX IF NOT EXISTS idx_notification_push_delivery_status ON notification_push_delivery_audit (delivery_status, created_at DESC)');
    sqlRun('CREATE INDEX IF NOT EXISTS idx_notification_push_delivery_notification ON notification_push_delivery_audit (notification_id, created_at DESC)');
  }

  async function readPushSettings() {
    ensureNotificationPushSettingsTable();
    const execGet = sqlGetAsync || ((...args) => Promise.resolve(sqlGet(...args)));
    const row = await execGet('SELECT push_enabled, updated_at FROM notification_push_settings WHERE id = 1');
    return {
      enabled: isDbBooleanTrue(row?.push_enabled),
      updated_at: row?.updated_at || null,
      firebase_configured: isFirebaseConfigured(),
      mock_mode: isMockMode()
    };
  }

  async function updatePushSettings({ enabled }) {
    ensureNotificationPushSettingsTable();
    const execRun = sqlRunAsync || ((...args) => Promise.resolve(sqlRun(...args)));
    const now = new Date().toISOString();
    await execRun(
      'UPDATE notification_push_settings SET push_enabled = ?, updated_at = ? WHERE id = 1',
      [toDbBooleanParam(dbDriver, enabled), now]
    );
    return readPushSettings();
  }

  function isMockMode() {
    return String(process.env.FCM_MOCK_MODE || '').trim().toLowerCase() === 'true';
  }

  function readFirebaseServiceAccount() {
    const inlineJson = String(process.env.FCM_SERVICE_ACCOUNT_JSON || '').trim();
    const filePath = String(process.env.FCM_SERVICE_ACCOUNT_FILE || '').trim();
    let raw = null;
    try {
      raw = inlineJson
        ? safeJsonParse(inlineJson, null)
        : filePath
          ? safeJsonParse(fs.readFileSync(filePath, 'utf-8'), null)
          : null;
    } catch {
      raw = null;
    }
    if (!raw || typeof raw !== 'object') return null;
    return {
      project_id: sanitizeText(process.env.FCM_PROJECT_ID || raw.project_id),
      client_email: sanitizeText(raw.client_email),
      private_key: sanitizeText(String(raw.private_key || '').replace(/\\n/g, '\n'))
    };
  }

  function isFirebaseConfigured() {
    if (isMockMode()) return true;
    const serviceAccount = readFirebaseServiceAccount();
    return Boolean(
      serviceAccount
      && serviceAccount.project_id
      && serviceAccount.client_email
      && serviceAccount.private_key
    );
  }

  async function recordPushDeliveryAudit({
    notificationId = null,
    userId = null,
    deviceId = null,
    platform = '',
    notificationType = '',
    deliveryStatus = '',
    skipReason = '',
    errorMessage = ''
  } = {}) {
    ensureNotificationPushDeliveryAuditTable();
    const execRun = sqlRunAsync || ((...args) => Promise.resolve(sqlRun(...args)));
    const normalizedStatus = sanitizeText(deliveryStatus).toLowerCase();
    await execRun(
      `INSERT INTO notification_push_delivery_audit
         (notification_id, user_id, device_id, platform, notification_type, delivery_status, skip_reason, error_message, created_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        Number(notificationId || 0) || null,
        Number(userId || 0) || null,
        Number(deviceId || 0) || null,
        sanitizePlainUserText(platform, 16) || null,
        sanitizePlainUserText(notificationType, 120) || null,
        PUSH_DELIVERY_STATUS_SET.has(normalizedStatus) ? normalizedStatus : 'failed',
        sanitizePlainUserText(skipReason, 120) || null,
        sanitizePlainUserText(errorMessage, 500) || null,
        new Date().toISOString()
      ]
    );
  }

  async function registerPushDevice({
    userId,
    installationId,
    platform,
    pushToken,
    locale = '',
    appVersion = ''
  }) {
    ensureNotificationPushDevicesTable();
    const execRun = sqlRunAsync || ((...args) => Promise.resolve(sqlRun(...args)));
    const safeUserId = Number(userId || 0);
    const normalizedInstallationId = sanitizeText(installationId);
    const normalizedToken = sanitizeText(pushToken);
    const normalizedPlatform = sanitizeText(platform).toLowerCase();
    if (!safeUserId || !normalizedInstallationId || !normalizedToken || !PUSH_PLATFORM_SET.has(normalizedPlatform)) {
      return false;
    }
    const now = new Date().toISOString();
    await execRun(
      'DELETE FROM notification_push_devices WHERE installation_id = ? OR push_token = ?',
      [normalizedInstallationId, normalizedToken]
    );
    await execRun(
      `INSERT INTO notification_push_devices
         (user_id, installation_id, platform, push_token, locale, app_version, enabled, created_at, updated_at, last_seen_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        safeUserId,
        normalizedInstallationId,
        normalizedPlatform,
        normalizedToken,
        sanitizePlainUserText(locale, 32) || null,
        sanitizePlainUserText(appVersion, 32) || null,
        toDbBooleanParam(dbDriver, true),
        now,
        now,
        now
      ]
    );
    return true;
  }

  async function unregisterPushDevice({
    userId,
    installationId = '',
    pushToken = ''
  }) {
    ensureNotificationPushDevicesTable();
    const execRun = sqlRunAsync || ((...args) => Promise.resolve(sqlRun(...args)));
    const normalizedInstallationId = sanitizeText(installationId);
    const normalizedToken = sanitizeText(pushToken);
    const safeUserId = Number(userId || 0);
    if (!normalizedInstallationId && !normalizedToken) return false;
    const whereParts = ['user_id = ?'];
    const params = [safeUserId];
    if (normalizedInstallationId) {
      whereParts.push('installation_id = ?');
      params.push(normalizedInstallationId);
    }
    if (normalizedToken) {
      whereParts.push('push_token = ?');
      params.push(normalizedToken);
    }
    await execRun(
      `DELETE FROM notification_push_devices WHERE ${whereParts.join(' AND ')}`,
      params
    );
    return true;
  }

  async function buildPushAdminSummary(windowDays = 30) {
    ensureNotificationPushDevicesTable();
    ensureNotificationPushDeliveryAuditTable();
    ensureNotificationPushSettingsTable();
    const execAll = sqlAllAsync || ((...args) => Promise.resolve([]));
    const execGet = sqlGetAsync || ((...args) => Promise.resolve(sqlGet(...args)));
    const sinceIso = new Date(Date.now() - (Math.max(Number(windowDays || 30), 1) * 24 * 60 * 60 * 1000)).toISOString();
    const [settings, deviceCountRow, userCountRow, platformRows, deliveryRows] = await Promise.all([
      readPushSettings(),
      execGet('SELECT COUNT(*) AS cnt FROM notification_push_devices WHERE enabled = ?', [toDbBooleanParam(dbDriver, true)]),
      execGet('SELECT COUNT(DISTINCT user_id) AS cnt FROM notification_push_devices WHERE enabled = ?', [toDbBooleanParam(dbDriver, true)]),
      execAll(
        `SELECT platform, COUNT(*) AS cnt
         FROM notification_push_devices
         WHERE enabled = ?
         GROUP BY platform
         ORDER BY cnt DESC, platform ASC`,
        [toDbBooleanParam(dbDriver, true)]
      ),
      execAll(
        `SELECT delivery_status, COUNT(*) AS cnt
         FROM notification_push_delivery_audit
         WHERE created_at >= ?
         GROUP BY delivery_status
         ORDER BY delivery_status ASC`,
        [sinceIso]
      )
    ]);
    const deliverySummary = { sent: 0, skipped: 0, failed: 0 };
    for (const row of deliveryRows || []) {
      const status = sanitizeText(row?.delivery_status).toLowerCase();
      if (PUSH_DELIVERY_STATUS_SET.has(status)) {
        deliverySummary[status] = Number(row?.cnt || 0);
      }
    }
    return {
      ...settings,
      registered_devices: Number(deviceCountRow?.cnt || 0),
      registered_users: Number(userCountRow?.cnt || 0),
      platforms: (platformRows || []).map((row) => ({
        platform: sanitizeText(row?.platform).toLowerCase(),
        count: Number(row?.cnt || 0)
      })),
      delivery_summary: deliverySummary,
      recent_deliveries: await readRecentPushDeliveries({ limit: 10 })
    };
  }

  async function readRecentPushDeliveries({ limit = 25, status = '' } = {}) {
    ensureNotificationPushDeliveryAuditTable();
    const execAll = sqlAllAsync || ((...args) => Promise.resolve([]));
    const safeLimit = Math.min(Math.max(Number(limit || 25), 1), 100);
    const normalizedStatus = sanitizeText(status).toLowerCase();
    const params = [];
    const whereParts = [];
    if (PUSH_DELIVERY_STATUS_SET.has(normalizedStatus)) {
      whereParts.push('pd.delivery_status = ?');
      params.push(normalizedStatus);
    }
    params.push(safeLimit);
    const whereSql = whereParts.length ? `WHERE ${whereParts.join(' AND ')}` : '';
    const rows = await execAll(
      `SELECT pd.id,
              pd.notification_id,
              pd.user_id,
              pd.device_id,
              pd.platform,
              pd.notification_type,
              pd.delivery_status,
              pd.skip_reason,
              pd.error_message,
              pd.created_at,
              n.type AS notification_row_type,
              n.message AS notification_message
       FROM notification_push_delivery_audit pd
       LEFT JOIN notifications n ON n.id = pd.notification_id
       ${whereSql}
       ORDER BY pd.created_at DESC, pd.id DESC
       LIMIT ?`,
      params
    );
    return (rows || []).map((row) => ({
      id: Number(row?.id || 0),
      notification_id: Number(row?.notification_id || 0) || null,
      user_id: Number(row?.user_id || 0) || null,
      device_id: Number(row?.device_id || 0) || null,
      platform: sanitizeText(row?.platform).toLowerCase() || null,
      notification_type: sanitizeText(row?.notification_type || row?.notification_row_type).toLowerCase() || null,
      delivery_status: sanitizeText(row?.delivery_status).toLowerCase(),
      skip_reason: sanitizeText(row?.skip_reason) || null,
      error_message: sanitizeText(row?.error_message) || null,
      notification_message: sanitizePlainUserText(row?.notification_message, 240) || null,
      created_at: sanitizeText(row?.created_at) || null
    }));
  }

  async function getFirebaseAccessToken() {
    if (isMockMode()) return 'mock-access-token';
    const now = Date.now();
    if (cachedFirebaseToken.token && cachedFirebaseToken.expiresAt - 60_000 > now) {
      return cachedFirebaseToken.token;
    }
    if (cachedFirebaseToken.pendingPromise) {
      return cachedFirebaseToken.pendingPromise;
    }
    const serviceAccount = readFirebaseServiceAccount();
    if (!serviceAccount) {
      throw new Error('fcm_service_account_missing');
    }
    cachedFirebaseToken.pendingPromise = (async () => {
      const issuedAt = Math.floor(Date.now() / 1000);
      const expiresAt = issuedAt + 3600;
      const header = base64UrlEncode(JSON.stringify({ alg: 'RS256', typ: 'JWT' }));
      const payload = base64UrlEncode(JSON.stringify({
        iss: serviceAccount.client_email,
        scope: FCM_SCOPE,
        aud: FCM_TOKEN_URL,
        iat: issuedAt,
        exp: expiresAt
      }));
      const signer = crypto.createSign('RSA-SHA256');
      signer.update(`${header}.${payload}`);
      signer.end();
      const signature = signer.sign(serviceAccount.private_key, 'base64url');
      const assertion = `${header}.${payload}.${signature}`;
      const response = await fetch(FCM_TOKEN_URL, {
        method: 'POST',
        headers: {
          'content-type': 'application/x-www-form-urlencoded'
        },
        body: new URLSearchParams({
          grant_type: 'urn:ietf:params:oauth:grant-type:jwt-bearer',
          assertion
        })
      });
      const payloadText = await response.text();
      const payloadJson = safeJsonParse(payloadText, {}) || {};
      if (!response.ok) {
        throw new Error(
          sanitizeText(payloadJson?.error_description || payloadJson?.error || payloadText, 'fcm_token_request_failed')
        );
      }
      const accessToken = sanitizeText(payloadJson.access_token);
      if (!accessToken) {
        throw new Error('fcm_access_token_missing');
      }
      const expiresInSeconds = Math.max(Number(payloadJson.expires_in || 3600), 60);
      cachedFirebaseToken = {
        token: accessToken,
        expiresAt: Date.now() + (expiresInSeconds * 1000),
        pendingPromise: null
      };
      return accessToken;
    })();
    try {
      return await cachedFirebaseToken.pendingPromise;
    } finally {
      cachedFirebaseToken.pendingPromise = null;
    }
  }

  function resolvePushTitle(type) {
    const category = sanitizeText(getNotificationCategory(type)).toLowerCase();
    if (category === 'events') return 'SDAL Etkinlik';
    if (category === 'networking') return 'SDAL Ağ Merkezi';
    if (category === 'groups') return 'SDAL Grup';
    if (category === 'jobs') return 'SDAL İş İlanı';
    return DEFAULT_PUSH_TITLE;
  }

  async function sendPushMessageToDevice(device, payload) {
    if (isMockMode()) {
      return { ok: true };
    }
    const serviceAccount = readFirebaseServiceAccount();
    const accessToken = await getFirebaseAccessToken();
    const endpoint = `https://fcm.googleapis.com/v1/projects/${serviceAccount.project_id}/messages:send`;
    const response = await fetch(endpoint, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${accessToken}`,
        'content-type': 'application/json'
      },
      body: JSON.stringify({
        message: {
          token: device.push_token,
          notification: {
            title: payload.title,
            body: payload.body
          },
          data: payload.data,
          android: {
            priority: 'high',
            notification: {
              channel_id: 'sdal_notifications'
            }
          },
          apns: {
            headers: {
              'apns-priority': '10'
            },
            payload: {
              aps: {
                sound: 'default'
              }
            }
          }
        }
      })
    });
    const text = await response.text();
    const json = safeJsonParse(text, {}) || {};
    if (response.ok) {
      return { ok: true };
    }
    const errorCode = sanitizeText(json?.error?.details?.[0]?.errorCode || json?.error?.status);
    const errorMessage = sanitizeText(json?.error?.message || text, `FCM ${response.status}`);
    return {
      ok: false,
      errorMessage,
      invalidToken: errorCode === 'UNREGISTERED' || errorMessage.toLowerCase().includes('unregistered')
    };
  }

  async function removePushDeviceById(deviceId) {
    ensureNotificationPushDevicesTable();
    const execRun = sqlRunAsync || ((...args) => Promise.resolve(sqlRun(...args)));
    await execRun('DELETE FROM notification_push_devices WHERE id = ?', [Number(deviceId || 0)]);
  }

  async function dispatchPushNotification({
    notificationId,
    userId,
    notificationType,
    message,
    sourceUserId = null,
    entityId = null
  }) {
    ensureNotificationPushDevicesTable();
    const settings = await readPushSettings();
    if (!settings.enabled) {
      await recordPushDeliveryAudit({
        notificationId,
        userId,
        notificationType,
        deliveryStatus: 'skipped',
        skipReason: 'push_disabled'
      });
      return { ok: false, reason: 'push_disabled' };
    }
    if (!settings.firebase_configured) {
      await recordPushDeliveryAudit({
        notificationId,
        userId,
        notificationType,
        deliveryStatus: 'skipped',
        skipReason: 'firebase_not_configured'
      });
      return { ok: false, reason: 'firebase_not_configured' };
    }
    const execAll = sqlAllAsync || ((...args) => Promise.resolve([]));
    const devices = await execAll(
      `SELECT id, push_token, platform
       FROM notification_push_devices
       WHERE user_id = ? AND enabled = ?
       ORDER BY updated_at DESC`,
      [Number(userId || 0), toDbBooleanParam(dbDriver, true)]
    );
    if (!Array.isArray(devices) || devices.length === 0) {
      await recordPushDeliveryAudit({
        notificationId,
        userId,
        notificationType,
        deliveryStatus: 'skipped',
        skipReason: 'no_registered_device'
      });
      return { ok: false, reason: 'no_registered_device' };
    }

    const target = await buildNotificationTarget({
      id: Number(notificationId || 0),
      type: notificationType,
      source_user_id: Number(sourceUserId || 0) || null,
      entity_id: Number(entityId || 0) || null
    });
    const payload = {
      title: resolvePushTitle(notificationType),
      body: sanitizeText(message, DEFAULT_PUSH_TITLE),
      data: {
        notificationId: String(Number(notificationId || 0) || 0),
        type: sanitizeText(notificationType).toLowerCase(),
        route: sanitizeText(target?.route),
        href: sanitizeText(target?.href),
        category: sanitizeText(getNotificationCategory(notificationType)).toLowerCase()
      }
    };

    for (const device of devices) {
      try {
        const result = await sendPushMessageToDevice(device, payload);
        if (result.ok) {
          await recordPushDeliveryAudit({
            notificationId,
            userId,
            deviceId: device.id,
            platform: device.platform,
            notificationType,
            deliveryStatus: 'sent'
          });
          continue;
        }
        if (result.invalidToken) {
          await removePushDeviceById(device.id);
        }
        await recordPushDeliveryAudit({
          notificationId,
          userId,
          deviceId: device.id,
          platform: device.platform,
          notificationType,
          deliveryStatus: 'failed',
          errorMessage: result.errorMessage || 'push_delivery_failed'
        });
      } catch (err) {
        await recordPushDeliveryAudit({
          notificationId,
          userId,
          deviceId: device.id,
          platform: device.platform,
          notificationType,
          deliveryStatus: 'failed',
          errorMessage: err?.message || 'push_delivery_failed'
        });
      }
    }

    writeAppLog('info', 'notification_push_dispatch_complete', {
      notificationId: Number(notificationId || 0) || null,
      userId: Number(userId || 0) || null,
      notificationType: sanitizeText(notificationType).toLowerCase(),
      deviceCount: devices.length,
      mockMode: isMockMode()
    });
    return { ok: true, deviceCount: devices.length };
  }

  return {
    ensureNotificationPushSettingsTable,
    ensureNotificationPushDevicesTable,
    ensureNotificationPushDeliveryAuditTable,
    readPushSettings,
    updatePushSettings,
    registerPushDevice,
    unregisterPushDevice,
    buildPushAdminSummary,
    readRecentPushDeliveries,
    dispatchPushNotification
  };
}
