BEGIN;

CREATE TABLE IF NOT EXISTS schema_migrations (
  name TEXT PRIMARY KEY,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT,
  first_name TEXT,
  last_name TEXT,
  activation_token TEXT,
  email TEXT,
  is_active BOOLEAN NOT NULL DEFAULT FALSE,
  is_banned BOOLEAN NOT NULL DEFAULT FALSE,
  is_profile_initialized BOOLEAN NOT NULL DEFAULT FALSE,
  website_url TEXT,
  signature TEXT,
  profession TEXT,
  city TEXT,
  is_email_hidden BOOLEAN NOT NULL DEFAULT FALSE,
  profile_view_count INTEGER NOT NULL DEFAULT 0,
  homepage_page_id BIGINT,
  graduation_year INTEGER,
  university_name TEXT,
  birth_day SMALLINT,
  birth_month SMALLINT,
  birth_year SMALLINT,
  last_activity_date DATE,
  last_activity_time TEXT,
  is_online BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_seen_at TIMESTAMPTZ,
  legacy_admin_flag BOOLEAN NOT NULL DEFAULT FALSE,
  last_ip TEXT,
  avatar_path TEXT,
  is_album_admin BOOLEAN NOT NULL DEFAULT FALSE,
  quick_access_ids_json TEXT,
  legacy_status_last_activity_at TIMESTAMPTZ,
  legacy_status_is_online BOOLEAN NOT NULL DEFAULT FALSE,
  previous_last_seen_at TIMESTAMPTZ,
  role TEXT NOT NULL DEFAULT 'user',
  is_verified BOOLEAN NOT NULL DEFAULT FALSE,
  verification_status TEXT NOT NULL DEFAULT 'pending',
  privacy_consent_at TIMESTAMPTZ,
  directory_consent_at TIMESTAMPTZ,
  company_name TEXT,
  job_title TEXT,
  expertise TEXT,
  linkedin_url TEXT,
  university_department TEXT,
  is_mentor_opted_in BOOLEAN NOT NULL DEFAULT FALSE,
  mentor_topics TEXT,
  oauth_provider TEXT,
  oauth_subject TEXT,
  oauth_email_verified BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT users_role_check CHECK (role IN ('user', 'mod', 'admin', 'root'))
);

CREATE TABLE IF NOT EXISTS oauth_identities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  provider TEXT NOT NULL,
  provider_subject TEXT NOT NULL,
  email TEXT,
  profile_json JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (provider, provider_subject),
  UNIQUE (user_id, provider)
);

CREATE TABLE IF NOT EXISTS site_settings (
  id INTEGER PRIMARY KEY,
  site_open BOOLEAN NOT NULL DEFAULT TRUE,
  maintenance_message TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT site_settings_singleton_id CHECK (id = 1)
);

CREATE TABLE IF NOT EXISTS module_settings (
  module_key TEXT PRIMARY KEY,
  is_open BOOLEAN NOT NULL DEFAULT TRUE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS media_settings (
  id INTEGER PRIMARY KEY,
  storage_provider TEXT NOT NULL DEFAULT 'local',
  local_base_path TEXT,
  thumb_width INTEGER NOT NULL DEFAULT 300,
  feed_width INTEGER NOT NULL DEFAULT 1200,
  full_width INTEGER NOT NULL DEFAULT 2000,
  webp_quality INTEGER NOT NULL DEFAULT 82,
  max_upload_bytes INTEGER NOT NULL DEFAULT 10485760,
  avif_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT media_settings_singleton_id CHECK (id = 1)
);

CREATE TABLE IF NOT EXISTS engagement_variants (
  variant TEXT PRIMARY KEY,
  name TEXT,
  description TEXT,
  traffic_pct INTEGER NOT NULL DEFAULT 0,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  params_json JSONB,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS groups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  cover_image_url TEXT,
  owner_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  visibility TEXT NOT NULL DEFAULT 'public',
  show_contact_hint BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT groups_visibility_check CHECK (visibility IN ('public', 'private', 'hidden'))
);

CREATE TABLE IF NOT EXISTS support_request_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_key TEXT NOT NULL UNIQUE,
  label TEXT NOT NULL,
  description TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS email_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT,
  value TEXT,
  description TEXT
);

CREATE TABLE IF NOT EXISTS email_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  subject TEXT NOT NULL,
  body_html TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS board_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT
);

CREATE TABLE IF NOT EXISTS cms_pages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  slug TEXT,
  view_count INTEGER NOT NULL DEFAULT 0,
  last_viewed_at TIMESTAMPTZ,
  last_editor_username TEXT,
  parent_page_id BIGINT REFERENCES cms_pages(id) ON DELETE SET NULL,
  is_visible_in_menu BOOLEAN NOT NULL DEFAULT TRUE,
  is_redirect BOOLEAN NOT NULL DEFAULT FALSE,
  body_html TEXT,
  layout_option INTEGER,
  image_url TEXT,
  last_editor_ip TEXT
);

CREATE TABLE IF NOT EXISTS album_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ,
  last_upload_at TIMESTAMPTZ,
  last_uploaded_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS media_assets (
  id TEXT PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  entity_type TEXT,
  entity_id BIGINT,
  provider TEXT,
  thumb_path TEXT,
  feed_path TEXT,
  full_path TEXT,
  width INTEGER,
  height INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  content TEXT,
  image_url TEXT,
  media_asset_id TEXT REFERENCES media_assets(id) ON DELETE SET NULL,
  group_id BIGINT REFERENCES groups(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS post_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  author_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  body TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS post_reactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  reaction_type TEXT NOT NULL DEFAULT 'like',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (post_id, user_id, reaction_type)
);

CREATE TABLE IF NOT EXISTS user_follows (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  follower_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  following_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (follower_id, following_id),
  CONSTRAINT user_follows_not_self CHECK (follower_id <> following_id)
);

CREATE TABLE IF NOT EXISTS stories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  image_url TEXT,
  media_asset_id TEXT REFERENCES media_assets(id) ON DELETE SET NULL,
  caption TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS story_views (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  story_id BIGINT NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (story_id, user_id)
);

CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  source_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  entity_id BIGINT,
  message TEXT,
  read_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS conversations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  participant_a_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  participant_b_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  last_message_at TIMESTAMPTZ,
  CONSTRAINT conversations_distinct_participants CHECK (
    participant_a_id IS NULL
    OR participant_b_id IS NULL
    OR participant_a_id <> participant_b_id
  ),
  UNIQUE (participant_a_id, participant_b_id)
);

CREATE TABLE IF NOT EXISTS conversation_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role TEXT NOT NULL DEFAULT 'member',
  joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_read_at TIMESTAMPTZ,
  UNIQUE (conversation_id, user_id)
);

CREATE TABLE IF NOT EXISTS conversation_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  recipient_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  body TEXT NOT NULL,
  client_written_at TIMESTAMPTZ,
  server_received_at TIMESTAMPTZ,
  delivered_at TIMESTAMPTZ,
  read_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_by_sender BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_by_recipient BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS live_chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  body TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  location TEXT,
  starts_at TIMESTAMPTZ,
  ends_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  approved BOOLEAN NOT NULL DEFAULT TRUE,
  approved_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  approved_at TIMESTAMPTZ,
  image_url TEXT,
  show_response_counts BOOLEAN NOT NULL DEFAULT TRUE,
  show_attendee_names BOOLEAN NOT NULL DEFAULT FALSE,
  show_decliner_names BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS event_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  comment_body TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS event_responses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  response TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  UNIQUE (event_id, user_id)
);

CREATE TABLE IF NOT EXISTS announcements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  approved BOOLEAN NOT NULL DEFAULT TRUE,
  approved_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  approved_at TIMESTAMPTZ,
  image_url TEXT
);

CREATE TABLE IF NOT EXISTS jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poster_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  company TEXT,
  title TEXT NOT NULL,
  description TEXT,
  location TEXT,
  job_type TEXT,
  link TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS group_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id BIGINT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role TEXT NOT NULL DEFAULT 'member',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (group_id, user_id)
);

CREATE TABLE IF NOT EXISTS group_join_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id BIGINT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  reviewed_at TIMESTAMPTZ,
  reviewed_by BIGINT REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS group_invites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id BIGINT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  invited_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  invited_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  status TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  responded_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS group_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id BIGINT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  location TEXT,
  starts_at TIMESTAMPTZ,
  ends_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS group_announcements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id BIGINT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS direct_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  recipient_visible BOOLEAN NOT NULL DEFAULT TRUE,
  subject TEXT,
  body_html TEXT,
  is_unread BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  sender_visible BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS board_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  body_html TEXT,
  category_id BIGINT REFERENCES board_categories(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS album_photos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT REFERENCES album_categories(id) ON DELETE SET NULL,
  file_name TEXT NOT NULL,
  title TEXT,
  description TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  uploaded_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ,
  view_count INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS album_photo_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  photo_id BIGINT NOT NULL REFERENCES album_photos(id) ON DELETE CASCADE,
  author_username TEXT,
  comment_body TEXT,
  created_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS blocked_terms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  term TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS shoutbox_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT,
  message_body TEXT,
  created_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS snake_scores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT,
  score INTEGER NOT NULL,
  created_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS tetris_scores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT,
  score INTEGER NOT NULL,
  level INTEGER,
  lines INTEGER,
  created_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS tournament_teams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_name TEXT,
  team_category_id INTEGER,
  team_phone TEXT,
  captain_name TEXT,
  captain_graduation_year TEXT,
  player1_name TEXT,
  player1_graduation_year TEXT,
  player2_name TEXT,
  player2_graduation_year TEXT,
  player3_name TEXT,
  player3_graduation_year TEXT,
  player4_name TEXT,
  player4_graduation_year TEXT,
  created_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS identity_verification_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status TEXT NOT NULL,
  proof_path TEXT,
  proof_media_asset_id TEXT REFERENCES media_assets(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  reviewed_at TIMESTAMPTZ,
  reviewer_id BIGINT REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS support_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  category_key TEXT REFERENCES support_request_categories(category_key) ON DELETE SET NULL,
  payload_json JSONB,
  status TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  reviewed_at TIMESTAMPTZ,
  reviewer_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  resolution_note TEXT
);

CREATE TABLE IF NOT EXISTS email_change_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  current_email TEXT,
  new_email TEXT,
  token TEXT,
  status TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ,
  verified_at TIMESTAMPTZ,
  ip TEXT,
  user_agent TEXT
);

CREATE TABLE IF NOT EXISTS moderation_scopes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  scope_type TEXT NOT NULL,
  scope_value TEXT NOT NULL,
  graduation_year INTEGER,
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, scope_type, scope_value)
);

CREATE TABLE IF NOT EXISTS moderation_permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  permission_key TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  UNIQUE (user_id, permission_key)
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  target_type TEXT,
  target_id TEXT,
  metadata JSONB,
  ip TEXT,
  user_agent TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS engagement_variant_assignments (
  user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  variant TEXT NOT NULL REFERENCES engagement_variants(variant) ON DELETE CASCADE,
  assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_engagement_scores (
  user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  ab_variant TEXT,
  score DOUBLE PRECISION,
  raw_score DOUBLE PRECISION,
  creator_score DOUBLE PRECISION,
  engagement_received_score DOUBLE PRECISION,
  community_score DOUBLE PRECISION,
  network_score DOUBLE PRECISION,
  quality_score DOUBLE PRECISION,
  penalty_score DOUBLE PRECISION,
  posts_30d INTEGER,
  posts_7d INTEGER,
  likes_received_30d INTEGER,
  comments_received_30d INTEGER,
  likes_given_30d INTEGER,
  comments_given_30d INTEGER,
  followers_count INTEGER,
  following_count INTEGER,
  follows_gained_30d INTEGER,
  follows_given_30d INTEGER,
  stories_30d INTEGER,
  story_views_received_30d INTEGER,
  chat_messages_30d INTEGER,
  last_activity_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS game_scores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_key TEXT NOT NULL,
  name TEXT NOT NULL,
  score INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION create_index_if_columns_exist(
  p_index_name TEXT,
  p_table_name TEXT,
  p_index_expr TEXT,
  p_required_columns TEXT[]
) RETURNS VOID AS $$
DECLARE
  missing_count INTEGER;
BEGIN
  IF to_regclass(format('public.%I', p_table_name)) IS NULL THEN
    RETURN;
  END IF;

  SELECT COUNT(*)
  INTO missing_count
  FROM unnest(p_required_columns) AS required_col
  WHERE NOT EXISTS (
    SELECT 1
    FROM information_schema.columns c
    WHERE c.table_schema = 'public'
      AND c.table_name = p_table_name
      AND c.column_name = required_col
  );

  IF missing_count = 0 THEN
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I %s', p_index_name, p_table_name, p_index_expr);
  END IF;
END;
$$ LANGUAGE plpgsql;

SELECT create_index_if_columns_exist('idx_users_username', 'users', '(username)', ARRAY['username']);
SELECT create_index_if_columns_exist('idx_users_email', 'users', '(email)', ARRAY['email']);
SELECT create_index_if_columns_exist('idx_users_role', 'users', '(role)', ARRAY['role']);
SELECT create_index_if_columns_exist('idx_users_graduation_year', 'users', '(graduation_year)', ARRAY['graduation_year']);

SELECT create_index_if_columns_exist('idx_posts_created_at', 'posts', '(created_at DESC)', ARRAY['created_at']);
SELECT create_index_if_columns_exist('idx_posts_author_created_at', 'posts', '(author_id, created_at DESC)', ARRAY['author_id', 'created_at']);
SELECT create_index_if_columns_exist('idx_posts_group_created_at', 'posts', '(group_id, created_at DESC)', ARRAY['group_id', 'created_at']);

SELECT create_index_if_columns_exist('idx_post_comments_post_created_at', 'post_comments', '(post_id, created_at DESC)', ARRAY['post_id', 'created_at']);
SELECT create_index_if_columns_exist('idx_post_reactions_post_created_at', 'post_reactions', '(post_id, created_at DESC)', ARRAY['post_id', 'created_at']);
SELECT create_index_if_columns_exist('idx_post_reactions_user_created_at', 'post_reactions', '(user_id, created_at DESC)', ARRAY['user_id', 'created_at']);

SELECT create_index_if_columns_exist('idx_stories_author_created_at', 'stories', '(author_id, created_at DESC)', ARRAY['author_id', 'created_at']);
SELECT create_index_if_columns_exist('idx_stories_expires_at', 'stories', '(expires_at)', ARRAY['expires_at']);

SELECT create_index_if_columns_exist('idx_conversation_messages_conversation_created_at', 'conversation_messages', '(conversation_id, created_at DESC)', ARRAY['conversation_id', 'created_at']);
SELECT create_index_if_columns_exist('idx_conversation_members_conversation_user', 'conversation_members', '(conversation_id, user_id)', ARRAY['conversation_id', 'user_id']);
SELECT create_index_if_columns_exist('idx_conversation_messages_recipient_delivered', 'conversation_messages', '(recipient_id, delivered_at)', ARRAY['recipient_id', 'delivered_at']);
SELECT create_index_if_columns_exist('idx_conversation_messages_recipient_read', 'conversation_messages', '(recipient_id, read_at)', ARRAY['recipient_id', 'read_at']);

SELECT create_index_if_columns_exist('idx_notifications_user_created_at', 'notifications', '(user_id, created_at DESC)', ARRAY['user_id', 'created_at']);
SELECT create_index_if_columns_exist('idx_notifications_user_read_at', 'notifications', '(user_id, read_at)', ARRAY['user_id', 'read_at']);

SELECT create_index_if_columns_exist('idx_user_follows_follower', 'user_follows', '(follower_id)', ARRAY['follower_id']);
SELECT create_index_if_columns_exist('idx_user_follows_following', 'user_follows', '(following_id)', ARRAY['following_id']);

SELECT create_index_if_columns_exist('idx_live_chat_messages_created_at', 'live_chat_messages', '(created_at DESC)', ARRAY['created_at']);
SELECT create_index_if_columns_exist('idx_live_chat_messages_user_created_at', 'live_chat_messages', '(user_id, created_at DESC)', ARRAY['user_id', 'created_at']);

SELECT create_index_if_columns_exist('idx_group_members_group_user', 'group_members', '(group_id, user_id)', ARRAY['group_id', 'user_id']);
SELECT create_index_if_columns_exist('idx_group_join_requests_group_status', 'group_join_requests', '(group_id, status)', ARRAY['group_id', 'status']);
SELECT create_index_if_columns_exist('idx_group_invites_user_status', 'group_invites', '(invited_user_id, status)', ARRAY['invited_user_id', 'status']);

SELECT create_index_if_columns_exist('idx_event_responses_event_user', 'event_responses', '(event_id, user_id)', ARRAY['event_id', 'user_id']);
SELECT create_index_if_columns_exist('idx_event_comments_event_created_at', 'event_comments', '(event_id, created_at DESC)', ARRAY['event_id', 'created_at']);

SELECT create_index_if_columns_exist('idx_media_assets_entity', 'media_assets', '(entity_type, entity_id)', ARRAY['entity_type', 'entity_id']);
SELECT create_index_if_columns_exist('idx_media_assets_user', 'media_assets', '(user_id)', ARRAY['user_id']);

SELECT create_index_if_columns_exist('idx_identity_verification_user_status', 'identity_verification_requests', '(user_id, status)', ARRAY['user_id', 'status']);
SELECT create_index_if_columns_exist('idx_support_requests_user_status', 'support_requests', '(user_id, status)', ARRAY['user_id', 'status']);

SELECT create_index_if_columns_exist('idx_moderation_permissions_user', 'moderation_permissions', '(user_id)', ARRAY['user_id']);
SELECT create_index_if_columns_exist('idx_moderation_scopes_user', 'moderation_scopes', '(user_id)', ARRAY['user_id']);

SELECT create_index_if_columns_exist('idx_audit_logs_created_at', 'audit_logs', '(created_at DESC)', ARRAY['created_at']);
SELECT create_index_if_columns_exist('idx_audit_logs_actor_created_at', 'audit_logs', '(actor_user_id, created_at DESC)', ARRAY['actor_user_id', 'created_at']);

SELECT create_index_if_columns_exist('idx_user_engagement_scores_score', 'user_engagement_scores', '(score DESC)', ARRAY['score']);
SELECT create_index_if_columns_exist('idx_user_engagement_scores_variant_score', 'user_engagement_scores', '(ab_variant, score DESC)', ARRAY['ab_variant', 'score']);

DROP FUNCTION create_index_if_columns_exist(TEXT, TEXT, TEXT, TEXT[]);

COMMIT;
