BEGIN;

CREATE TABLE IF NOT EXISTS connection_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  receiver_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  responded_at TIMESTAMPTZ,
  CHECK (sender_id <> receiver_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_connection_requests_sender_receiver
  ON connection_requests (sender_id, receiver_id);

CREATE INDEX IF NOT EXISTS idx_connection_requests_receiver_status
  ON connection_requests (receiver_id, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_connection_requests_sender_status
  ON connection_requests (sender_id, status, created_at DESC);

COMMIT;
