BEGIN;

CREATE TABLE IF NOT EXISTS languages (
  code TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  native_name TEXT NOT NULL,
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS language_strings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lang_code TEXT NOT NULL REFERENCES languages(code) ON DELETE CASCADE,
  key TEXT NOT NULL,
  value TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (lang_code, key)
);

CREATE INDEX IF NOT EXISTS idx_language_strings_lang_code ON language_strings (lang_code);
CREATE INDEX IF NOT EXISTS idx_language_strings_key ON language_strings (key);

-- Seed built-in languages
INSERT INTO languages (code, name, native_name, is_default, is_active) VALUES
  ('tr', 'Turkish', 'Türkçe', TRUE, TRUE),
  ('en', 'English', 'English', FALSE, TRUE),
  ('de', 'German', 'Deutsch', FALSE, TRUE),
  ('fr', 'French', 'Français', FALSE, TRUE)
ON CONFLICT (code) DO NOTHING;

COMMIT;
