BEGIN;

CREATE TABLE IF NOT EXISTS notification_push_settings (
  id INTEGER PRIMARY KEY,
  push_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT notification_push_settings_singleton_id CHECK (id = 1)
);

INSERT INTO notification_push_settings (id, push_enabled, updated_at)
VALUES (1, FALSE, NOW())
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS notification_push_devices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  installation_id TEXT NOT NULL UNIQUE,
  platform TEXT NOT NULL,
  push_token TEXT NOT NULL UNIQUE,
  locale TEXT,
  app_version TEXT,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_notification_push_devices_user_enabled
  ON notification_push_devices (user_id, enabled, updated_at DESC);

CREATE TABLE IF NOT EXISTS notification_push_delivery_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notification_id BIGINT REFERENCES notifications(id) ON DELETE SET NULL,
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  device_id BIGINT REFERENCES notification_push_devices(id) ON DELETE SET NULL,
  platform TEXT,
  notification_type TEXT,
  delivery_status TEXT NOT NULL,
  skip_reason TEXT,
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_notification_push_delivery_created
  ON notification_push_delivery_audit (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notification_push_delivery_status
  ON notification_push_delivery_audit (delivery_status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notification_push_delivery_notification
  ON notification_push_delivery_audit (notification_id, created_at DESC);

COMMIT;
