BEGIN;

ALTER TABLE album_categories
  ADD COLUMN IF NOT EXISTS visibility_scope TEXT NOT NULL DEFAULT 'public',
  ADD COLUMN IF NOT EXISTS cohort_year TEXT,
  ADD COLUMN IF NOT EXISTS album_type TEXT NOT NULL DEFAULT 'general',
  ADD COLUMN IF NOT EXISTS owner_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS is_system_album BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS cover_file_name TEXT,
  ADD COLUMN IF NOT EXISTS cover_mode TEXT NOT NULL DEFAULT 'latest';

ALTER TABLE album_photos
  ADD COLUMN IF NOT EXISTS allow_comments BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS tagged_user_ids_json TEXT NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS album_group_key TEXT,
  ADD COLUMN IF NOT EXISTS album_group_index INTEGER NOT NULL DEFAULT 0;

ALTER TABLE album_photo_comments
  ADD COLUMN IF NOT EXISTS author_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS album_photo_likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  photo_id BIGINT NOT NULL REFERENCES album_photos(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (photo_id, user_id)
);

CREATE TABLE IF NOT EXISTS album_category_permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT NOT NULL REFERENCES album_categories(id) ON DELETE CASCADE,
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  group_id BIGINT REFERENCES groups(id) ON DELETE CASCADE,
  created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (user_id IS NOT NULL OR group_id IS NOT NULL)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_album_category_permissions_category_user
  ON album_category_permissions (category_id, user_id)
  WHERE user_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_album_category_permissions_category_group
  ON album_category_permissions (category_id, group_id)
  WHERE group_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_album_categories_visibility_scope
  ON album_categories (visibility_scope, cohort_year, is_active);

CREATE INDEX IF NOT EXISTS idx_album_categories_owner_user_id
  ON album_categories (owner_user_id, album_type, is_active);

CREATE INDEX IF NOT EXISTS idx_album_photo_likes_photo_id
  ON album_photo_likes (photo_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_album_photo_comments_author_user_id
  ON album_photo_comments (author_user_id, photo_id);

COMMIT;
