ALTER TABLE events ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
