BEGIN;

ALTER TABLE events ADD COLUMN IF NOT EXISTS show_in_feed INTEGER NOT NULL DEFAULT 1;
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS show_in_feed INTEGER NOT NULL DEFAULT 1;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS show_in_feed INTEGER NOT NULL DEFAULT 1;
ALTER TABLE group_events ADD COLUMN IF NOT EXISTS show_in_feed INTEGER NOT NULL DEFAULT 1;
ALTER TABLE group_announcements ADD COLUMN IF NOT EXISTS show_in_feed INTEGER NOT NULL DEFAULT 1;

COMMIT;
