BEGIN;

CREATE TABLE IF NOT EXISTS content_approval_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type TEXT NOT NULL,
  group_id INTEGER,
  approval_required INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL,
  updated_by INTEGER,
  UNIQUE(entity_type, group_id)
);

INSERT OR IGNORE INTO content_approval_settings (entity_type, group_id, approval_required, updated_at)
VALUES
  ('event', NULL, 0, CURRENT_TIMESTAMP),
  ('announcement', NULL, 0, CURRENT_TIMESTAMP),
  ('job', NULL, 0, CURRENT_TIMESTAMP),
  ('group_event', NULL, 0, CURRENT_TIMESTAMP),
  ('group_announcement', NULL, 0, CURRENT_TIMESTAMP),
  ('group_post', NULL, 0, CURRENT_TIMESTAMP);

ALTER TABLE events ADD COLUMN IF NOT EXISTS publication_status TEXT NOT NULL DEFAULT 'published';
ALTER TABLE events ADD COLUMN IF NOT EXISTS approval_status TEXT NOT NULL DEFAULT 'not_required';
ALTER TABLE events ADD COLUMN IF NOT EXISTS review_note TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS reviewed_by INTEGER;
ALTER TABLE events ADD COLUMN IF NOT EXISTS reviewed_at TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS published_at TEXT;

ALTER TABLE announcements ADD COLUMN IF NOT EXISTS publication_status TEXT NOT NULL DEFAULT 'published';
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS approval_status TEXT NOT NULL DEFAULT 'not_required';
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS review_note TEXT;
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS reviewed_by INTEGER;
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS reviewed_at TEXT;
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS published_at TEXT;

ALTER TABLE jobs ADD COLUMN IF NOT EXISTS publication_status TEXT NOT NULL DEFAULT 'published';
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS approval_status TEXT NOT NULL DEFAULT 'not_required';
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS review_note TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS reviewed_by INTEGER;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS reviewed_at TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS published_at TEXT;

ALTER TABLE group_events ADD COLUMN IF NOT EXISTS publication_status TEXT NOT NULL DEFAULT 'published';
ALTER TABLE group_events ADD COLUMN IF NOT EXISTS approval_status TEXT NOT NULL DEFAULT 'not_required';
ALTER TABLE group_events ADD COLUMN IF NOT EXISTS review_note TEXT;
ALTER TABLE group_events ADD COLUMN IF NOT EXISTS reviewed_by INTEGER;
ALTER TABLE group_events ADD COLUMN IF NOT EXISTS reviewed_at TEXT;
ALTER TABLE group_events ADD COLUMN IF NOT EXISTS published_at TEXT;

ALTER TABLE group_announcements ADD COLUMN IF NOT EXISTS publication_status TEXT NOT NULL DEFAULT 'published';
ALTER TABLE group_announcements ADD COLUMN IF NOT EXISTS approval_status TEXT NOT NULL DEFAULT 'not_required';
ALTER TABLE group_announcements ADD COLUMN IF NOT EXISTS review_note TEXT;
ALTER TABLE group_announcements ADD COLUMN IF NOT EXISTS reviewed_by INTEGER;
ALTER TABLE group_announcements ADD COLUMN IF NOT EXISTS reviewed_at TEXT;
ALTER TABLE group_announcements ADD COLUMN IF NOT EXISTS published_at TEXT;

ALTER TABLE posts ADD COLUMN IF NOT EXISTS publication_status TEXT NOT NULL DEFAULT 'published';
ALTER TABLE posts ADD COLUMN IF NOT EXISTS approval_status TEXT NOT NULL DEFAULT 'not_required';
ALTER TABLE posts ADD COLUMN IF NOT EXISTS review_note TEXT;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS reviewed_by INTEGER;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS reviewed_at TEXT;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS published_at TEXT;

UPDATE events
SET publication_status = CASE
    WHEN LOWER(COALESCE(CAST(approved AS TEXT), 'true')) IN ('1', 'true', 'evet', 'yes') THEN 'published'
    WHEN COALESCE(show_in_feed, 1) = 0 THEN 'draft'
    ELSE 'pending_publication'
  END,
  approval_status = CASE
    WHEN LOWER(COALESCE(CAST(approved AS TEXT), 'true')) IN ('1', 'true', 'evet', 'yes') THEN 'not_required'
    WHEN COALESCE(show_in_feed, 1) = 0 THEN 'not_required'
    ELSE 'pending'
  END,
  published_at = CASE WHEN LOWER(COALESCE(CAST(approved AS TEXT), 'true')) IN ('1', 'true', 'evet', 'yes') THEN COALESCE(approved_at, created_at) ELSE published_at END;

UPDATE announcements
SET publication_status = CASE
    WHEN LOWER(COALESCE(CAST(approved AS TEXT), 'true')) IN ('1', 'true', 'evet', 'yes') THEN 'published'
    WHEN COALESCE(show_in_feed, 1) = 0 THEN 'draft'
    ELSE 'pending_publication'
  END,
  approval_status = CASE
    WHEN LOWER(COALESCE(CAST(approved AS TEXT), 'true')) IN ('1', 'true', 'evet', 'yes') THEN 'not_required'
    WHEN COALESCE(show_in_feed, 1) = 0 THEN 'not_required'
    ELSE 'pending'
  END,
  published_at = CASE WHEN LOWER(COALESCE(CAST(approved AS TEXT), 'true')) IN ('1', 'true', 'evet', 'yes') THEN COALESCE(approved_at, created_at) ELSE published_at END;

UPDATE jobs
SET publication_status = CASE WHEN COALESCE(show_in_feed, 1) = 0 THEN 'draft' ELSE 'published' END,
  approval_status = 'not_required',
  published_at = CASE WHEN COALESCE(show_in_feed, 1) = 1 THEN created_at ELSE published_at END;

UPDATE group_events
SET publication_status = CASE WHEN COALESCE(show_in_feed, 1) = 0 THEN 'draft' ELSE 'published' END,
  approval_status = 'not_required',
  published_at = CASE WHEN COALESCE(show_in_feed, 1) = 1 THEN created_at ELSE published_at END;

UPDATE group_announcements
SET publication_status = CASE WHEN COALESCE(show_in_feed, 1) = 0 THEN 'draft' ELSE 'published' END,
  approval_status = 'not_required',
  published_at = CASE WHEN COALESCE(show_in_feed, 1) = 1 THEN created_at ELSE published_at END;

UPDATE posts
SET publication_status = 'published',
  approval_status = 'not_required',
  published_at = COALESCE(published_at, created_at)
WHERE group_id IS NOT NULL;

COMMIT;
