BEGIN;

CREATE TABLE IF NOT EXISTS content_approval_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type TEXT NOT NULL,
  group_id INTEGER,
  approval_required INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL,
  updated_by INTEGER,
  UNIQUE(entity_type, group_id)
);

INSERT INTO content_approval_settings (entity_type, group_id, approval_required, updated_at)
SELECT seed.entity_type, seed.group_id, seed.approval_required, seed.updated_at
FROM (
  VALUES
    ('event', NULL::INTEGER, 0, CURRENT_TIMESTAMP),
    ('announcement', NULL::INTEGER, 0, CURRENT_TIMESTAMP),
    ('job', NULL::INTEGER, 0, CURRENT_TIMESTAMP),
    ('group_event', NULL::INTEGER, 0, CURRENT_TIMESTAMP),
    ('group_announcement', NULL::INTEGER, 0, CURRENT_TIMESTAMP),
    ('group_post', NULL::INTEGER, 0, CURRENT_TIMESTAMP)
) AS seed(entity_type, group_id, approval_required, updated_at)
WHERE NOT EXISTS (
  SELECT 1
  FROM content_approval_settings existing
  WHERE existing.entity_type = seed.entity_type
    AND existing.group_id IS NOT DISTINCT FROM seed.group_id
);

ALTER TABLE events ADD COLUMN IF NOT EXISTS publication_status TEXT NOT NULL DEFAULT 'published';
ALTER TABLE events ADD COLUMN IF NOT EXISTS approval_status TEXT NOT NULL DEFAULT 'not_required';
ALTER TABLE events ADD COLUMN IF NOT EXISTS image TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS created_by INTEGER;
ALTER TABLE events ADD COLUMN IF NOT EXISTS approved INTEGER DEFAULT 1;
ALTER TABLE events ADD COLUMN IF NOT EXISTS approved_by INTEGER;
ALTER TABLE events ADD COLUMN IF NOT EXISTS approved_at TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS review_note TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS reviewed_by INTEGER;
ALTER TABLE events ADD COLUMN IF NOT EXISTS reviewed_at TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS published_at TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS show_in_feed INTEGER DEFAULT 1;
ALTER TABLE events ADD COLUMN IF NOT EXISTS allow_comments INTEGER DEFAULT 1;
ALTER TABLE events ADD COLUMN IF NOT EXISTS allow_likes INTEGER DEFAULT 1;
ALTER TABLE events ADD COLUMN IF NOT EXISTS show_response_counts INTEGER DEFAULT 1;
ALTER TABLE events ADD COLUMN IF NOT EXISTS show_attendee_names INTEGER DEFAULT 0;
ALTER TABLE events ADD COLUMN IF NOT EXISTS show_decliner_names INTEGER DEFAULT 0;

ALTER TABLE announcements ADD COLUMN IF NOT EXISTS publication_status TEXT NOT NULL DEFAULT 'published';
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS approval_status TEXT NOT NULL DEFAULT 'not_required';
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS image TEXT;
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS created_by INTEGER;
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS approved INTEGER DEFAULT 1;
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS approved_by INTEGER;
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS approved_at TEXT;
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS review_note TEXT;
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS reviewed_by INTEGER;
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS reviewed_at TEXT;
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS published_at TEXT;
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS show_in_feed INTEGER DEFAULT 1;
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS allow_comments INTEGER DEFAULT 1;
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS allow_likes INTEGER DEFAULT 1;

ALTER TABLE jobs ADD COLUMN IF NOT EXISTS publication_status TEXT NOT NULL DEFAULT 'published';
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS approval_status TEXT NOT NULL DEFAULT 'not_required';
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS work_mode TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS image TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS review_note TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS reviewed_by INTEGER;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS reviewed_at TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS published_at TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS show_in_feed INTEGER DEFAULT 1;

ALTER TABLE group_events ADD COLUMN IF NOT EXISTS publication_status TEXT NOT NULL DEFAULT 'published';
ALTER TABLE group_events ADD COLUMN IF NOT EXISTS approval_status TEXT NOT NULL DEFAULT 'not_required';
ALTER TABLE group_events ADD COLUMN IF NOT EXISTS review_note TEXT;
ALTER TABLE group_events ADD COLUMN IF NOT EXISTS reviewed_by INTEGER;
ALTER TABLE group_events ADD COLUMN IF NOT EXISTS reviewed_at TEXT;
ALTER TABLE group_events ADD COLUMN IF NOT EXISTS published_at TEXT;
ALTER TABLE group_events ADD COLUMN IF NOT EXISTS show_in_feed INTEGER DEFAULT 1;

ALTER TABLE group_announcements ADD COLUMN IF NOT EXISTS publication_status TEXT NOT NULL DEFAULT 'published';
ALTER TABLE group_announcements ADD COLUMN IF NOT EXISTS approval_status TEXT NOT NULL DEFAULT 'not_required';
ALTER TABLE group_announcements ADD COLUMN IF NOT EXISTS review_note TEXT;
ALTER TABLE group_announcements ADD COLUMN IF NOT EXISTS reviewed_by INTEGER;
ALTER TABLE group_announcements ADD COLUMN IF NOT EXISTS reviewed_at TEXT;
ALTER TABLE group_announcements ADD COLUMN IF NOT EXISTS published_at TEXT;
ALTER TABLE group_announcements ADD COLUMN IF NOT EXISTS show_in_feed INTEGER DEFAULT 1;

ALTER TABLE posts ADD COLUMN IF NOT EXISTS publication_status TEXT NOT NULL DEFAULT 'published';
ALTER TABLE posts ADD COLUMN IF NOT EXISTS approval_status TEXT NOT NULL DEFAULT 'not_required';
ALTER TABLE posts ADD COLUMN IF NOT EXISTS review_note TEXT;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS reviewed_by INTEGER;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS reviewed_at TEXT;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS published_at TEXT;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS show_in_feed INTEGER DEFAULT 1;

UPDATE events
SET publication_status = CASE
    WHEN LOWER(COALESCE(CAST(approved AS TEXT), 'true')) IN ('1', 'true', 'evet', 'yes') THEN 'published'
    WHEN COALESCE(show_in_feed, 1) = 0 THEN 'draft'
    ELSE 'pending_publication'
  END,
  approval_status = CASE
    WHEN LOWER(COALESCE(CAST(approved AS TEXT), 'true')) IN ('1', 'true', 'evet', 'yes') THEN 'not_required'
    WHEN COALESCE(show_in_feed, 1) = 0 THEN 'not_required'
    ELSE 'pending'
  END,
  published_at = CASE
    WHEN LOWER(COALESCE(CAST(approved AS TEXT), 'true')) IN ('1', 'true', 'evet', 'yes')
      THEN COALESCE(CAST(approved_at AS TEXT), CAST(created_at AS TEXT))
    ELSE published_at
  END;

UPDATE announcements
SET publication_status = CASE
    WHEN LOWER(COALESCE(CAST(approved AS TEXT), 'true')) IN ('1', 'true', 'evet', 'yes') THEN 'published'
    WHEN COALESCE(show_in_feed, 1) = 0 THEN 'draft'
    ELSE 'pending_publication'
  END,
  approval_status = CASE
    WHEN LOWER(COALESCE(CAST(approved AS TEXT), 'true')) IN ('1', 'true', 'evet', 'yes') THEN 'not_required'
    WHEN COALESCE(show_in_feed, 1) = 0 THEN 'not_required'
    ELSE 'pending'
  END,
  published_at = CASE
    WHEN LOWER(COALESCE(CAST(approved AS TEXT), 'true')) IN ('1', 'true', 'evet', 'yes')
      THEN COALESCE(CAST(approved_at AS TEXT), CAST(created_at AS TEXT))
    ELSE published_at
  END;

UPDATE jobs
SET publication_status = CASE WHEN COALESCE(show_in_feed, 1) = 0 THEN 'draft' ELSE 'published' END,
  approval_status = 'not_required',
  published_at = CASE WHEN COALESCE(show_in_feed, 1) = 1 THEN CAST(created_at AS TEXT) ELSE published_at END;

UPDATE group_events
SET publication_status = CASE WHEN COALESCE(show_in_feed, 1) = 0 THEN 'draft' ELSE 'published' END,
  approval_status = 'not_required',
  published_at = CASE WHEN COALESCE(show_in_feed, 1) = 1 THEN CAST(created_at AS TEXT) ELSE published_at END;

UPDATE group_announcements
SET publication_status = CASE WHEN COALESCE(show_in_feed, 1) = 0 THEN 'draft' ELSE 'published' END,
  approval_status = 'not_required',
  published_at = CASE WHEN COALESCE(show_in_feed, 1) = 1 THEN CAST(created_at AS TEXT) ELSE published_at END;

UPDATE posts
SET publication_status = 'published',
  approval_status = 'not_required',
  published_at = COALESCE(published_at, CAST(created_at AS TEXT))
WHERE group_id IS NOT NULL;

COMMIT;
