BEGIN;

CREATE TABLE IF NOT EXISTS user_activity_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL,
  target_type TEXT,
  target_id TEXT,
  metadata JSONB,
  request_id TEXT,
  ip_hash TEXT,
  user_agent TEXT,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_user_activity_events_actor_time
  ON user_activity_events (actor_user_id, occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_user_activity_events_target_time
  ON user_activity_events (target_type, target_id, occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_user_activity_events_type_time
  ON user_activity_events (event_type, occurred_at DESC);

COMMIT;
